### ISSUE TITLE
Problem building freac 1.1 from AUR

### ISSUE THREAD

**Issue by DarkSwan86** [enzo1982/freac#100]
Hi @enzo1982 ,

it's me again, sorry! ^^"

Now i can build Boca 1.0 (see https://github.com/enzo1982/BoCA/issues/7 ) but i still can't build freac 1.1 from AUR.

This is the building log:

==> Avvio di build() in corso...
mkdir -p bin objects
g++ -I"/var/tmp/pamac-build-leonardo/freac/src/freac-1.1"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt src/cddb/cddb.cpp -o objects/cddb.o
g++ -I"/var/tmp/pamac-build-leonardo/freac/src/freac-1.1"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt src/cddb/cddbbatch.cpp -o objects/cddbbatch.o
g++ -I"/var/tmp/pamac-build-leonardo/freac/src/freac-1.1"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt src/cddb/cddbcache.cpp -o objects/cddbcache.o
g++ -I"/var/tmp/pamac-build-leonardo/freac/src/freac-1.1"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt src/cddb/cddbinfo.cpp -o objects/cddbinfo.o
g++ -I"/var/tmp/pamac-build-leonardo/freac/src/freac-1.1"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt src/cddb/cddblocal.cpp -o objects/cddblocal.o
src/cddb/cddbinfo.cpp: In member function ‘smooth::Bool freac::CDDBInfo::UpdateTrack(BoCA::Track&) const’:
src/cddb/cddbinfo.cpp:178:9: error: ‘class BoCA::Track’ has no member named ‘outputFile’; did you mean ‘outfile’?
  178 |   track.outputFile = NIL;
      |         ^~~~~~~~~~
      |         outfile
make: *** [Makefile:302: objects/cddbinfo.o] Errore 1
make: *** Attesa per i processi non terminati....
==> ERRORE: Si è verificato un errore in build().
    L'operazione sta per essere interrotta...

I'm sorry for bothering you but i'm still new to building from AUR, thanks!

**Comment by enzo1982** [comment]
It's the same issue as enzo1982/BoCA#7 basically. Just now with BoCA instead of smooth. You have an old version of BoCA installed in /usr/local and the compiler is finding that one.

Try removing it using:

rm -fr /usr/local/include/boca*
rm -fr /usr/local/lib/boca
rm -f /usr/local/lib/libboca*

**Comment by DarkSwan86** [comment]
Ok almost there! Now it compiles perfectly but i think it's conflicting with the old installation. Here is the error:
![Screenshot_20200403_134426](https://user-images.githubusercontent.com/24975273/78357343-95bbde80-75b1-11ea-9d13-415b163215de.png)

I think it's best to delete all the old files and the folder of the previous installation but i don't know where freac put itself when is compiled. Where i should have to look to purge it completely and recompile everything from scratch from AUR? Thanks and sorry again!

**Comment by enzo1982** [comment]
rm -f /usr/local/bin/freac*
rm -fr /usr/local/lib/freac
rm -fr /usr/local/share/freac

That should be enough.

You should also re-compile BoCA and fre:ac completely again, as some files might have been compiled with the old smooth and BoCA headers and some with the new. That might result in instability.

**Comment by DarkSwan86** [comment]
Finally everything works!! Thanks for all the help @enzo1982 !
