### ISSUE TITLE
add discid as variable to naming.

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#101]
**Is your feature request related to a problem? Please describe.**
Sometimes my cds are not recognised while ripping with freaccmd and cddb query activated. freaccmd names them as "unknown artist" for artist and "unknown album" as album. if i rip more than one cd in that session without immediately renaming the first, the files get overwritten

**Describe the solution you'd like**
add a new variable/pattern for the discid so that i can use this in the naming pattern to differentiate the cds without overwriting them.

**Comment by enzo1982** [comment]
Thank you for your suggestion!

The latest continuous build adds the <discid> placeholder and an optional joblist column displaying the disc ID.

**Comment by wkremser** [comment]
thank you, i will try that feature out tomorrow. ist there a way to list all available placeholders in freaccmd with a special help command? i was not able to find a list of all available placeholders.

**Comment by enzo1982** [comment]
Oh, the list of available placeholders is here: https://freac.org/manual/en/howto.html#anchor_pat

**Comment by wkremser** [comment]
ah, i was not sure if these are all. last time i looked was a month ago or so :)

**Comment by wkremser** [comment]
placeholder works as expected. thank you for the quick resolution.
