### ISSUE TITLE
CDParanoia mode brings up an error, then crashes Freac

### ISSUE THREAD

**Issue by Rhawne** [enzo1982/freac#104]
when attempting to rip a CD using Freac with CDParanoia mode on, Freac brings up an error:

"The CD-ROM drive appears to be seeking impossibly quickly.
This could be due to timer bugs, a drive that really is improbably fast, 
or, most likely, a bug in cdparanoia's cache modelling.

Please consider using another drive for ripping audio CDs and send a bug
report to support@freac.org to assist developers in correcting the problem."

this started occurring after ripping several CDs using the newly updated version 1.1 of the software, and so far only on one CD. After dismissing this warning dialogue, Freac will go on to rip the rest of the CD with no trouble - the first track is the only one that seems to trouble it. If I try to rip just the first track that Freac will not rip, the application throws up the above error, and crashes. The CD is clean with no marks on the surface of the disk. 

To reproduce the error I have done this:
1) Open the application
2) Click the "add audio CD contents to this playlist"
3) Waited for the CDDB request, and selected the content from the list
3b) deselect all tracks except track 1 - the track that won't rip
4) clicked the "start the encoding process" button
5) disk drive seeks and it sounds like it's about to start ripping
6) Error
7) Crash, unless:
7b) After error is dismissed, Freac rips the other tracks on the album, just not track 1

![image](https://user-images.githubusercontent.com/63528199/79059798-c76b2e80-7cb0-11ea-82b8-3b9e0d3518f3.png)

System Specifications:
AMD Ryzen 2700X
X470 chipset
32gb RAM
nVidia GeForce 1080
LG Slim Portable DVD Writer GP60NB50

Extra details:
- The CD I'm trying to rip is the Australian release of Nine Inch Nails's Pretty Hate Machine and the track that fails is Head Like a Hole
- I am mainly using the LAME 3.10 MP3 encoder, but it errors out the same with all the other encoders I've tried (AAC, FLAC, WMA, WAV)
- After shifting my DVDRW to a new USB port, the rip got to 5% before error, instead of immediately
- Enacting a speed limit doesn't seem to stop the error from occurring or the crash

**Comment by enzo1982** [comment]
Thank you for reporting this!

This should be fixed with commit enzo1982/boca@83099cd. The fix will be included with the next update (to be released within 2-3 days).

**Comment by enzo1982** [comment]
fre:ac 1.1.1 is now available with the fix mentioned before. Closing this ticket.

Please add a comment here if this does not actually fix the issue for you.

**Comment by akayueh** [comment]
I am having the same issue, Verbatim External USB-C Blu-ray Writer, PIONEER BDR-UD04).

If i don't turn this mode on, there are regular poping noise in the FLAC files, not sure why.

![FB_IMG_1717924258639](https://github.com/enzo1982/freac/assets/3982857/3d4808a8-8abe-4f79-adcf-c1d89a441880)
![FB_IMG_1717924249674](https://github.com/enzo1982/freac/assets/3982857/25c06491-dca4-49aa-984e-60e0fde5b217)
