### ISSUE TITLE
M4B files split incorrectly 

### ISSUE THREAD

**Issue by gustgeo** [enzo1982/freac#110]
**Describe the bug**

When I add a single M4B file (audiobook) freac automatically recognises chapters (amazing feature). Seems like there is some error on recognising the time tags for the last chapter...

I am trying to convert the automatically recognised chapters into separate MP3 files and all works well until the last file. It is noticeable on the interface (see attached screenshot) that something is wrong, and when I try to proceed the last chapter file does not save properly, it comes out as a very small file filled with silence and whole final chapter is missing. 

I have tried this with two different M4B files and had the same issue. 

Have tried on both the Mac and Windows versions and both act the same.

Seems like there is some error on recognising the time tags for the last chapter...

**Screenshots**
<img width="632" alt="Screenshot 2020-05-06 at 20 22 48" src="https://user-images.githubusercontent.com/64922758/81215568-d4dab680-8fd9-11ea-88af-7b77c753e44d.png">

**System (please complete the following information)**
macOS Catalina 10.15.3 and Windows 7 (32bit)
 - CPU: [Intel Core i7]
 - RAM: [8 GB]

**Comment by enzo1982** [comment]
I cannot reproduce this with the .m4b files I have. Could you share one of the files where you are seeing this behavior? I will then analyze it and try to find a fix. If you cannot share it here, please send a link to support@freac.org.

**Comment by gustgeo** [comment]
I have forwarded a file to support@freaac.ord.
Unfortunately I cannot share it openly.

I think the issue might be related to a missing "total file duration" information on the tag information of some of my files. 

The chapter tags come as "time stamps" that mark the beginning of a chapter, for all the initial and middle chapters the "end time stamp" is the "start time stamp" of the next chapter. But for the last chapter the "end time stamp" is the duration of the whole audio file. 

When I compare the audio file duration on freac and on my file explorer (MAC Finder) I get different values as can be seen on the attached screenshot bellow. This is likely to be the cause I think...

<img width="912" alt="Screenshot 2020-05-07 at 12 45 37" src="https://user-images.githubusercontent.com/64922758/81286607-a0aad880-9061-11ea-9347-83b70eacdad6.png">

**Comment by enzo1982** [comment]
Thank you for providing the sample file!

The problem is that the last chapter does not specify a duration and fre:ac did not handle this case. I think it's legitimate for .m4b files to not specify a duration on the last chapter. This should then be interpreted as lasting to the end of the track.

I fixed this in the MP4 tagger component which is responsible for reading chapter data. The fix will be in the upcoming fre:ac 1.1.2.

I can provide patched binaries for you to use in the meantime. Would 32 bit Windows binaries be ok or do you need a macOS version? The latter would be slightly more work for me, but I can provide it on your request.

**Comment by enzo1982** [comment]
Here's the fix for the 32 bit Windows version already: [boca_tagger_mp4.1.0.zip](https://github.com/enzo1982/freac/files/4594969/boca_tagger_mp4.1.0.zip)

Just replace the existing `boca_tagger_mp4.1.0.dll` in the `boca` folder with the new version.

**Comment by gustgeo** [comment]
That is great! 
Thanks for the Windows version update, I can easily use the windows version until the next 1.1.2 version is out on your own timeline.
Thanks again.
