### ISSUE TITLE
OPUS bitrate not being honoured

### ISSUE THREAD

**Issue by mitchray** [enzo1982/freac#111]
**Describe the bug**
~50-60kbps is added to the desired bitrate of OPUS encoder, neither "Enable variable bitrate encoding" nor "Constrain bitrate to target value" are having any effect

**To Reproduce**
1. Configure OPUS Audio Encoder v1.3.1
2. Set Bitrate to 160kbps
3. Inspect output file with MediaInfo

**Expected behavior**
For example, desired bitrate of 160kbps to be output at ~160kbps

**Screenshots**
fre:ac 160kbps outputting ~216kbps file
<img width="218" alt="mediainfo_2020-05-16_23-14-36" src="https://user-images.githubusercontent.com/5735900/82120659-24d02f00-97cb-11ea-905b-0e03eb83a990.png">

Compared with WinFF 160kbps
<img width="217" alt="mediainfo_2020-05-16_23-14-52" src="https://user-images.githubusercontent.com/5735900/82120660-2699f280-97cb-11ea-8baa-a6b509698941.png">

**System (please complete the following information)**
 - OS: Windows 10
 - CPU: Intel Core i5 2500K
 - RAM: 16GB

**Comment by enzo1982** [comment]
Cannot reproduce this here. Could it be that your output file has some large cover art embedded?

It could be that WinFF discards cover art and thus outputs a smaller file. Also MediaInfo might include the Comment header containing the cover art in its bitrate calculation.

You can configure cover art handling in fre:ac's configuration dialog under _Tags->"Cover art"_. Try disabling the _"Write cover art to tags"_ option.

**Comment by mitchray** [comment]
Yup it was the embedded album art causing it, thanks! I'm surprised and saddened that MediaInfo is including that in its calculation..
