### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by jmccabe** [enzo1982/freac#112]
Couple of things; I can split these out if you want, but...

configure file in root of project contains:
    echo "  On Windows:"
    echo
    echo "    - Please use MinGW (http://www.mingw.org/) or Visual Studio 2015"
    echo "      with the msvc/freac/freac.sln project file to build fre:ac"

Readme contains:
    Windows:
        - MinGW GCC v4.0+ (http://www.mingw.org/) or Visual Studio 2019

Which is right?

Also, what would be _really_ nice is, when working with smooth, BoCA and freac, to be able to have a single root folder with all 3 in it, (presumably in folders freac, BoCA and smooth) open the VS solution, and be able to just build things with relative search folders etc correctly set up.

**Comment by enzo1982** [comment]
The solution and project files are for Visual Studio 2019. I'll update the configure scripts to print the correct version.

I'll think about making the changes necessary to build all three projects from a common root folder. That would simplify the process at least a little, indeed.

**Comment by jmccabe** [comment]
Thank you Robert; that would be appreciated. 

Even if it's not a common root folder, just a quick note in the documentation to say where, relatively speaking, they're expected to be would be good. For example, I started with freac, got all the "couldn't find smooth.h" errors, so downloaded and built smooth in the same root folder as freac. Building freac after that gave me "couldn't find BoCA.h" errors, so I downloaded that and unzipped it to the same root folder as the other two. Building BoCA then gave me a load of "couldn't find smooth.h" errors. I had a quick look at the project settings but couldn't see how to quickly change the multitude of projects in the BoCA solution to point to the smooth folder, so gave up.

**Comment by enzo1982** [comment]
Alright, changes have been committed now to allow building smooth, BoCA and fre:ac from a common base folder using Visual Studio. Just make sure the folders are called `smooth` and `boca` (name of the fre:ac folder does not matter).

**Comment by jmccabe** [comment]
Robert,

Thank you for taking the time to do that. I've now cloned all 3 projects into the same base folder and been able to build all 3 with no problems (I also saw that the configure script now mentions VS 2019 too).

John

**Comment by dogancelik** [comment]
While downloading the sources and patches from the website, I've noticed some files don't exist on the server (`404 Not Found`).

```
https://freac.org/patches/flac-1.3.3.tar.gz
https://freac.org/patches/libogg-1.3.4.tar.gz
```

**Comment by enzo1982** [comment]
@dogancelik Thank you, those should be .tar.xz. Links on the website have been fixed.

You don't really need any of those sources to build fre:ac. Instead, you can either copy the codec binaries from the official fre:ac 1.1.3 build or use the `build-codecs` script found in the tools folder of the fre:ac source tree to build your own.

**Comment by tucano42** [comment]
Trying to build freac with Visual Studio 2022.
I cloned smooth, BoCA and freac into a common root folder and then tried to build the x64/Debug configuration.
smooth\msvc\smooth.sln: build solution succeeds
BoCA\msvc\BoCA.sln: build solution succeeds
freac\msvc\freac.sln:

fails on building the extensions. I noticed that they refer to a cdk folder inside the freac folder. So I downloaded freac-cdk-1.1.6-windows-x64.zip and extracted it as cdk inside the freac folder. This seems to replicate the BoCA folder tree. So I opened freac\cdk\msvc\BoCA.sln and built it. Is this correct?

Now I can build freac\msvc\freac.sln and build all extensions that previously failed.

So it is now build, but I cannot run it. All my attempts to copy the created dlls in a folder structure that mimics the official freac release resulted in "freac.dll cannot be loaded".

Is there a script that copies the dlls to a target folder? Do we need to use make in addition to Visual Studio? Please advise.
