### ISSUE TITLE
Support for CRC and put them in log file

### ISSUE THREAD

**Issue by henriqueelder** [enzo1982/freac#114]
Please, add support for CRC and put them in log file.

**Comment by enzo1982** [comment]
Yes, that one's easy, so I think I can add that in the next update.

Just verified that the CRC32 algorithm available to fre:ac is actually the same as used by Exact Audio Copy. So you will be able to compare results using the CRC values from both apps.

**Comment by henriqueelder** [comment]
> Yes, that one's easy, so I think I can add that in the next update.
> 
> Just verified that the CRC32 algorithm available to fre:ac is actually the same as used by Exact Audio Copy. So you will be able to compare results using the CRC values from both apps.

Thank you. I will wait the next update.

**Comment by enzo1982** [comment]
fre:ac 1.1.2 is available now adding CRC checksums to log files when ripping audio CDs.

**Comment by henriqueelder** [comment]
> fre:ac 1.1.2 is available now adding CRC checksums to log files when ripping audio CDs.

Oh my God! Thank you so much.
