### ISSUE TITLE
Cannot run freaccmd via MobaXterm; "MoTTY X11 proxy: Unsupported authorisation protocol"

### ISSUE THREAD

**Issue by Strider3000** [enzo1982/freac#116]
Server: Ubuntu 20.04 LTS headless.
Running freac 1.1.1 (installed via snap 2020.06.11).
Client: MobaXterm (latest) over SSH.

I cannot get freaccmd to run:

root@ubuntu:~# freaccmd
MoTTY X11 proxy: Unsupported authorisation protocol
Error: Unable to open display at localhost:10.0.

If use any other client (teraterm, windows CLI) via SSH I have no problem running freaccmd.
I've tried numerous X11 tweaks on MobaXterm to get freaccmd to run.
Is there any option to run freaccmd completely headless, where it does not trigger X11 at all?

**Comment by enzo1982** [comment]
Just unset your DISPLAY environment variable in the SSH session and it should work. If DISPLAY is not set, freaccmd will not try to open an X11 session.

**Comment by Strider3000** [comment]
Thank you, I used "del os.environ['DISPLAY']" in python to fix this issue. I will close the issue.
