### ISSUE TITLE
"File not found" when attempting to run freaccmd on Ubuntu LTS 20.04

### ISSUE THREAD

**Issue by Strider3000** [enzo1982/freac#117]
Running freaccmd latest via snap install freac 2020.06.11.
Running "freaccmd -m CBR -b 96 test.m4a -o test.mp3" yields "File not found":

root@ubuntu:/# freaccmd -m CBR -b 96 test.m4a -o test.mp3
File not found: test.m4a

The exact same command works fine on Windows.
This seems pretty basic - what idiotic thing am I doing wrong?
The test.m4a file is a real file, and I'm running the command from my / system directory.
Running the command "freaccmd" alone gives me the help dialog (correctly).

**Comment by enzo1982** [comment]
Snaps are running in a confined sandbox and cannot access files in arbitrary locations. The fre:ac Snap can access files in your home directory and can optionally be granted permission to access files on removable media (by connecting the removable-media plug using the snap command). Files outside of those locations are not visible to the Snap.

When I initially created the fre:ac Snap, I suggested to [allow access to paths passed as command line arguments](https://forum.snapcraft.io/t/autoconnect-removable-media-for-fre-ac-snap/9571/3), but as far as I know, this has not been implemented by the Snapcraft project.

You may want to use the Flatpak or AppImage version of fre:ac instead. Both are able to access files in any location (Flatpak has a whole file system permission which was granted to fre:ac and AppImages are not sandboxed at all).

**Comment by Strider3000** [comment]
I got the appimage. How do I run freaccmd from the appimage, or do I need a specific freaccmd appimage?

I managed to get flatpak working (also never used this repo type). I can run flatpak run org.freac.freac but there was no "flatpak run org.freac.freaccmd". Do I need to install a separate package for freaccmd with flatpak?

**Comment by enzo1982** [comment]
With the AppImage, you can simply pass freaccmd as the first argument. Then the usual freaccmd arguments. Alternatively, you can rename the AppImage to freaccmd or create a symlink named freaccmd that points to the AppImage.

With Flatpak, you need to invoke `flatpak run --command=freaccmd org.freac.freac [freccmd arguments]`.

**Comment by Strider3000** [comment]
Hi, thanks for your assistance!
The command "freac-1.1.1-linux-x86_64.AppImage freaccmd --superfast --threads=12 -o test.mp3 test.m4a" worked fine for me.
I will close this ticket.
