### ISSUE TITLE
FreAC 1.1.2 UI is broken in W8.1

### ISSUE THREAD

**Issue by IPeluchito** [enzo1982/freac#120]
**FreAC 1.1.2 UI** is broken in **Windows 8.1** at **4k** resolution and scale **250%** please fix it....
![Freac](https://user-images.githubusercontent.com/64821708/85214350-14adf100-b32f-11ea-87c5-704d674b4c71.png)
**God bless you.**

**Comment by enzo1982** [comment]
Thank you for reporting this!

There was a bug affecting the Windows version on high DPI settings. There's a 1.1.2a hotfix available now that fixes the issue.
