### ISSUE TITLE
converting files - ascii hexa code 20 generated

### ISSUE THREAD

**Issue by Osny95** [enzo1982/freac#122]
Hello,
Small problem when converting files.

File conversion introduces a space (ascii hexa code 20)at the beginning of the name of the generated file. 

Example:
1-mymusic.flac -> [space]1-mymusic.mp3
2-mymusic.flac -> [space]1-mymusic.ogg

**Comment by enzo1982** [comment]
I cannot confirm this.

Please check if you entered a space at the beginning of your output file name pattern.

**Comment by Osny95** [comment]
Ok. Thank you for your reply.  Effectively the issue was on my side.

**Comment by Osny95** [comment]
Ok. Thank you for your reply. Soory, effectively the issue was on my side.

**Comment by Osny95** [comment]
Ok. Thank you for your reply. Sorry, effectively the issue was on my side.
