### ISSUE TITLE
Support for AppleLossless *m4a

### ISSUE THREAD

**Issue by AjFax** [enzo1982/freac#124]
Hello, would be very very good if fre:ac could support *.m4a files. It's a container format containing two types of audio files:
- lossy as AACplus
- lossless as Apple Lossless 
the later often compared to .aiff (plain/raw audio for workstations).

**Comment by enzo1982** [comment]
fre:ac already supports Apple Lossless (ALAC). Depending on your system, fre:ac will offer either a dedicated Apple Lossless Encoder or the Core Audio AAC/ALAC Encoder. Both can output Apple Lossless .m4a files.

**Comment by AjFax** [comment]
Hi there,

 

I’m using mainly the windows version. It didn’t work when using .m4a/AL as a source file.

 

Von: Robert Kausch <notifications@github.com> 
Gesendet: Dienstag, 23. Juni 2020 22:21
An: enzo1982/freac <freac@noreply.github.com>
Cc: AjFax <ajfax@hispeed.ch>; Author <author@noreply.github.com>
Betreff: Re: [enzo1982/freac] Support for AppleLossless *m4a (#124)

 

fre:ac already supports Apple Lossless (ALAC). Depending on your system, fre:ac will offer either a dedicated Apple Lossless Encoder or the Core Audio AAC/ALAC Encoder. Both can output Apple Lossless .m4a files.

**Comment by enzo1982** [comment]
Are you using the latest 1.1.2a version of fre:ac? I just tested ALAC decoding support once again just to be sure and it looks like it's working just fine.

You can send the file you are trying to decode (or a link where I can download it) to support@freac.org if you would like me to investigate what's going on.

**Comment by enzo1982** [comment]
As I didn't hear back from you after my last post, I'm closing this ticket now. If there still is an issue, please add a comment here or contact support@freac.org.
