### ISSUE TITLE
"Custom cmdline only" option for LAME

### ISSUE THREAD

**Issue by Peppernrino** [enzo1982/freac#131]
**Is your feature request related to a problem? Please describe.**
The only problem is having to use another program to encode .wav to .mp3, due to the lack of granular control over LAME's cmdline options.

**Describe the solution you'd like**
A button to use "command-line only" LAME options, and the ability to manually change the LAME output text.

**Describe alternatives you've considered**
I've been using another fairly old app called RazorLame as a front-end for years now, as I've discovered LameXP has their own version of LAME cooked in as a .dll, and no way to alter the cmdline or use your own version of LAME.

**Comment by enzo1982** [comment]
fre:ac does not use the command line LAME interface. It use the DLL interface, thus there are no command line options being passed.

The LAME configuraton dialog in fre:ac makes a wide variety of modes and options available. What are you missing? I don't understand what you mean by _"change the LAME output text"_.

You can, however, use the command line LAME encoder with fre:ac, if you really want. Just copy your `lame.exe` to the `codecs/cmdline` subfolder of the fre:ac program folder and a _"LAME Command Line Encoder"_ will appear in fre:ac. This offers only the most basic options, but you can add your own by editing the `boca_encoder_lame.1.0.xml` file in the `boca` subfolder.

Alternatively, if you just want to use your own LAME, you can replace the `LAME.dll` in the codecs folder with e.g. one of the `libmp3lame.dll` files from Rarewares (rename to `LAME.dll` to allow fre:ac to find it).

**Comment by Peppernrino** [comment]
To clarify,  I'm actually talking about when I am using the LAME Command Line Encoder and the box I would like to manually change is the "Resulting arguments string:".

(Sorry if I dropped too many issues at once. I love the program, and have been sitting on these issues for a month or so... just had time to say everything today.)

**Comment by enzo1982** [comment]
OK, then the only option is editing the `boca_encoder_lame.1.0.xml` for now.

Letting the user specify additional arguments seems like a good idea, though, so I made a note to add this in one of the next releases.

**Comment by Peppernrino** [comment]
OK! I'm editing the `boca_encoder_lame.1.0.xml` file, and it's a lot of fun!

This probably will end up doing the trick for now. Very snazzy program. :1st_place_medal:

**Comment by Peppernrino** [comment]
In the case of Linux, what files would I move, and where? I recently switched over to UbuntuStudio. I have it installed as a snap, and I've found some familiar-looking files in `/snap/freac/current/usr/lib/`... am I getting warm?

**Comment by enzo1982** [comment]
fre:ac 1.1.3 now has a new option for external encoders, allowing to specify additional command line arguments.
