### ISSUE TITLE
CDRip Ripper Component still reads as v2.3

### ISSUE THREAD

**Issue by Peppernrino** [enzo1982/freac#132]
**Describe the bug**
In the release notes for 1.1.2, it's stated that the CDRip component was updated to v2.4, but it says CDRip Component is v2.3 when a CD is extracting audio, as well as in the logs.

**To Reproduce**
1. extract CD audio
2. observe "Decoder" window while extracting/inspect conversion log
3. log states: Decoder: CDRip Ripper Component v2.3

**Expected behavior**
I expected it to say v2.4.

**Screenshots**
![image](https://user-images.githubusercontent.com/18277943/87231166-fd808300-c371-11ea-9cb4-e0e754a653c0.png)
The picture is from version 1.1.2a, but it is still relevant in v1.1.2b.

**System (please complete the following information)**
 - OS: Windows 8.1
 - CPU: Ryzen 1600X
 - RAM: 16GB

**Comment by enzo1982** [comment]
My bad. I forgot to increment the version number reported by the GetCDRipVersion call when updating the library. The version shipped with fre:ac 1.1.2 is 2.4, despite the wrong display.

Also, the only change from 2.3 to 2.4 is fixing a crash that would occur on some systems when loading the library. In that case, the CD ripping features would not be available in fre:ac despite a CD drive possibly being present. If CD ripping is available to you in fre:ac, you are not affected by that bug.

**Comment by Peppernrino** [comment]
All good. I had a note about something like that in the additional comments... but I deleted it. lol

**Comment by enzo1982** [comment]
Fixed in fre:ac 1.1.3.
