### ISSUE TITLE
Ability to disable logging completely

### ISSUE THREAD

**Issue by Peppernrino** [enzo1982/freac#133]
**Is your feature request related to a problem? Please describe.**
Not really, just trying to score you some points with the surveillance-phobes.

**Describe the solution you'd like**
The auto-delete function is nice, but I wouldn't mind the option to disable all logging.

**Describe alternatives you've considered**
The only real options are to allow it to auto-delete the files or delete them manually. You CAN choose auto-delete after 0 days, and click OK and it will empty the log folder.

**Comment by enzo1982** [comment]
This is a bug, of course. Unchecking the "Archive log files" option should disable writing log files entirely.

Fixed in commit ffb01ff5.

**Comment by Peppernrino** [comment]
Excellent. Thank you for your all your work. :)

**Comment by enzo1982** [comment]
fre:ac 1.1.3 is out now with the fix.
