### ISSUE TITLE
Extract all tracks to same directory, regardless of data in Artist field

### ISSUE THREAD

**Issue by Peppernrino** [enzo1982/freac#134]
**Is your feature request related to a problem? Please describe.**
I extracted an audio CD, and it divided itself into many directories based on the addition of a featured artist. It also adds "WAV" to the end of the folder name.

**Describe the solution you'd like**
Copy all tracks to the same directory.

**Describe alternatives you've considered**
I have changed the artist names, and then add the featured artist back again in an mp3 tagging program. This is not ideal, due to forcing inconsistencies in submissions to the CDDB.

**Comment by enzo1982** [comment]
The naming of output folders and files depends entirely on the _"Output filename pattern"_ setting in the configuration dialog.

The default is `<albumartist> - <album>\<track> - <artist> - <title>`. Remove the `<albumartist> - <album>\` part or change it to `<album>\` only to get all files in the same folder. Or better yet, if you are dealing with a compilation with tracks from different artists, set the _Album artist_ to _Various Artists_ in the tag editor tab.

**Comment by Peppernrino** [comment]
It's not a VA CD, it's a hiphop CD. They often have featured artists on tracks. :P
Another possible option would be to add the featured artists to the trackname, but I feel that looks sloppy...

Just tested the same CD with `<album>\<track> - <artist> - <title>` and it all extracted to the same directory, but the "WAV" tag remains at the end of the foldername. Thank you!

**Comment by enzo1982** [comment]
The usual way to deal with such discs would be to put the main artist in the album artist field and keep the artist fields for the individual tracks as they are, i.e. main artist + feature artists.

If you see "WAV" at the end of the folder name, that might be part of the album field for the tracks. Please check that. You can edit the album field for all tracks belonging to an album at once using the tag editor in album mode (switch to the _Tags_ tab and choose the _Albums_ sub-tab).

Or you are using the _meh! multi encoder_ and checked the _"Create a separate folder for each output format"_ option in its configuration. In that case, a folder named after the output format will be created, containing the output files in that format.

**Comment by Peppernrino** [comment]
It seems the "WAV" indeed was a part of the album title in the CD Text. lol. Sorry about that! Everything else seems to be working fine now.
