### ISSUE TITLE
WMA encoder crashes via freeac v1.1.2b

### ISSUE THREAD

**Issue by JLGF1** [enzo1982/freac#136]
freeac crashes when encoding via Windows Media Audio Encoder [WMA].

Is that something _freac_ needs to know about?  Or out of bounds?  Obsolete?

**Comment by enzo1982** [comment]
WMA encoding works fine for me here. Can you provide more information?

I assume you're using Windows, as 1.1.2b is a hotfix version available only for Windows.

- What Windows version are you using?
- Do you use the 32 or 64 bit version of fre:ac?
- Do you use the Microsoft Store version or the regular one?
- What WMA settings do you use? Did you change anything from the defaults in the WMA configuration dialog?
- What other fre:ac settings are you using (esp. things like output to a single file or non-on-the-fly conversion might be important)? Are the crashes reproducible with the default settings?
- What's your input file type (MP3, M4A, WAV, etc.) and sample format (Mono/Stereo, Sample Rate, ...)?
- Did you try converting other input files?

**Comment by JLGF1** [comment]
OS ver: Win10 (see attached for recent build #)

WMA used: Win10 default installation (see attached)

freeAC encoder selected:  WMA, default settings (see attached)

Result: First output file-name is written (zero length) and then freeAC crashes.

Crash Reproducible?: Yes

**Comment by enzo1982** [comment]
Unfortunately, attachments are not getting through when replying to GitHub items by email.

Could you upload the screenshots directly on the GitHub issue page please?

**Comment by JLGF1** [comment]
![Freec-WMA-crash](https://user-images.githubusercontent.com/64571200/87721941-4460e500-c785-11ea-999a-bf45e2e7a454.JPG)
![Win10-Ver](https://user-images.githubusercontent.com/64571200/87721950-46c33f00-c785-11ea-9a6b-e9bc2581b97b.JPG)

**Comment by enzo1982** [comment]
Could you try again with the new fre:ac 1.1.3? It fixes a crash related to writing metadata that also affected WMA, so there's a chance that this issue is fixed.

**Comment by enzo1982** [comment]
Closing this as there was no response to my last comment. Please comment here if this is still an issue in recent versions of fre:ac.
