### ISSUE TITLE
Music output Dircetory

### ISSUE THREAD

**Issue by schfand** [enzo1982/freac#137]
Das Musik Ausgangs Verzeichnis wird bei der Auswahl, wenn ein nuer Ordner angegeben wird mit neuer Ordner und nicht mit dafür gewählten Namen ausgewählt.

The music output directory is selected when a new folder is specified with a new folder and not with the selected name.

**Comment by enzo1982** [comment]
Im Auswahldialog muss nach Eingabe des neuen Ordnernamens Enter gedrückt werden. Sonst wird der Ordner zwar angelegt, es wird aber dennoch "Neuer Ordner" an das Programm zurückgemeldet. Da es sich dabei um einen Windows-Systemdialog handelt, habe ich leider keine Möglichkeit, dieses Verhalten zu ändern.
