### ISSUE TITLE
Outputfolderfilenamestructure

### ISSUE THREAD

**Issue by jan-1923** [enzo1982/freac#140]
Hey, using this great piece of software more and more as it outrules all the others 
one thing i'm missing is that the freedb entries can't be turned into an outputfolder
structure automatically e.g. 
c:\BaseDirectoryGivenInSettings\New\AlbumArtist\Album\TracknumLead0-Track-Artist-Album.musicfile
...or i'm simply too dump to find the right button for that, what i hope you can excuse...

Keep the great work rolling !
5 Star program also without this feature

greetings

jan

**Comment by enzo1982** [comment]
Hi, that's possible actually. You can use slashes in the output _filename_ pattern to create sub-folders. To reproduce your example, try this pattern:

    <albumartist>\<album>\<track>-<title>-<artist>-<album>

See here for more info on output filename pattern options: https://freac.org/manual/en/howto.html#anchor_pat

**Comment by jan-1923** [comment]
RTFM... i knew it when pressing the submit button.
Sorry and thanks for punching my lazy nose into it!
Have a good one.

jan

**Comment by jan-1923** [comment]
gee, what a vast set of powerful parameters. safes quite some clicking! 
THX again !
