### ISSUE TITLE
Where do I put the codec files for custom command line options on Linux?

### ISSUE THREAD

**Issue by Peppernrino** [enzo1982/freac#142]
I recently switched over to UbuntuStudio. I have fre:ac installed as a Snap, and I've found some familiar-looking files in `/snap/freac/current/usr/lib/`... is this the codecs folder on Ubuntu?

To use "LAME Command Line Encoder" re: https://github.com/enzo1982/freac/issues/131, I mean... do I use the `libmp3lame.so` files, or is there somewhere to put the `lame` file from `/usr/local/bin`..? I am confused. :D

**Comment by enzo1982** [comment]
This is not possible with the Snap version. Snaps run in a sandbox and cannot access codecs outside the Snap package.

To use the command line LAME encoder with fre:ac on Linux, please use the AppImage version [available here](https://github.com/enzo1982/freac/releases/latest).

Unlike the Windows version, the AppImage does not come with the command line LAME support script. To use the encoder proceed as follows:

1. Download the [command line LAME support script](https://raw.githubusercontent.com/enzo1982/BoCA/master/scripts/boca_encoder_lame.1.0.xml)
2. Create a folder `.config/freac/boca` inside you home directory and move the LAME support script there
3. Install the LAME encoder via your package manager (on Ubuntu you can do `sudo apt install lame`)

After this, the fre:ac AppImage should detect and offer the LAME command line encoder.
