### ISSUE TITLE
Split file using Freac using cue generated by itself and into equal parts.

### ISSUE THREAD

**Issue by duytrung** [enzo1982/freac#149]
**Is your feature request related to a problem? Please describe.**
I convert and merge some file to one large file using freac (Encode into a single file). However, the file is too big > 4Gb and now I need to split into smaller files using the cue generated by Freac itself.

**Describe the solution you'd like**
Split the big file to tracks using cue file.
Split a big file into equal parts (such as 4Gb into 4 files of 1Gb).

**Describe alternatives you've considered**

**Additional context**

Thank you

**Comment by enzo1982** [comment]
It's not possible to automate this with the current version of fre:ac, but I have plans to add a splitting tool in a future version.

The plan is to allow splitting the output either into a fixed number of parts or alternatively into a variable number of parts each with a fixed length. It will be possible to restrict the split points to track boundaries as read from a cue sheet or chapter tags.

I'll leave this feature request open until that tool is available.

**Comment by duytrung** [comment]
Thanks @enzo1982

**Comment by enzo1982** [comment]
The output splitting feature is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7).

To access it, load files/tracks into the joblist, then select _Encode->Output splitting tool..._ from the menu or click the new toolbar button to the left of the _Start encoding_ button.

Closing this issue.

**Comment by hawkiboy** [comment]
This tool doesn't work as I would expect. I load a .cue and can instantly see all the individual track in freac. I have not found any settings that will split them into individual files. Any idea how to do it?

**Comment by demosthenez** [comment]
> This tool doesn't work as I would expect. I load a .cue and can instantly see all the individual track in freac. I have not found any settings that will split them into individual files. Any idea how to do it?

It either crashes or closes for me.  Maybe it's an operating system version situation or something.  Windows 11?
