### ISSUE TITLE
Channel converter: Mono file bigger than stereo?!

### ISSUE THREAD

**Issue by PhoenixIV** [enzo1982/freac#157]
I have source material in stereo, lossless. I even checked the audio graphs to make sure the channels differ.

For testing I converted it to
- opus mono 32 bit VBR (channel converter activated)
- opus mono 32 bit
- opus stereo 32 bit VBR (channel converter disabled)
- opus stereo 32 bit

I was surprised to find the resulting VBR mono file bigger than the stereo one. With fixed bitrates mono and stereo are exactly the same size.

Do you have any idea why this might happen?

**Comment by enzo1982** [comment]
When using VBR mode with a set target bitrate, the codec will try to reach that target. The actually achieved bitrate will vary slightly around that target. Sometimes it will be a bit lower, sometimes a bit higher.

So if you set a bitrate targer, it doesn't matter whether the source is Mono or Stereo, the result will be approximately the same file size in both cases. However, when there is less data to encode (Mono), the average quality achieved at the same bitrate will be higher than with more data to encode (Stereo). So in your case, when encoding in Stereo at 32 kbps, you will get a lower quality result than at the same bitrate in Mono.

So it's not surprising at all that the file size of the Mono file is sometimes bigger than a Stereo file at the same bitrate. On average, the files should be approximately the same size. For some songs one will be bigger and for others the other, but all within a margin of a few kB.

**Comment by PhoenixIV** [comment]
Thanks! I was not aware that the bitrate is a total thing, instead of per-stream.
You made me smarter.
