### ISSUE TITLE
Freac 1.1.3 Win installer Panda virus alert and installer permission

### ISSUE THREAD

**Issue by daninsky1** [enzo1982/freac#159]
Panda Security just say virus and no more details. I think that has to be something to do with adm permition, but either way it can be alarming. I didn't have this issue with older versions.
![Captura de tela 2020-10-11 212705](https://user-images.githubusercontent.com/4410465/95694487-b0c67580-0c08-11eb-8a83-04f835565e79.png)
![Captura de tela 2020-10-11 212604](https://user-images.githubusercontent.com/4410465/95694488-b15f0c00-0c08-11eb-8433-063501b1b8bb.png)

**Comment by enzo1982** [comment]
Unfortunately it happens from time to time that AV products produce false positives and flag software like fre:ac. This happened more regularly before the installer was digitally signed, but apparently is not completely ruled out even with the signature in place.

According to VirusTotal, the file is clean: https://www.virustotal.com/gui/file/efc2b9d75ad708530f9ce7a5a92780a75ff2da9c71fcfd0f90162d37be209f51/detection

Also not flagged by Panda Antivirus. Please make sure you have the latest updates. If you are using heuristic threat detection, false positives are more likely. Many AV products have a sensitivity setting for their heuristic scanners. It's generally a good idea to not set it to the most sensitive level.

**Comment by daninsky1** [comment]
Thank You.
