### ISSUE TITLE
[regression] garbage in GUI

### ISSUE THREAD

**Issue by axredneck** [enzo1982/freac#160]
**Describe the bug**
1.1.3 doesn't draw GUI properly while 1.1.2 does

**To Reproduce**
1. Download 1.1.3 appimage or flatpak
2. Run it

**Expected behavior**
Proper GUI

**Screenshots**
![Screenshot_20201012_221151](https://user-images.githubusercontent.com/20617900/95782703-feaaae80-0cd8-11eb-800f-a8ea838df09d.png)
![Screenshot_20201012_221207](https://user-images.githubusercontent.com/20617900/95782708-ff434500-0cd8-11eb-98da-b847ad480cda.png)

**System (please complete the following information)**
 - OS: Arch Linux
 - CPU: Ryzen 5 2600
 - RAM: 16 GB

**Comment by enzo1982** [comment]
Thank you for reporting this!

It's working fine here on Ubuntu. I'll have to set up an Arch VM to try and reproduce this.

**Comment by enzo1982** [comment]
I can reproduce this on Manjaro. Will investigate.

**Comment by Andrew5719** [comment]
At KUBUNTU 20.04, it's the same .....?

**Comment by enzo1982** [comment]
> At KUBUNTU 20.04, it's the same .....?

Yes, I can confirm. It appears to happen on KDE only - probably related to the window manager. I'll probably have a fix for this ready this evening.

**Comment by enzo1982** [comment]
This is fixed now via enzo1982/smooth@0db8f929. The AppImage, Flatpak and Snap releases have been updated.

**Comment by Andrew5719** [comment]
Thanks, Works OK.
