### ISSUE TITLE
Adding AUDIO DVD fails to load the disk

### ISSUE THREAD

**Issue by jimasun** [enzo1982/freac#161]
While it works on opening and converting audio CDs that are written on CDs, it cannot open (and therefor cannot convert) audio CD that are written on DVDs.

Win10, i5, 8G

**Comment by enzo1982** [comment]
I'm not sure what you mean by _"Audio CDs that are written on DVDs"_.

There is [DVD-Audio](https://en.wikipedia.org/wiki/DVD-Audio), a dedicated DVD format for audio, but completely different from audio CDs. I have vague plans to add support for DVD-Audio at some point, but as the format is rather niche, it's not a high priority for me.

Other than that, I can only think of audio files burned to a DVD. You should be able to open such files using the _Open file_ functionality in fre:ac. You will not be able to do this using the _Add audio CD contents_ button, as it is in fact not an audio CD.

So in any case, this is not a bug. If you mean DVD-Audio, this might be a feature request, but I'll wait for your confirmation of what format you actually mean.

**Comment by enzo1982** [comment]
Closing this as there was no response to my previous comment.
