### ISSUE TITLE
Merging files into MP4, Create a chapter for each file merged, at the beginning of each merged file.

### ISSUE THREAD

**Issue by L0garithmic** [enzo1982/freac#163]
Looking to merge a bunch of MP3 audiobooks, each has lots of individual files. I would like to merge all the files into one and have each individual file be its own chapter. They seem to save INSIDE the file, since when I stick the individual M4A into FreAc it shows them, but players like VLC, do not see them.

I am currently using NeroAAC but I don't think that makes a difference when tagging.

**Comment by enzo1982** [comment]
Just checked with Nero AAC and found that VLC and foobar2000 do not see chapters created by fre:ac in QuickTime format when using that encoder.

They see the chapters when a different encoder is used, though, which is strange as the tagging mechanism is the same, independent of the encoder used.

Other software like iTunes sees the chapters just fine by the way.

To work around the issue with VLC, go to the fre:ac configuration dialog, navigate to _Components->Taggers->MP4 Tagger_ and set the _Chapter format_ option to **_both_**.

**Comment by enzo1982** [comment]
I had a look at the internal structure of a file created with Nero AAC. It appears that Nero AAC writes an empty chapter list in its own Nero format to the output files.

fre:ac - when set to write chapters in QuickTime format - does that, but does not remove the empty chapter list in the other format. Apparently, VLC and foobar2000 then see the empty Nero chapter list and use that, assuming no chapters. iTunes on the other hand never supported Nero chapters and displays the QuickTime chapters written by fre:ac.

Now when fre:ac is configured to write both chapter formats, it will of course replace the empty Nero chapter list, making the issue go away.

I think I can fix that for the next release. Will give it a try in the next few days.

**Comment by L0garithmic** [comment]
I had JUST figured that out and was here to comment! Thanks for the super fast response! Thanks for looking into it too!

**Comment by L0garithmic** [comment]
So, it seems a LOT of my files chapters DO work,. But some... Don't. I have NO idea whats up.. But I will just check through them, find the ones that do not and, re-encode. So weird.

**Comment by enzo1982** [comment]
Closing this as the chapter issue was fixed in fre:ac 1.1.4 already.
