### ISSUE TITLE
Re-encoding multiple files with chapters. Want each file individually but not multiple chapter files

### ISSUE THREAD

**Issue by L0garithmic** [enzo1982/freac#164]
So. I got 3 audio books.

Book 1
Book 2
Book 3

each book has 3 chapters (exemple). So they appear like this in FreAc
Chapter1
Chapter2
Chapter3
Chapter1
Chapter2
Chapter3
Chapter1
Chapter2
Chapter3

Now, I want to re-encode these 3 books because I want to change something. Say a bitrate or a tagging option (Tagging in this case). However, when re-encoding them, it wants to encode them to 9 individual files. If I select encode to a single file, it will encode them to 1 file.

Is there a middle ground? Encode each file to an individual file?

**Comment by enzo1982** [comment]
That's not really possible in fre:ac right now - at least not without losing the chapter information.

However, there are two ways to possible improve your workflow around this:

1. After starting a conversion, you don't have to wait for it to finish. You can clear the joblist, load a different audio book and start editing it immediately. Any already running conversion will be unaffected by this.
2. You could use the check marks in front of the joblist entries. E.g. uncheck them all after loading your audio books to the joblist, then make your edits and finally enqueue each book conversion by checking the chapters belonging to the respective book and starting the conversion. As with 1. you don't have to wait for one conversion to finish before starting the next one.

So while not fully automated solutions, maybe these will help you speed up your workflow.

**Comment by enzo1982** [comment]
That's not really possible in fre:ac right now - at least not without losing the chapter information.

However, there are two ways to possible improve your workflow around this:

    After starting a conversion, you don't have to wait for it to finish. You can clear the joblist, load a different audio book and start editing it immediately. Any already running conversion will be unaffected by this.
    You could use the check marks in front of the joblist entries. E.g. uncheck them all after loading your audio books to the joblist, then make your edits and finally enqueue each book conversion by checking the chapters belonging to the respective book and starting the conversion. As with 1. you don't have to wait for one conversion to finish before starting the next one.

So while not fully automated solutions, maybe these will help you speed up your workflow.

**Comment by L0garithmic** [comment]
Yeah, Those are great suggestions. I honestly, just open up 20 copies of FreAc lol and run them so I can watch. But thanks for those ideas, I did not know about number 1 and had not thought about number 2. Just a suggestion for future editions maybe. Thanks!

**Comment by enzo1982** [comment]
Well, at first I thought this might be a bit difficult to integrate into fre:ac without making the UI more complicated. After thinking about it for a while, though, I think I might have found a way.

I plan to add an output splitting tool in an upcoming release (probably two or three releases from now). Up to now, the plan was to allow splitting the output by duration (e.g. split into parts not longer than 20 minutes) or into a given number of parts (e.g. split the whole thing into 6 equal parts). I think I can add a _split-by-metadata_ mode, so you could specify e.g. _split by original filename_ and have your three audio books come back out with chapters.

We can leave this ticket open and I'll update it once that tool is ready.

**Comment by divine-comedy** [comment]
1. is a good tipp. Didn´t no that.

Used an old version; not sure, if I solved the problem with mixed single- and multiple-chapter input-files a long time ago.
Now I updated and the problem surfaced (maybe) again.
Other settings were kept.

After a long search this works just fine for my podcast-needs: uncheck the tickbox "Read chapters from files".

![no_chapter_split](https://user-images.githubusercontent.com/74658132/99527748-37533d00-2995-11eb-9155-7a42856448f1.png)

**Comment by enzo1982** [comment]
The output splitting feature is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7).

To access it, load files/tracks into the joblist, then select _Encode->Output splitting tool..._ from the menu or click the new toolbar button to the left of the _Start encoding_ button.

Closing this issue.
