### ISSUE TITLE
Compilation under Linux is not possible

### ISSUE THREAD

**Issue by schfand** [enzo1982/freac#167]
SMOOTH 0.9.6, boca 1.0.2
Error message:
make
mkdir -p bin objects
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/cddb/cddb.cpp -o objects/cddb.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/cddb/cddbbatch.cpp -o objects/cddbbatch.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/cddb/cddbcache.cpp -o objects/cddbcache.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/cddb/cddbinfo.cpp -o objects/cddbinfo.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/cddb/cddblocal.cpp -o objects/cddblocal.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/cddb/cddbremote.cpp -o objects/cddbremote.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/cddb/extsettings.cpp -o objects/cddb_extsettings.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/cddb/manage.cpp -o objects/cddb_manage.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/cddb/managequeries.cpp -o objects/cddb_managequeries.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/cddb/managesubmits.cpp -o objects/cddb_managesubmits.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/cddb/multimatch.cpp -o objects/cddb_multimatch.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/cddb/query.cpp -o objects/cddb_query.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/cddb/submit.cpp -o objects/cddb_submit.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config.cpp -o objects/dialog_config.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_cddb.cpp -o objects/config_cddb.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_dsp.cpp -o objects/config_dsp.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_encoders.cpp -o objects/config_encoders.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_interface.cpp -o objects/config_interface.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_language.cpp -o objects/config_language.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_playlists.cpp -o objects/config_playlists.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_resources.cpp -o objects/config_resources.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_tags.cpp -o objects/config_tags.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/config_verification.cpp -o objects/config_verification.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/configcomponent.cpp -o objects/configcomponent.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/config/configentry.cpp -o objects/configentry.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/adddirectory.cpp -o objects/adddirectory.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/addpattern.cpp -o objects/addpattern.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/charset.cpp -o objects/charset.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/error.cpp -o objects/error.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/format.cpp -o objects/format.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/dialogs/overwrite.cpp -o objects/overwrite.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/engine/component.cpp -o objects/engine_component.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/engine/converter.cpp -o objects/engine_converter.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/engine/decoder.cpp -o objects/engine_decoder.o
g++ -I"/home/frank/freac/freac-1.1.3"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/local/include  src/engine/encoder.cpp -o objects/engine_encoder.o
src/engine/encoder.cpp: In member function ‘smooth::Bool freac::Encoder::Create(const smooth::String&, const smooth::String&, const BoCA::Track&)’:
src/engine/encoder.cpp:110:2: error: ‘AdjustTrackSampleCounts’ was not declared in this scope
  110 |  AdjustTrackSampleCounts(album, targetFormat);
      |  ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:317: objects/engine_encoder.o] Fehler 1

**Comment by enzo1982** [comment]
You need BoCA 1.0.3 to compile fre:ac 1.1.3.

Also, in case you are running KDE, you'll need to include enzo1982/smooth@0db8f929 in your build to avoid drawing issues.

**Comment by enzo1982** [comment]
These issues are sorted out with the new releases:

- smooth 0.9.7
- BoCA 1.0.4
- fre:ac 1.1.4

Closing this.
