### ISSUE TITLE
The ability to disregard chapter data when inputting M4A files.

### ISSUE THREAD

**Issue by L0garithmic** [enzo1982/freac#169]
Request: The ability to disregard chapter data when inputting M4A files.

Example:
Using Fre:Ac v1.1.3, I had a large audio-book. In total 250 mp3 files, split into chapters, each chapter containing about 7 mp3 files. Knowing that Fre:Ac turns each file into a chapter, I attempted to merge each chapter (7 files) into 1 so instead of 250 chapters, I would have 36. However, Fre:Ac reads the chapters in each of the merged files, which is awesome... and terrible lol

So after all the work of reducing the files, it ended up having 250 chapters anyways. Which brings me to the request. 

The ability to uncheck a box or click a button, so that Fre:Ac disregards any chapter data previously embedded in the M4A files would be a handy feature.

**Comment by L0garithmic** [comment]
I have managed to remove the chapters using ffmpeg, not the greatest but works for now. (Windows .bat file)
`mkdir nochap & for %%f in (*.m4a) do (ffmpeg -i "%%f" -map_chapters -1 -c:v copy -c:a copy "nochap\%%~nf.m4b")`

**Comment by enzo1982** [comment]
You can control the chapter behavior in the configuration dialog under _Tags->Other_:

- Disabling the _"Read chapters from files"_ option makes fre:ac disregard chapters when adding files to the joblist, i.e. each file will appear as only one track.
- Disabling the _"Write chapters to files"_ option will suppress chapters when writing output files.

**Comment by L0garithmic** [comment]
Well, look at that... There it is. Facepalm. Just burred way under stuff. Sorry about the hassle!

**Comment by enzo1982** [comment]
No worries. I know there's so many options that some things can be difficult to find at times.
