### ISSUE TITLE
Freac Audio v1.1.3 DOes rip after 10 successful rips

### ISSUE THREAD

**Issue by majordude** [enzo1982/freac#170]
FREAC cant create output file. Not sure why. I un installed app and reinstalled and it still doesnt werite output file.  Is there a config I should check.  My audio cdroms are older, but I did successfully rip about 10 music cds which performed great, then suddenly stopped.  I made no changes to anything that I am aware.  Just upset I cant use this app.  Its a great app until now

![image](https://user-images.githubusercontent.com/30181216/99432096-af5c2d00-28d9-11eb-95bb-7f66244131a2.png)

**Comment by enzo1982** [comment]
Hi Ed, you already asked this by email and I answered you on Sunday. Didn't you get my reply?

I suggested this might have to do with Windows 10's controlled folder access feature which prevents applications from writing to your user profile/personal files folders.

However, I didn't notice that your output folder is set to `E:\`. Is E: your CD drive? If so, you need to set the output folder to a location on your hard disk. fre:ac will not be able to write to CD drives.

**Comment by enzo1982** [comment]
Closing this as I didn't hear back. See previous comment for possible causes/solutions.
