### ISSUE TITLE
Improve CPU Detection (in Linux only?)

### ISSUE THREAD

**Issue by Peppernrino** [enzo1982/freac#173]
Minor issue.

I ripped a CD in v1.1.3 and checked the log, and I saw:

**System:  Ubuntu 20.04.1 LTS (Linux 5.4.0-54-lowlatency)
CPU:     unidentified 6 core (12 threads) x86-64 CPU
RAM:     16 GB**

I am running a Ryzen 1600X cpu. Is there anything to help detection of cpu instead of generic readout? Is it an Ubuntu problem?

**Comment by enzo1982** [comment]
fre:ac uses [libcpuid](https://github.com/anrieff/libcpuid) to detect the CPU type. I just updated the library, so maybe try and see if the latest fre:ac continuous build fixes the issue.

If you're using the Flatpak or Snap version of fre:ac, it's possible that the sandbox denies access to CPUID data (not sure about that). So please try the continuous AppImage build instead.

I'll probably get a Ryzen system in December or January, so if the CPU is still not detected with the libcpuid update, I might be able to reproduce this then.

**Comment by Peppernrino** [comment]
I have actually been using thre AppImage since my last issues with where to put custom cmdline stuff. :)

**Comment by enzo1982** [comment]
This issue is now fixed in the continuous builds.

It actually was related to the initialization order for static data on Linux systems and was found coincidentally by running fre:ac with the compiler's undefined behavior sanitizer enabled.

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.5 is now available with the fix.
