### ISSUE TITLE
Corrupt Audio File when convert to opus

### ISSUE THREAD

**Issue by Olli0073** [enzo1982/freac#174]
When I convert multiple audio files in one file with opus codec and a total playtime over 12 hours the encoded file is corrupt.

Under 12 hours the files are fine.
fre:ac V1.1.3b Apple M1

**Comment by enzo1982** [comment]
This is a duplicate of #162. The fix will be in fre:ac 1.1.4.

If you need a fixed version now, let me know and I will provide a macOS build here.

**Comment by Olli0073** [comment]
That sounds great.  Please provide the macOS  build here.

**Comment by enzo1982** [comment]
Alright, I put a build at https://freac.org/updates/freac-1.1.3-20201201-macos11.dmg

**Comment by Olli0073** [comment]
It works. Thank you.

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.4 is now released.
