### ISSUE TITLE
Crashes after 4 - 5 encodings

### ISSUE THREAD

**Issue by Olli0073** [enzo1982/freac#175]
Program crashes after 4 -5 encodings.

Apple M1 
Fre:ac V1.1.3b

**Comment by enzo1982** [comment]
Any specific input or output formats? Or does it crash independent of the formats? Does it crash when doing the same conversion 4-5 times (i.e. same input files and settings)?

I did some tests on Apple Silicon before releasing 1.1.3b and did not detect any obvious crashing issues.

**Comment by Olli0073** [comment]
I will do some further tests.

**Comment by enzo1982** [comment]
FWIW, fre:ac 1.1.5 comes with some further stability fixes (not specific to Apple Silicon). If you're still around here, please check if this is still an issue with the latest version. Otherwise, I will close this soon.
