### ISSUE TITLE
FREE AUDIO CONVERTER

### ISSUE THREAD

**Issue by jagman55** [enzo1982/freac#177]
I need to convert some BIN files to FLAC or MP3 files.   The "Converter" asks for a FOLDER to search in for the input files. Mine are mixed suffixes but I want to do only the BIN files. But the Converter display does not LIST THE FILES SUFFIXES BUT IT SHOULD SO WE CAN CONVERT BY SUFFIXES. Does it seem the suffix of a file would be need in a conversion?

**Comment by enzo1982** [comment]
You can enable the _File type_ joblist column in the configuration dialog under _Interface->Joblist_.

However, .bin is not an audio file format extension it's usually a CD image. fre:ac will most probably not be able to read those files.

To extract audio tracks from .bin files, you'll need to mount the files in a virtual CD drive (usually using an accompanying .cue file). Then use the CD ripping function of fre:ac to access the tracks on your virtual drive.

**Comment by jagman55** [comment]
What a "pain". I joined YOUTUBE, pay monthly to download..  and get to download lots of Youtube and all audioa are  in ,BIN format. Wonder what they expect us to do because the Member fees are for downloading.

**Comment by enzo1982** [comment]
Well, actually I don't even know if your .bin files are the same format as the CUE/BIN files I was referring to above. The CUE/BIN format originates from a software called CDRWin and is nowadays supported by CD tools like ImgBurn.

I'd be surprised if YouTube used that format for anything. So maybe their .bin is something completely different. .bin usually just stands for _binary_ after all, so it can actually be anything.

**Comment by enzo1982** [comment]
Closing this as this is about an unknown file format and it's unclear if it is even an audio format.
