### ISSUE TITLE
Hello, author. I really like this software. I hope you can add a custom background music plug-in or insert a start and end audio plug-in.

### ISSUE THREAD

**Issue by li19890922** [enzo1982/freac#178]
Hello, author. I really like this software. I hope you can add a custom background music plug-in or insert a start and end audio plug-in.

**Comment by enzo1982** [comment]
Thank you for your suggestion!

As fre:ac is mainly a converter, however, I think it would not be the right place for such features. You can easily edit audio files in Audacity to add custom intros/outros and background music. Audacity and fre:ac can be used together really well for such use cases.
