### ISSUE TITLE
Not scaling on Linux HiDPI screen

### ISSUE THREAD

**Issue by forrcaho** [enzo1982/freac#18]
I just built freac on Debian unstable and the windows are not scaling properly; they appear tiny on my HiDPI screen. My desktop environment is MATE, and I have not had problems with other GTK3 apps not scaling.

I tried setting the scaling with dconf-editor to force it to 2 (instead of autodetect, which has worked for everything else) and I also tried setting the GDK_SCALE env var to 2, but neither of these approaches worked.

**Comment by enzo1982** [comment]
fre:ac does not evaluate the GTK configuration or GDK_SCALE variable yet. But you can run it in scaled mode, by passing the `--scale` argument to the program: `freac --scale:2.0`

I will add support for autodetecting the scale factor in a future release.

**Comment by forrcaho** [comment]
That works. Thanks.

**Comment by enzo1982** [comment]
Commit enzo1982/smooth@e4725c2 adds evaluation of the GDK_SCALE setting, so the `--scale:n.n` option should no longer be necessary (however, it allows fractional scaling, so you might want to continue using it instead of GDK_SCALE).

**Comment by forrcaho** [comment]
I've confirmed this works. I was hoping this was the mechanism by which autoscaling was implemented and so that would work too, but unfortunately that doesn't appear to be the case.

**Comment by agorodezki** [comment]
If i start freac-1.1-alpha-20180913 without the --scale:n.n option, it will appear unusable tiny. I'm working on elmentary os 5.0 (it's based on ubuntu 18.04). Setting the GDK_SCALE Variable won't have any affect. freac-1.1-alpha-20180716 doesn't have this issue.

**Comment by enzo1982** [comment]
@agorodezki: The alpha release you are using is from September 13th. The changes discussed here have been implemented on October 20th.

There will be a new release soon that will incorporate these changes and work with GDK_SCALE.

**Comment by enzo1982** [comment]
Closing this as the December alpha release now evaluates the GDK_SCALE variable.

Nevertheless, scaling on Linux systems will have to be revisited and improved in the future. At this time, HiDPI support in Linux desktop environments is a mess though.

Once there is something like an XDG standard that allows for fractional scale factors and different settings per monitor, we can consider implementing it.
