### ISSUE TITLE
Tags->CoverArt->WriteToFile setting does not honor Encoder->UserInputFolder setting

### ISSUE THREAD

**Issue by ryanlath** [enzo1982/freac#187]
**Describe the bug**
Tags "Cover Art" writing to files setting, doesn't honor Encoder setting of "User input folder."  Using the settings below, mp3s end up in the "User input folder."  Cover art ends up in default output folder. e.g.
```
<INPUT_FILES>\<albumartist>\<album>\<CONVERTED_FILES>
<DEFAULT_OUTPUT_FOLDER\<albumartist>\<album>\<COVERART_FILES>
```

**To Reproduce**
General Settings:
```
Encoders->LAME[snip]->Output folder->[x]User input  folder if possible
Encoders->LAME[snip]->Output filenames->Filename patterns: <albumartist>\<album>\<track> - <title>
Tags->Cover art[X]Write cover art to files
Tags->Cover art[X]Write cover art to files->Filename patterns: <albumartist>\<album>\<type>
```

**Expected behavior**
Cover art would end up in the same folder of encoded files.

**System**
 - OS: [Windows 7]
 - Fre:ac [1.1.3]

**Comment by enzo1982** [comment]
Thank you for reporting this!

This is now fixed in the source code. The fix will be reflected in the continuous builds shortly.

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.5 is now available with the fix.
