### ISSUE TITLE
[linux] It takes too long for fre:ac to start

### ISSUE THREAD

**Issue by axredneck** [enzo1982/freac#188]
(It's both a bug report and feature request)

**Describe the bug**
It starts Wine and creates/updates a prefix even if i don't have/use Apple AAC encoder (i don't even know how to install it properly)

**To Reproduce**
1. Install/update Wine.
2. Start fre:ac
3. Waaaaait...

**Expected behavior**
A couple of seconds between double-clicking freac.appimage and it's window appearing instead of half a minute

**System (please complete the following information)**
 - OS: Arch Linux

**Additional context**
Maybe add some kind of "Search for Apple AAC encoder at startup (may take some time)" checkbox to Options window?

**Comment by enzo1982** [comment]
Well, this happens only if Wine is installed/updated and then fre:ac is started without any other application using Wine inbetween.

I don't really like the idea of adding an option for this to the UI. Would a command line option a la `--disable-coreaudio` help?

**Comment by axredneck** [comment]
> Would a command line option a la --disable-coreaudio help?

Would be good too.

**Comment by enzo1982** [comment]
Alright, the patch is pushed now. A new continuous build should be available in ~20 min.

I actually called the option `--disable-wine`. If you have a desktop entry for fre:ac to show up in your application launcher, you should be able to add the option there and be done with it.

**Comment by axredneck** [comment]
> Alright, the patch is pushed now.

The only patch i see is "Update Readme to note a previously unmentioned fix"

**Comment by enzo1982** [comment]
It's in the Core Audio component: enzo1982/BoCA@8a8734512b3214614bf2a7f4567975b525ed5ebd

**Comment by axredneck** [comment]
Thank You!
