### ISSUE TITLE
Folder for Artist/Album

### ISSUE THREAD

**Issue by lotte67890** [enzo1982/freac#189]
Maybe I´m just to stupid, I want my files like `<artist>/<album>/<track> <title>` . Funny thing is that the folder artist is created correctly, but the inside folder which should have the album name is named "unknown album". When I choose `<artist> - <album>/<track> <title>` the part of the album name is correct.

**Comment by enzo1982** [comment]
Unfortunately, your post got messed up a bit here. I guess you want your files to be named like `<artist>/<album>/<track> <title>`. That is the correct format for this.

You get _unknown album_ in the album part only when the album field for a track is empty. So I guess the issue has nothing to do with the filename pattern, but you had a track with an empty album field when you tried your desired pattern.

Please try again, but make sure you enter something in the album field for the track you are testing with.

**Comment by lotte67890** [comment]
So, everything is fine, it works as you suggested, don´t know why it didn´t yesterday... I was unsure if album folder in artist folder is supported cause it didn´t work in the first place, while without restarting the sw the name of the album was included when having `<artist> - <album>/<track> <title>`.
Thanks for your help!
