### ISSUE TITLE
freaccmd (freac-1.1-alpha-20180913-linux-x64) cannot handle files with space in filename or patterns

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#19]
Hi there, 

i am currently setting up a batch conversion system for converting FLAC encoded files to mp3 with freaccmd.

It seems as if freaccmd has a problem with spaces in filenames, or how bash expansion works.

Example: 
freac-1.1-alpha-20180913-linux-x64 $ ./freaccmd -d /Volumes/Musik/__INCOMING__/_RIPPED_/ -p 'MP3/<albumartist>/<album>/<disc><track>\ -\ <artist>\ -\ <title>' -m CBR -b 320 /Volumes/Musik/__INCOMING__/_RIPPED_/FLAC/Atreyu/In\ Our\ Wake/*
File not found: /Volumes/Musik/__INCOMING__/_RIPPED_/FLAC/Atreyu/In
File not found: Our
File not found: Wake/101
File not found: Atreyu
File not found: In
File not found: Our
File not found: Wake.flac
File not found: /Volumes/Musik/__INCOMING__/_RIPPED_/FLAC/Atreyu/In
File not found: Our
File not found: Wake/102
File not found: Atreyu
File not found: House
File not found: Of
File not found: Gold.flac
File not found: /Volumes/Musik/__INCOMING__/_RIPPED_/FLAC/Atreyu/In
File not found: Our
File not found: Wake/103
File not found: Atreyu
File not found: The
File not found: Time
File not found: Is
File not found: Now.flac
File not found: /Volumes/Musik/__INCOMING__/_RIPPED_/FLAC/Atreyu/In
File not found: Our
File not found: Wake/104
File not found: Atreyu
File not found: Nothing
File not found: Will
File not found: Ever
File not found: Change.flac
File not found: /Volumes/Musik/__INCOMING__/_RIPPED_/FLAC/Atreyu/In
File not found: Our
File not found: Wake/105
File not found: Atreyu
File not found: Blind
File not found: Deaf
File not found: &
File not found: Dumb.flac
.....

any idea how to solve this?

**Comment by enzo1982** [comment]
That's a bug in the arguments parser on non-Windows platforms. Sorry about that!

It's fixed in enzo1982/smooth@a463fa4.

I also attached a [fixed freaccmd binary](https://github.com/enzo1982/freac/files/2508328/freaccmd-argsfix-linux-x64.tar.gz) compatible with the 20180913 x64 Linux release.

**Comment by wkremser** [comment]
Well, the new binary now handles blanks but suddenly it does seem to have a problem with accessing or finding the files. The files exist in the current directory.

The script is a wrapper using the options of the first post.
$ ~/scripts/enc2mp3.sh *.flac
File not found: 101 - Atreyu - In Our Wake.flac
File not found: 102 - Atreyu - House Of Gold.flac
File not found: 103 - Atreyu - The Time Is Now.flac
File not found: 104 - Atreyu - Nothing Will Ever Change.flac
File not found: 105 - Atreyu - Blind Deaf & Dumb.flac
File not found: 106 - Atreyu - Terrified.flac
File not found: 107 - Atreyu - Safety Pin.flac
File not found: 108 - Atreyu - Into The Open.flac
File not found: 109 - Atreyu - Paper Castle.flac
File not found: 110 - Atreyu - No Control.flac
File not found: 111 - Atreyu - Anger Left Behind.flac
File not found: 112 - Atreyu - Super Hero.flac
File not found: 113 - Atreyu - Generation.flac
File not found: 114 - Atreyu - Straight To Hell.flac

**Comment by enzo1982** [comment]
It works for me with the fixed binary. Could it be a bug in your wrapper script?

Please try freaccmd without the wrapper. If it shows the same issue, please try if you can open the files in the GUI version.

**Comment by wkremser** [comment]
you were right .. my script was buggy, had a changedir in it, because of not finding the libraries.
changed it to expand the LD_LIBRARY_PATH and now it works.

Can be closed ;)
