### ISSUE TITLE
Genre tag box multiselect dropdown not functioning - Win10

### ISSUE THREAD

**Issue by tapfret** [enzo1982/freac#192]
**Describe the bug**
Just updated to 1.1.4 (x86). When changing the genre tag (or any tag for that matter) there is a small down arrow at the upper right corner that should appear with options to modify case, interpret string, and "use for all selected tracks".  Arrow appears when cursor is in the text field of these tags or directly over them. However in the genre tag box, it disappears when moving the cursor out of the box. Other fields like Artist Name, Album and Year do not appear to be effected. 

**To Reproduce**
1. Change the text in the genre selection box, free text or select from dropdown menu makes no difference  
2. Put the mouse cursor over the text.
3. Note the small arrow that appears over the larger field selection arrow to the right of the selection box.
4. Move the mouse cursor toward the small dropdown arrow.
5. Note the arrow disappears when the mouse cursor leaves the box at a distance of 23 character away from the left within the box.

**Expected behavior**
The modify case, interpret string, and "use for all selected tracks" dropdown arrow should remain when the cursor is anywhere over the genre selection box, but under the "Title" box. **Note: I was able to fool it by resizing the entire fre:ac window to its smallest possible width, which brings the arrow to within that 23 character field.  When restarted at its default size, or the window is resized larger, the behavior resumes. **

**Screenshots**
Screenshots attempted but do not display cursor location, so are of little value.

**System (please complete the following information)**
 - OS: Win10
 - CPU: Intel Core i7 3770
 - RAM: 32GB

**Additional context**

**Comment by enzo1982** [comment]
Thank you for reporting this!

I can confirm this behavior. It was introduced when making the title and genre resize with the window for fre:ac 1.1.4. This will be fixed in the next update.

As I'll be preparing an updated build for a different issue in the next few days anyway, I will link it here so you can get a fixed build early.

Please use the workaround of resizing the window to its smalles width in the meantime.

**Comment by enzo1982** [comment]
Continuous builds for Windows are now available. You can get a Windows build that already includes the fix at https://github.com/enzo1982/freac/releases/tag/continuous

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.5 is now available with the fix.
