### ISSUE TITLE
Add *.opus file, returns "Error: Unknown file type"

### ISSUE THREAD

**Issue by Blake-LeBlanc** [enzo1982/freac#193]
**Describe the bug**
Try to add *.opus file to job list, it fails with the error message, "Error: Unknown file type". 

**To Reproduce**
1. Attempt to add a *.opus files, either as individual files or as a directory
2. See error

**Expected behavior**
Populate job list with selected files

**Screenshots**
n/a

**System (please complete the following information)**
 - OS: Windows 10 x64 19042.804
 - CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
 - RAM: 16.0 GB

**Additional context**
Out of the ~150 or so *.opus files that I have, I think maybe ten of them went through okay. But the remainder did not. 

If you need any more information, please don't hesitate to ask!

Thank you again for such a great tool!

**Comment by enzo1982** [comment]
Thank you for reporting this!

I cannot reproduce this with any Opus files I have here, so I'll need one of the files that are failing to see what's going on.

You can either attach one here or, if that is not possible due to Copyright or other reasons, send it to support@freac.org.

**Comment by Blake-LeBlanc** [comment]
Sure! Here is an example of one that has a small file size:

[Pers Dev Willink, J Push Through.zip](https://github.com/enzo1982/freac/files/6004983/Pers.Dev.Willink.J.Push.Through.zip)

**Comment by enzo1982** [comment]
Thanks for the file!

That is actually a WebM file containing an Opus stream. The file extension should be changed to .webm and the the file can then be opened by fre:ac (through it's generic FFmpeg based input component).

The .opus extension is reserved for Opus streams in an Ogg container and should not be used for WebM files.

**Comment by Blake-LeBlanc** [comment]
> Thanks for the file!
> 
> That is actually a WebM file containing an Opus stream. The file extension should be changed to .webm and the the file can then be opened by fre:ac (through it's generic FFmpeg based input component).
> 
> The .opus extension is reserved for Opus streams in an Ogg container and should not be used for WebM files.

That did the trick! Thank you so much, Enzo!
