### ISSUE TITLE
Dither as part of resampling DSP

### ISSUE THREAD

**Issue by ghost** [enzo1982/freac#196]
It would be great to have TPDF dither (and perhaps some noise-shaped options) as part of the resampler DSP. Chris from airwindows has some truly excellent open-source options too including "Not-Just-Another-Dither" and "Dark" in both 16-bit and 24-bit variants.

**Comment by enzo1982** [comment]
[fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7) has been released and adds support for TPDF and RPDF dithering when converting to a lower sample resolution.

This is enabled for all automatically happening sample format conversions (e.g. after resampling) in fre:ac and TPDF dither is used by default.

Closing this issue.
