### ISSUE TITLE
Issues with iMac air

### ISSUE THREAD

**Issue by maton2912** [enzo1982/freac#199]
Even though I tagged Eject after ripping in the Automization section of settings, it doesn't respond on my iMac air nor does pressing the eject tag on the main screen

**Comment by enzo1982** [comment]
Thank you for reporting this!

I can confirm there is a bug that prevents disc eject from working on macOS. This will be fixed with the next update.

**Comment by maton2912** [comment]
Great thank you.
Regards
Kevin

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.5 is now available with the fix.

**Comment by maton2912** [comment]
Thanks Robert
