### ISSUE TITLE
feature request: make flatpack or snap binaries

### ISSUE THREAD

**Issue by smoser** [enzo1982/freac#2]
Hi,
I came upon fre:ac and thought i'd give it a try. I downloaded the pre-built tarball and extracted.  a 'ldd' showed I was missing several dependencies.

Solutions to this dependency issue are available in `snap` or `flatpack`.
Both flatpack and snap provide additional benefits from the security perspective.

Have you considered building either?  http://snapcraft.io has information on how to get started with snap, and https://flatpak.org/hello-world for flatpack.

**Comment by collectorgeneral** [comment]
Would also like to throw in AppImage as an alternative.

**Comment by enzo1982** [comment]
Creating packages is not a high priority for me as long as fre:ac 1.1 is still alpha. I plan to pursue this after the beta 1 and before the final fre:ac 1.1 release.

If someone else would like to help package fre:ac for Flatpak or Snap earlier, please go ahead. I guess this would be a good item for new contributors.

**Comment by enzo1982** [comment]
FWIW, I've started building a Flatpak package of the latest fre:ac alpha. It should be ready soon.

Will look at Snap next.

**Comment by enzo1982** [comment]
fre:ac is now [available on Flathub](https://flathub.org/apps/details/org.freac.freac)!

**Comment by probonopd** [comment]
@collectorgeneral 

> Would also like to throw in AppImage as an alternative.

We are working on it:
https://github.com/enzo1982/freac/pull/31

**Comment by enzo1982** [comment]
fre:ac is now [available as a Snap](https://snapcraft.io/freac) too.

I'll leave this ticket open as AppImage support has been requested as well. I will work on that now. Thanks to the work already done @probonopd, this should be available soon.

**Comment by collectorgeneral** [comment]
@probonopd Your work is much appreciated :). I prefer the AppImage format and making it available will be a huge help!

**Comment by enzo1982** [comment]
AppImages of the 20181201a release are now available [here](https://github.com/enzo1982/freac/releases).

I will now work on integrating @probonopd's PR for building continuously building AppImages for every commit.

**Comment by enzo1982** [comment]
Continuous AppImage builds are now available at https://github.com/enzo1982/freac/releases/tag/continuous.

The build infrastructure will also be used for upcoming releases.

Closing this ticket.
