### ISSUE TITLE
Error when editing track info from disc from 2 artists to one

### ISSUE THREAD

**Issue by forrcaho** [enzo1982/freac#20]
I have a CD I'm trying to rip: _High Plains Gospel_ by Dan Schwartz. The data is not in CDDB so it reads the track data correctly from the disc.
![freac01](https://user-images.githubusercontent.com/492742/47476095-5433db00-d7e4-11e8-9f8d-c47aa62a5ea6.png)

The disc attributes one of the songs to another artist (Bill Frisell), but that is actually the composer; the performer is Dan Schwartz, the same as the rest of the disc. So, on the joblist tab that is initially shown, I click on that track and edit the artist name, and this looks fine.
![freac02](https://user-images.githubusercontent.com/492742/47476096-5433db00-d7e4-11e8-9302-2daba2275270.png)

I want to set some tags that apply to the entire album, so i go to the "Tags" tab, and under that to "Albums". Here I see a list of two albums: _High Plains Gospel_ by Dan Schwartz as I am expecting, and _High Plains Gospel_ by "B" (no doubt some vestigial remnant of "Bill Frisell").
![freac03](https://user-images.githubusercontent.com/492742/47476097-5433db00-d7e4-11e8-8b6d-a9c7621a2f1b.png)

I was able to select the correct entry from the list and edit it as I wanted, but the spurious entry is confusing.

**Comment by enzo1982** [comment]
Thank you for reporting this!

I can reproduce the issue. It was introduced this summer in an attempt to improve handling of album artist information. I will think about a better solution.

**Comment by enzo1982** [comment]
Should be fixed in commit c95ab9aecda3aa3eadb5c86b738985a2d75bf209.

**Comment by forrcaho** [comment]
Confirmed fixed!

**Comment by enzo1982** [comment]
The 20181201a release includes the fix. Please test and close.

**Comment by forrcaho** [comment]
Finally got the chance to test this with the tagged version. It's fixed, thanks. Closing.
