### ISSUE TITLE
how to generate a cue file if I want to merge tracks into one  by freaccmd?

### ISSUE THREAD

**Issue by ghGYR** [enzo1982/freac#201]

**Comment by enzo1982** [comment]
freaccmd does not support creating cue sheets or playlists yet.

I will consider adding this in a future update.

**Comment by ghGYR** [comment]
> freaccmd does not support creating cue sheets or playlists yet.
> 
> I will consider adding this in a future update.

well, hope !

**Comment by enzo1982** [comment]
Support for generating cue sheets and playlists is now available in fre:ac [continuous builds](https://github.com/enzo1982/freac/releases/tag/continuous).

Would be great if you could try this.

An official 1.1.6 release will be available in a few days.

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.6 is released now.
