### ISSUE TITLE
[MusicBrainz] How to configure to use MusicBrainz

### ISSUE THREAD

**Issue by cmarchand** [enzo1982/freac#204]
**Question**
Label `Question` is not available as typing...

I'm looking for config to use [MusicBrainz FreeDb Gateway](https://wiki.musicbrainz.org/History:FreeDB_Gateway).

I'm able to modify `~/.freac/freac.xml` if required.

Thanks in advance,
Christophe

**Comment by enzo1982** [comment]
Hi, the MusicBrainz project shut down the freedb gateway in 2019. That's mentioned on the site you linked.

As the gateway is no longer available, it's currently not possible to access MusicBrainz using fre:ac.

I'm working on adding MusicBrainz support, though. I expect this to be available in one of the next updates (i.e. not in the upcoming 1.1.5, but possibly in 1.1.6).

**Comment by cmarchand** [comment]
Ok. So, at this time, there is no way for getting disc info from any database ?

**Comment by enzo1982** [comment]
fre:ac uses the GnuDb database by default since version 1.1.3. That's working quite fine as a freedb replacement.

**Comment by cmarchand** [comment]
Nice ! As I had an old release of fre:ac, and changed this config may times, when I updated it, I didn't recover the gnudb config.

Now, it perfectly works ! Thanks a lot !

**Comment by enzo1982** [comment]
Great! Glad that it's working now!
