### ISSUE TITLE
Ogg Vorbis Encoder rejects quality values below -1

### ISSUE THREAD

**Issue by damian101** [enzo1982/freac#213]
**Describe the bug**
Ogg Vorbis Encoder rejects quality values below -1

**To Reproduce**
1. Select Ogg Vorbis Encoder
2. In the encoder settings set quality to any value below -1
3. Try encoding a file. I get error message "Could not set up encoder for output file: [...]"

**Expected behavior**
Encoder settings in the GUI should represent possible settings for the underlying encoder.

**System (please complete the following information)**
 - OS: RebornOS (Arch Linux)
 - CPU: 2x Intel Xeon E5-2667 v2
 - RAM: 384GB

**Comment by enzo1982** [comment]
Quality values below -1 are only supported with the aoTuV encoder. All official fre:ac packages (AppImage, Flatpak and Snap) use that encoder, but if you're using a different package or a custom build, you may be using the original Vorbis encoder.

I updated the Vorbis config dialog code to check which encoder is being used and offer the lower quality values only for aoTuV: enzo1982/BoCA@45bb798f

**Comment by damian101** [comment]
Oh, that's good to know. I thought there was only one Vorbis encoder.
I replaced libvorbis with libvorbis-aotuv-lancer on my system, now fre:ac uses the aoTuV encoder. And Handbrake too :)
I also did a quick comparison at quality 0.0 and 2.0 between the two encoders, and aoTuV definitely sounded better, at a slightly higher file size though.

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.5 is now available with the changes for non-aoTuV Vorbis.
