### ISSUE TITLE
does not read m4p files

### ISSUE THREAD

**Issue by vintagestich** [enzo1982/freac#220]
**Describe the bug**
the program will not read or convert m4p files
**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**System (please complete the following information)**
 - OS: [e.g. macOS Mojave 10.14.5]
 - CPU: [e.g. Intel Core i7 6700K]
 - RAM: [e.g. 8 GB]

**Additional context**

**Comment by enzo1982** [comment]
The p in m4p stands for _protected_.

These files a protected and encrypted with a Digital Rights Management (DRM) scheme (usually [Apple's FairPlay](https://en.wikipedia.org/wiki/FairPlay)) to restrict what you can do with them. Basically, you bought a license to play those files on your Apple devices (with FairPlay compatible software such as Apple Music), but cannot convert them to unprotected formats as that would circumvent the protection.

There is no way for fre:ac to convert such files. You will need to get an m4a version of the files for that.
