### ISSUE TITLE
GUI does not scale on Xfce

### ISSUE THREAD

**Issue by killermoehre** [enzo1982/freac#222]
**Describe the bug**
The UI does not scale according to set DPI in Xfce 4.16.

**To Reproduce**
1. Use [Xfce](https://xfce.org)
2. set DPI in `xfce4-appearance-settings` → `Fonts` to something bigger than `96` (I use `196`)
3. open `fre:ac` and see fonts so small you can't identify it on HiDPI screens

**Expected behavior**
The UI scales according to the X DPI settings.

**Screenshots**
![fre:ac not scaled](https://user-images.githubusercontent.com/7925665/122965991-17e81c80-d389-11eb-83a2-d804208a3df3.png)

**System (please complete the following information)**
 - OS: Arch Linux
 - DE: Xfce 4.16, GTK3 3.24.29
 - CPU: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
 - RAM: 16 GiB

**Comment by enzo1982** [comment]
Thank you for reporting this!

This should be fixed in the latest [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous) via enzo1982/smooth@f0105fe8.

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.5 is now available with the fix.
