### ISSUE TITLE
Problem beim Konvertieren der .dsf-Datei in flac

### ISSUE THREAD

**Issue by fre-ac** [enzo1982/freac#225]
Ich habe die neue Version 1.1.5 installiert. Es gibt ein Problem beim Konvertieren der .dsf-Datei in flac. Nun, die resultierende flac-Datei ist größer als die dsf-Datei. Das Ändern der flac-Codec-Einstellungen hilft nicht. Ich habe eine neue Version des flac v1.3.3 und des Flake flac Codecs installiert. Keine Änderung. Das Konvertieren in mp3 funktioniert einwandfrei. Vielen Dank für Ihre Aufmerksamkeit.
![dsf_to_flac_and_mp3__2](https://user-images.githubusercontent.com/85880630/126385236-4c48a7ad-a9a6-49b4-bf69-4d329f652ea9.png)

**Comment by enzo1982** [comment]
Dass bei der Konvertierung von DSD/DSF nach FLAC die FLAC-Dateien größer sind, ist normal. DSD-Dateien sind nach einem anderen Verfahren aufgezeichnet als dem üblicherweise bei Audioformaten verwendeten PCM-Verfahren. Um das DSD-Signal möglichst originalgetreu wiederzugeben, wird bei der Umwandlung in ein PCM-Signal eine sehr hohe Samplerate verwendet (i.d.R. 352 kHz). Das wiederum führt zu den sehr großen FLAC-Dateien.

Die MP3-Dateien haben eine normale Größe, da 1. die Samplerate bei MP3 auf 48 kHz begrenzt ist und 2. die Bitrate der MP3-Datei in erster Linie von den Kodierereinstellungen bestimmt und nur wenig durch das Tonmaterial beeinflusst wird.

Um kleinere FLAC-Dateien zu erhalten, sollte in den Verarbeitungseinstellungen die Samplerate reduziert werden, z.B. auf 48 kHz.
