### ISSUE TITLE
Cue sheet 'FILE' format is WAVE for flac files

### ISSUE THREAD

**Issue by MGislv** [enzo1982/freac#227]
**Describe the bug**
Example:
`FILE "01 - Moonchild.flac" WAVE`

Instead of `FILE "01 - Moonchild.flac" FLAC`

**To Reproduce**
1. Set the encoder to flac and rip the CD
3. Cue sheet uses WAVE instead of FLAC for each referenced file

**Expected behavior**
Cue sheet should use the referenced file format

**Screenshots**

**System (please complete the following information)**
 - OS: Linux arch 5.13.8-arch1-1 x86_64 GNU/Linux
 - CPU: AMD Athlon 64 X2 Dual 4200+
 - RAM: 2GB

**Additional context**
I also ticked "Look for compressed alternatives if referenced Wave files cannot be located" under Decoders --> Cue Sheet Reader.

**Comment by enzo1982** [comment]
This is not a bug.

The only valid format designators allowed in the cue sheet `FILE` command are `WAVE`, `AIFF`, `MP3`, `BINARY` and `MOTOROLA`. All other formats regularly use the `WAVE` designator. See also the [HydrogenAudio knowledge base article on cue sheets](https://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Most_often_used).

A command like `FILE "01 - Moonchild.flac" FLAC` would render the cue sheet invalid.
