### ISSUE TITLE
WAV encoder missing on linux

### ISSUE THREAD

**Issue by plonibarploni** [enzo1982/freac#23]
I recall in the Windows version there was an option to use a WAV encoder, and this is also advertised on the website, but when trying out the latest alpha on linux, it's not there.

**Comment by enzo1982** [comment]
The Wave Output Filter of fre:ac 1.0.x is replaced by the SndFile Output Component in fre:ac 1.1.

The latter supports not only .wav, but a wide range of simple audio formats including .aiff, .caf, .w64 and .rf64. It defaults to creating .wav files though.

You should see the SndFile Output Component among the other encoders in fre:ac.
