### ISSUE TITLE
Manual translation for Brazilian Portuguese

### ISSUE THREAD

**Issue by wtuemura** [enzo1982/freac#231]
Sent this through e-mail but got no return.

Thank you.
[freac_manual_Brazilian_Portuguese.zip](https://github.com/enzo1982/freac/files/7181290/freac_manual_Brazilian_Portuguese.zip)

**Comment by enzo1982** [comment]
Good work! Thank you very much! And sorry for responding only now. I was busy when I got your mail and this ticket and then almost forgot about it. But I'm preparing a new release right now and found your ticket again.

The Brazilian Portuguese manual will show up in the next continuous build and will be in included with fre:ac 1.1.6 in a few days.

Also thank you for always keeping the program translation up to date on Crowdin! Greatly appreciated!

**Comment by enzo1982** [comment]
fre:ac 1.1.6 is now available and includes the Brazilian Portuguese manual.

**Comment by wtuemura** [comment]
Thank you @enzo1982
