### ISSUE TITLE
Feature request: Encode and cut encoded file into smaller by time and size accordingly

### ISSUE THREAD

**Issue by duytrung** [enzo1982/freac#233]
**Is your feature request related to a problem? Please describe.**
I have use Freac for a year but found there is no functionality to cut the encoded file into smaller parts according to size and length.

**Describe the solution you'd like**
I have 4 audio lectures with different lengths and bit-rates, I would like to encode all of them into 1 single file and split them into 4 parts with the same amount of size or length such as:

4 hours -> 4 of 1 hour-lenght mp3s
Or
20MB -> 4 of 5MB-size mp3s

**Describe alternatives you've considered**
Freac has a function to encode multiple files into a single file. I have to use another software to split them but sometimes not successful as that program is buggy and unstable, especcially with large file.

Thanks for considering the issue

**Comment by enzo1982** [comment]
This feature is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7).

To access it, load files/tracks into the joblist, then select _Encode->Output splitting tool..._ from the menu or click the new toolbar button to the left of the _Start encoding_ button.

Closing this issue.
