### ISSUE TITLE
MacOS Monterey Not possible to convert multiply files to a single file

### ISSUE THREAD

**Issue by Olli0073** [enzo1982/freac#238]
Problems with MacOS Monterey 12.0.1
When encode multiple Files to "Encode to single file" an error displays. 
"The Save file operation failed" "The save file operation failed to connect to the option and save panel service"

**Comment by enzo1982** [comment]
Continuous builds for Apple Silicon Macs are now available and I'm delaying the 1.1.6 release by a few days to allow finishing some other items.

**Comment by enzo1982** [comment]
This is now fixed in the official fre:ac 1.1.5a hotfix. Closing this issue.
