### ISSUE TITLE
Barcode length limited

### ISSUE THREAD

**Issue by Adam-89-SK** [enzo1982/freac#239]
**Describe the bug**
Number of digits in Barcode is limited to 12 the correct value should be 13.

**To Reproduce**
1. Go to 'insertCD - add audio from CD - Tag - Album - publisher - Publisher Info'
2. Click on 'Barcode: try to input 13 numbers - usual barcode size '
3. See error - only 12 digits available

**Expected behavior**
The barcode should have 13 digits.

**Screenshots**

![Freac bug report Barcode](https://user-images.githubusercontent.com/93492161/139600415-d6bdd6b6-ff6f-4163-b000-b70eb19f2a3c.png)

**System (please complete the following information)**
 - OS: [Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal]
 - CPU: [Intel Core i5-2400 bits: 64 type: MCP arch: Sandy Bridge 
           rev: 7 L2 cache: 6144 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 24743 
           Speed: 3210 MHz min/max: 1600/3400 MHz Core speeds (MHz): 1: 3205 2: 3203 3: 3193 
           4: 3198]
 - RAM: [Memory: 7.61 GiB]

**Additional context**

**Comment by enzo1982** [comment]
Thank you for reporting this!

Fixed in bffb7138. This limit also affected the media type and catalog number fields. The code to set up these fields had been copied from the ISRC field code and the limit erroneously left in place.

Continuous builds with the fix will be available in a few minutes.

**Comment by enzo1982** [comment]
Closing this as fre:ac 1.1.6 has been released with the fix.
