### ISSUE TITLE
Add support for Overdrive chapter metadata ("MediaMarkers")

### ISSUE THREAD

**Issue by thw0rted** [enzo1982/freac#242]
**Is your feature request related to a problem? Please describe.**
Some OverDrive audiobooks ship as multiple MP3 "parts", each with a custom tag containing XML-formatted chapter marker data.  (I guess ID3v2 chapter frame tags aren't good enough?)

**Describe the solution you'd like**
It would be great if fre:ac could detect this custom tag, and parse it for chapter data when present, treating it the same as "real" ID3 tag chapter data.

**Describe alternatives you've considered**
* Suffer through bad/no chapter markers
* Hack together a CLI script to copy the Overdrive stuff to real ID3 chapter-frame tags
* Switch to another encoder that supports them already

**Additional context**
I found a few other projects that have already added support:
* https://github.com/sandreas/m4b-tool/issues/114
* https://github.com/pflouret/overdrive-m4b/blob/master/bin/overdrive-m4b

**Comment by enzo1982** [comment]
Uh, ID3v2 chapter frames are far superior to these OverDrive markers...

I guess they didn't know about the ID3v2 chapter addendum (which is not part of the original standard, but was proposed later by the BBC) and felt they needed to re-invent the wheel.

I will add support for parsing these. Should be doable quickly, so this will be available in the next update.

**Comment by thw0rted** [comment]
No idea why they rolled their own standard, other than [the usual answer](https://xkcd.com/927/).

I noticed that they look like XML but don't have an opening document tag, and the books I'm using don't seem to include any attributes either.  I wonder if they use entity escapes or CDATA sections?  I think one of the linked implementations actually uses an *HTML* parser, presumably because they're more forgiving.

Anyway, thanks for the quick response!

**Comment by enzo1982** [comment]
Please try the latest [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous). It should be able to read OverDrive markers.

Let me know if anything is not working. I might need some example files then (wasn't able to find any online, so the current implementation is more like a best guess).

**Comment by thw0rted** [comment]
I tried it with one book and it looks good -- each marker loads as one "part" in the job list, then in the assembled (single) file it shows the marker titles as I mouse over the scrubber in VLC.

Thanks for the quick response!

**Comment by enzo1982** [comment]
Great! Thanks for reporting back!

**Comment by thw0rted** [comment]
Hi Robert, I just wanted to check if you were planning a public release with this feature any time soon.  I'm not sure what your schedule/process is, but it looks like there hasn't been a numbered release for some months now.

**Comment by enzo1982** [comment]
fre:ac 1.1.6 is available now.
