### ISSUE TITLE
Open file operation failed

### ISSUE THREAD

**Issue by jmannatl** [enzo1982/freac#245]
Can't select destination folder on MacBook Air,  macOS Monterey 12.0.1 

"The open file operation failed to connect to the open and save panel service".

**Comment by enzo1982** [comment]
Yes, there's a bug in macOS Monterey that needs a work-around. This is already implemented in the [continuous builds](https://github.com/enzo1982/freac/releases/continuous) as mentioned in the [Downloads](https://www.freac.org/downloads-mainmenu-33) section on freac.org:

> **_Users of macOS Monterey:_** please use the [Continuous Build](https://www.freac.org/downloads-mainmenu-33/308-freac-continuous) for now which fixes an issue with the file dialog of fre:ac 1.1.5 when running on the current version of macOS Monterey; an official release with the fix will be available shortly

**Comment by jmannatl** [comment]
thanks! Just donated, love the product. 
    On Monday, November 22, 2021, 10:09:56 AM MST, Robert Kausch ***@***.***> wrote:  
 
 


Yes, there's a bug in macOS Monterey that needs a work-around. This is already implemented in the continuous builds as mentioned in the Downloads section on freac.org:


Users of macOS Monterey: please use the Continuous Build for now which fixes an issue with the file dialog of fre:ac 1.1.5 when running on the current version of macOS Monterey; an official release with the fix will be available shortly


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by enzo1982** [comment]
> thanks! Just donated, love the product. 

That's great! Thank you very much!

**Comment by enzo1982** [comment]
This is now fixed in the official fre:ac 1.1.5a hotfix. Closing this issue.
