### ISSUE TITLE
avoid overwrite

### ISSUE THREAD

**Issue by lucasmz1** [enzo1982/freac#254]
how do I avoid overwrite files? here's the situation, I have one folder full of files but I want it don't overwrite cause they have same name.
how do I do that ?

**Comment by enzo1982** [comment]
Just enable the option _"Append sequential numbers to otherwise identical filenames"_ at the bottom of the _Encoders_ page of the configuration dialog.

**Comment by Lakrits** [comment]
![freac_gen_sett_app_seq](https://user-images.githubusercontent.com/1184718/145724067-ab5c905d-5cdd-441a-8712-28d34b7a5b33.png)
