### ISSUE TITLE
freaccmd: No freedb entry for this disk.

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#255]
**Describe the bug**
i am ripping cds on a regular basis. since a couple of weeks freaccmd does not seem to be able to get the disc information.

Example:

i tried to rip Alan Parsons - The NeverEnding Show Lie In The Netherlands (Deluxe DVD + 2CD Set)

Getting infos for device /dev/liteon-01 freedb 820b0109 musicbrainz CI48e688R9wk8DpjajsY..UYYhM- mcn
ripping /dev/liteon-01 - discid: 820b0109

Info: 820b0109: No freedb entry for this disk.

cddb query 820b0109 9 150 21834 43363 63436 89772 115596 138570 167224 190210 2819

**To Reproduce**
./freaccmd -e flac -cd /dev/liteon-01 --superfast --threads=3 --track=all --cddb --eject -d /Volumes/Musik/_INC/_RIPPED_ -p <filetype>/<album> (<discid>)/<disc(2)><track(2)> - <artist> - <title>

**Expected behavior**
i expect freaccmd to query the data from a cddb source

**Screenshots**

**System (please complete the following information)**
 - OS: Linux Mint 20
 - CPU: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
 - RAM: 8 GB
 - Freac Version: fre:ac - free audio converter v1.1.5 (20211212) (x86-64) command line interface

**Comment by enzo1982** [comment]
GnuDb does not seem to have an entry for that particular disc, so looks like freaccmd's output is correct here.

The only entry for disc ID 820b0109 in GnuDb is for a completely different disc: https://gnudb.org/gnudb/rock/820b0109

GnuDb relies on users providing disc information. If no one ever entered this disc into the database, you will not be able to find it there. You can submit entries to the database in the fre:ac GUI.

**Comment by wkremser** [comment]
well i tried it with adele 30 too ... this is in the gnudb but had the same error.

but thx i will try more cds ;)

**Comment by wkremser** [comment]
ok, it seems to work fine ... thx for the reply :) 

closing this issue

**Comment by enzo1982** [comment]
Thanks for checking again!

According to MusicBrainz, the 12 track edition of the Adele 30 album has different pressings for the US and Europe, resulting in different disc IDs. GnuDb has only one disc ID for this album, so I suspect it will be the US pressing while you probably have the European one.

I'm working on MusicBrainz support for fre:ac by the way. That will greatly enhance the disc information querying capabilities of fre:ac in the future. Maybe if I get to it over the Christmas holidays this will show up in continuous builds already in January (cannot promise that, though).

**Comment by wkremser** [comment]
ooh this would be huuge :) ... i could start testing mid january  ;) have still a lot of cds to get ripped
