### ISSUE TITLE
Don't override user-specified -arch flags; don't rely on xcodebuild

### ISSUE THREAD

**Issue by ryandesign** [enzo1982/freac#256]
The build system is very opinionated about which architectures and flags should be used to build on macOS.

The user compiling freac (or the package management system compiling freac on the user's behalf) may wish to specify which architecture(s) to use. There doesn't seem to be a provision in the build system to allow this.

The build system seems to use the Xcode version as obtained by `xcodebuild` and the target macOS version as specified in `MACOSX_DEPLOYMENT_TARGET` as the basis for its decisions. This doesn't work if the user doesn't have Xcode installed. For example, they may only have the command line tools installed. In this case the build will emit many errors like this:

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
bash: line 1: [: -le: unary operator expected
```

Nevertheless the build succeeds, but who knows how closely it resembles the build you intended.

The build system sets various other defines like `BUILD_PPC` or `BUILD_X86` and makes further decisions based on that. This makes it difficult for a user or package management system that expects to be able to tell the build system which architecture(s) to build for by including the appropriate `-arch` flag(s) in CFLAGS, CXXFLAGS, and LDFLAGS.

**Comment by enzo1982** [comment]
The build system does not set any `-arch` flags unless you invoke it with `make config=release`. Don't do that if you want to specify your own custom flags. `make config=release` sets various optimization and symbol stripping flags and is meant to be used only for official release builds. Instead, set your CFLAGS, CXXFLAGS and LDFLAGS as you need and just call `make`.

You're right about `xcodebuild` being invoked unconditionally. The decisions made based on the installed Xcode version are only used with `make config=release`, so I updated the build system to only invoke `xcodebuild` when that argument is used.

**Comment by ryandesign** [comment]
> The build system does not set any `-arch` flags unless you invoke it with `make config=release`

Ah, that explains it. I was seeing `xcodebuild` being invoked but I didn't actually see `-arch` flags being added (I imagined that maybe it was because I was on Catalina where there's only one arch you can build for anyway).

> I updated the build system to only invoke `xcodebuild` when that argument is used

Super, thanks. For anyone looking for it, it was 1a2f009f0e4bf562449ebb161d5fafae71ac2095.
