### ISSUE TITLE
Fre:ac changes the Track-Numer of the converted file

### ISSUE THREAD

**Issue by gerd-steffens** [enzo1982/freac#258]
**Describe the bug**
I try to convert a folder with 8 songs using format *.wma to another folder and the new format *.ogg.
All worked fine, but the new files didn't start with "Track 1" but with "Track 2". The original *.WMA file had the right Track-Number 1.
Why did the program change it?

**To Reproduce**
3. See error

**Expected behavior**
The programm should not change the track-number within the tags

**Screenshots**

**System (please complete the following information)**
Win 10
 - CPU: Intel Core i5 7400]
 - RAM: 16 MB
 

**Additional context**

**Comment by enzo1982** [comment]
Microsoft defines two different metadata attributes for track numbers:

- [WM/Track](https://docs.microsoft.com/windows/win32/wmformat/wm-track) is 0-based, so a value of 0 means track 1, a value of 1 means track 2 and so on.
- [WM/TrackNumber](https://docs.microsoft.com/windows/win32/wmformat/wm-tracknumber) is 1-based, so a value of 1 means track 1 as with most other tagging formats.

Many applications get this wrong especially with WM/Track and write 1 to mean track 1 and this is the reason why Microsoft at some point introduced the newer WM/TrackNumber attribute.

fre:ac implements these attributes according to the official specification, so when it encounters a 1 in the WM/Track attribute, it interprets this as track 2.

So most likely this is not a bug in fre:ac, but in the program originally used to tag the WMA files. That program probably wrote WM/Track values ignoring that the attribute is 0-based.

If you would like me to confirm this by having a look at one of your files, you can send a file or a link to it to support@freac.org.

**Comment by gerd-steffens** [comment]
Enzo1982 is correct, the original *.wma file shows: "Track 1". It was written in 2012 by napster - maybe they did their job badly in that times.
So it's not a bug.
