### ISSUE TITLE
MusicBrainz metadata tags stripped during transcoding

### ISSUE THREAD

**Issue by rfilmyer** [enzo1982/freac#262]
**Describe the bug**
fre:ac implicitly strips out a number of MusicBrainz-associated tags that picard adds:

* MusicBrainz Artist Id
* MusicBrainz Recording Id
* MusicBrainz Release Id
* MusicBrainz Release Artist Id
* MusicBrainz Release Group Id
* MusicBrainz Release Track Id

This ends up in me having to re-add the files in Picard to recover the MusicBrainz metadata.

Not sure if this is expected behavior (fre:ac appears to do some implicit stripping of certain tags), but it is a bit disruptive to my workflow

**To Reproduce**
1. Grab a FLAC file (let's use this as an example: https://archive.org/details/bucket2008-07-28.flac16.sbd/buckethead2008_07_28d01_t13.flac )
2. Load it into MusicBrainz Picard and tie it to the appropriate recording/release ( Track 13 from the Buffalo, NY show https://musicbrainz.org/release/643d560f-1b76-46e4-bd5e-d23d5ccfd215 ). Note that you now have a number of MusicBrainz metadata tags that Picard wants to add to the file.
3. Save the changes, adding the requisite metadata to your FLAC file.
4. Open the FLAC in fre:ac, and choose to convert to Opus (file format likely does not matter)
5. Press the "play" button to convert
6. Open the transcoded file in Picard
7. Notice that the MusicBrainz tags, as well as several Sort Order tags, the "Artists" tag, Release Status, and Release Type are missing.

**Expected behavior**
These tags should be preserved, not thrown away.

**Screenshots**

Original Picard matching:
![freac bug report 262 - original file in picard](https://user-images.githubusercontent.com/5913205/151408109-4c06a3cf-5159-4665-8419-fa6f775f2d8d.png)

Loaded in fre:ac
![freac bug report 262 - loaded into freac](https://user-images.githubusercontent.com/5913205/151408143-897906ea-b1f4-4b45-bff2-4e59ed88a727.png)

Reopening Picard:
![freac bug report 262 - transcoded file in picard](https://user-images.githubusercontent.com/5913205/151408151-60d1ca86-7d4f-47e4-9551-ee3c0118d611.png)

**System (please complete the following information)**
 - OS: Windows 10 Home, version 21H1, build 19043.1503
 - CPU: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz   4.10 GHz
 - RAM: 16GB

**Comment by enzo1982** [comment]
The latest [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous) now preserves MusicBrainz metadata and sort order tags.

**Comment by rfilmyer** [comment]
This substantially fixes my issue. While some metadata still gets stripped (With multiple MB Artist IDs, only the first is kept; the rest are discarded), this still satisfies my use case.
