### ISSUE TITLE
Support xHE-AAC encoder

### ISSUE THREAD

**Issue by gabriele2000** [enzo1982/freac#264]
Title says all, it surpass HEv2-AAC as far as I can see with even better compression

**Comment by enzo1982** [comment]
fre:ac supports the exhale xHE-AAC encoder (as far as I know the only publicly available one).

To use it, build or get an exhale binary (an exhale.exe for Windows is available from [rarewares.org](https://www.rarewares.org/aac-encoders.php)) and copy it to the codecs/cmdline folder inside the fre:ac program directory.

**Comment by gabriele2000** [comment]
> The Snap version runs in a sandbox and cannot be extended with external codecs.
> 
> If you can switch to the AppImage version, it will offer the exhale encoder if the exhale binary exists in /usr/local/bin.

Done, thanks a lot!
