### ISSUE TITLE
Follow Linux desktop UI policy

### ISSUE THREAD

**Issue by RafaelLinux** [enzo1982/freac#266]
**Is your feature request related to a problem? Please describe.**
Even using only a FHD display, text font size of freac in Linux doesn't follow user desktop policies. I have some visual issues and it's difficult for me to read freac UI text. I not agree with  "Windows UI is UGLY #119 ", cause I think is effective.

**Describe the solution you'd like**
Despite I read it's possible to change font size in command line, I think is not an elegant fix nowadays. By default, it should follow system user preferences about font and UI size.

**Describe alternatives you've considered**
At least, to implement a way to let user to change UI / font size from freac "Options"

Thanks

**Comment by enzo1982** [comment]
fre:ac is supposed to respect the desktop environment's font settings on Linux.

However, I just checked this again and found that while the font size and DPI scaling settings were respected. There also is a text scaling setting (available e.g. under accessibility settings in Ubuntu) that is applied on top of the font size and was not respected before.

So if you are using this setting to have larger fonts, the current release version of fre:ac will have a too small font.

Support for this text scaling option is now available in the [continuous builds](https://github.com/enzo1982/freac/releases/continuous). Please check if this fixes the issue for you.

If the continuous build does not fix the issue for you, please let me know what distribution and desktop environment you are using and which settings you changed to get larger fonts in other applications.

**Comment by RafaelLinux** [comment]
I tried just today continuous version ([freac-continuous-linux-x86_64.AppImage](https://github.com/enzo1982/freac/releases/download/continuous/freac-continuous-linux-x86_64.AppImage) but same issue.

My apologies because I forgot to include my desktop information:

- Operating System: openSUSE Tumbleweed 20220205
- KDE Plasma Version: 5.23.5
- KDE Frameworks Version: 5.90.0
- Qt Version: 5.15.2
- Kernel Version: 5.16.4-1-default (64-bit)
- Graphics Platform: X11
- Processors: 8 × Intel® Core™ i7-9700K CPU @ 3.60GHz
- Memory: 15.4 GiB of RAM
- Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2

**Comment by enzo1982** [comment]
Thanks for posting the specs. I was able reproduce the issue on openSUSE.

Turns out that setting the display scale factor in KDE does not update the `scaling-factor` value in gsettings. I think it did so before and fre:ac's scaling worked on KDE back then.

Anyway, right now it's not set, so I updated the code to query KDE's settings directly if `gdk_screen_get_monitor_scale_factor` does not return anything useful.

Please try the new continuous build. It should work now.

**Comment by RafaelLinux** [comment]
It seems you fixed it!!!! I'll try tomorrow in my base system too, but I'm sure it will work so well like in this one (openSUSE both).
Meanwhile I'll close this issue, cause you really did a great job fixing it!!
Thank you a lot
