### ISSUE TITLE
flatpak Version can't save file 

### ISSUE THREAD

**Issue by perelandra** [enzo1982/freac#28]
Version fre:ac v1.1 Alpha 20181201a on ubuntu 18.04 saves single file but the flatpak version shows the progress file with 0 bytes too, but the removes it, instead of replacing with the result of the single file.

**Comment by enzo1982** [comment]
The new 20190423 version comes with some fixes for issues with MP4/M4A that might have led to the observed behavior as well.

Please check and close this issue if it is fixed. If there are no further updates, I'll close it in a few days.
