### ISSUE TITLE
TwinVQ (VQF) read feature 

### ISSUE THREAD

**Issue by RafaelLinux** [enzo1982/freac#285]
I had several old and unreplaceabled audio files in VQF format (better than MP3 but slower encoding). Now I would like to convert to "opus" format  so ... 

Please, is there any possibility to implement VQF read feature to FRE:AC?

I can play them with QMMP Player (it uses ffmpeg so I believe could be easy to add to FRE:AC to read VQF files) 

Thank you!!

**Comment by enzo1982** [comment]
Please try the latest [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous). It adds support for decoding VQF vis FFmpeg.

**Comment by RafaelLinux** [comment]
Great!!! I just added a comment about it before reading your post!!! ;)

**Comment by enzo1982** [comment]
The change is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7). Closing this issue.

**Comment by RafaelLinux** [comment]
Thank you!!! I'll download it yet!!!  ;)
