### ISSUE TITLE
Recent updates of freac.xml on GitHub but related strings are not created on Crowdin

### ISSUE THREAD

**Issue by Patriccollu** [enzo1982/freac#287]
Hi Robert,

I noticed there was a couple of recent updates of [freac.xml](https://github.com/enzo1982/freac/commits/master/i18n/freac/freac.xml) on *GitHub* but there were not created on *Crowdin*.

The entry ids are: 12006, 50502, 5252, 5255, 5256, 5257 and 5501.

Is it on purpose? Do you plan to add these new entries on *Crowdin* in the future?

If you prefer, I can prepare an update of `freac_co.xml` for **Corsican** via a *GitHub*'s pull request? Just tell me.

Kind regards,
Patriccollu.

**Comment by Patriccollu** [comment]
@enzo1982 
Hi Robert,

I hope that you are well!

The problem recently occurred again and I just created pull request #341 to update `freac_co.xml`.

I hope this is the right way. If not, feel free to tell me what do you prefer.

Kind regards,
Patriccollu.

**Comment by enzo1982** [comment]
Hi Patriccollu,

Thank you for bringing this up and for updating your translation here on GitHub!

The Crowdin translations are synchronized manually and it's always a bit of work. So I'm usually doing that only before a release. GitHub pull requests are the best way to update translations between releases.

I did not have much time to spend on fre:ac in the past few months, unfortunately, so I'm a bit behind my plan for the next release. But it will come eventually. 😃 

Best,
Robert

**Comment by Patriccollu** [comment]
@enzo1982 
Hi Robert,

Thanks a lot for these explanations which clarify the process. No problem for me to work this way. I'm closing this issue.

Cheers,
Patriccollu.
