### ISSUE TITLE
TTA codec DECODER add plz

### ISSUE THREAD

**Issue by thestreetdj** [enzo1982/freac#294]
TTA file ..to flac covert error...
TTA decoder add plz.

**Comment by enzo1982** [comment]
There's a new [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous) now that supports decoding .tta files out of the box using FFmpeg.

Previous releases were prepared for TTA support, but you had to add `ttaenc.exe` to the `codecs\cmdline` folder manually (or the `ttaenc` binary to `/usr/local/bin` on non-Windows systems).

In addition to allowing TTA decoding out of the box, future releases will also support the newer `tta`/`tta.exe` binary in addition to the older `ttaenc`/`ttaenc.exe`. That change is not in the current continuous build yet, but will be available soon.

**Comment by enzo1982** [comment]
The change is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7). Closing this issue.
