### ISSUE TITLE
Feature request: queue multiple jobs at once (or, add folder-of-folders)

### ISSUE THREAD

**Issue by thw0rted** [enzo1982/freac#296]
I use fre:ac to join multi-MP3 audiobooks into a single M4A/M4B book.  It works great for this, but when I have multiple books to convert at once, I have to add a folder, start the job, wait several minutes for it to finish converting, then repeat the whole process for the next one.  There doesn't seem to be an easy way to continue adding "jobs" in the background while the first one is running, or to point to a folder containing multiple folders (one per audiobook) and have each converted automatically.

If there's already a feature to do this, I'd be happy to hear about it.  If not, I could probably knock out a shell script to do it using the command line interface, but it would be nice to be able to do this from the UI as well.

**Comment by thw0rted** [comment]
I just found https://github.com/enzo1982/freac/issues/164 which sounds pretty similar -- if you think the solution you proposed there is the best way to solve my problem, I'm happy to close this issue and follow that instead.

**Comment by enzo1982** [comment]
> I just found https://github.com/enzo1982/freac/issues/164 which sounds pretty similar -- if you think the solution you proposed there is the best way to solve my problem, I'm happy to close this issue and follow that instead.

Yes, you don't have to wait until a conversion is finished. Just clear the joblist after starting the first conversion, then prepare and start the next one. Already running conversions will be unaffected by joblist changes.

I also still plan to add the output splitting tool mentioned in #164 which will make this even easier (you will be able to add all your folders at once then and get one output file per folder). I have a prototype of this already, but still need some time to finish it.

**Comment by thw0rted** [comment]
Just to check, if I add a folder, click Start (pick a save-as filename), then clear the joblist and do it again -- then do it all a *third* time, all during the first conversion -- does that result in all 3 getting converted?  Are the "pending" tasks shown anywhere in that case?

Either way, I'll track #164 and close this one.  As long as I can eventually add a folder containing a number of multi-file books, and get each book in its own file, I'm happy with that.  (I assume that this solution will name the files based on the suggested name in the save-as dialog?  That works for me, because I always use MP3tag to edit the metadata and rename the files when I'm done anyway.)
