### ISSUE TITLE
Build OK but can not process files on openSUSE

### ISSUE THREAD

**Issue by andrecbarros** [enzo1982/freac#3]
Hi,

I have used your great app a couple of times on Windows and got excited you are porting it to Linux.

I tried to build it on openSUSE and made the needed .spec recipes for RPM packages. The building process was OK but when I started the application I could not add files to new projects.

The used .spec files are attached, if I can help on something, please, let me know.

Some observations about the package generation and handling of files, libraries and paths:
- it was really not needed but all source files were processed through dos2unix;
- the 'Makefile-options' were patched to have the target directory prefix changed to '/usr' instead of '/usr/local'. Also, for x86_64 arch, '/usr/lib' was translated to '/usr/lib64';
- for 'BoCA' and 'freac' there is a need to add the libraries paths to '/etc/ld.rc.conf.d';
- 'freac.so' had it's name changed to 'libfreac.so' so that ldconfig can add it to the list of known libraries.

Regards,
André

[superfast.spec.txt](https://github.com/enzo1982/freac/files/1616467/superfast.spec.txt)
[smooth.spec.txt](https://github.com/enzo1982/freac/files/1616469/smooth.spec.txt)
[freac.spec.txt](https://github.com/enzo1982/freac/files/1616472/freac.spec.txt)
[freac.desktop.txt](https://github.com/enzo1982/freac/files/1616474/freac.desktop.txt)
[boca.spec.txt](https://github.com/enzo1982/freac/files/1616476/boca.spec.txt)

**Comment by enzo1982** [comment]
Hi André,

Thanks alot for creating the .spec files!

Some remarks from me:

- It should not be necessary to add the libraries paths to '/etc/ld.rc.conf.d'. The libraries in the 'BoCA' and 'freac' folders are not meant to being linked against at build time - except for boca.1.0.so, but that already has a symlink as 'libboca-1.0.so' in '/usr/lib'.
- 'freac.so' should not be renamed to 'libfreac.so' for the same reason.
- 'cdparanoia' should not be needed to build BoCA on Linux. 'libcdio' is used instead.

I guess you are unable to open any files with fre:ac, because there are no codecs installed (assuming you are running the build result in something like a chroot environment with only the libraries mentioned in 'Requires:' available).

You should provide at least the following packages for fre:ac at runtime:

- libsndfile for simple audio formats like .wav and .aiff
- libcdio and libcdio-paranoia for CD ripping
- libfdk-aac or libfaac and libfaad2 for AAC encoding/decoding
- libmp3lame and libmpg123 for MP3 encoding/decoding
- libFLAC, libopus, libspeex and libvorbis for the corresponding formats
- libogg and libmp4v2 for container format support
- libsamplerate for resampling support

And optionally the following command line utilities:

- mpcenc and mpcdec for Musepack (.mpc) support
- ofr for OptimFROG (.ofr) support
- wavpack and wvunpack for WavPack (.wv) support
- avconv or ffmpeg for additional format support (encoding ALAC and WMA plus decoding various other formats)

I will try building fre:ac using the .spec files myself in the next few days.

Cheers,
Robert

**Comment by andrecbarros** [comment]
Hi Robert,
OK, will check again to see what went wrong but I did end up installing them properly after getting errors on a chrooted environment.
For openSUSE, it may be needed  to update the fdk-aac as the current version from packman repo does not contain the latest fixes.
All cited libraries are installed (I regularly build a qt5 version of audacious for testing purposes, the 'official' version on SUSE repo is linked against gtk3).
Quote: "mpcenc and mpcdec for Musepack (.mpc) support"On openSUSE there is a 'mppenc' and I could not find any 'mpcdec' or equivalent.
Quote: "wavpack and wvunpack for WavPack (.wv) support"Both installed.
Quote: "avconv or ffmpeg for additional format support ..."
'ffmpeg' installed.
It seems to me that, perhaps, the problem may be related to the gtk3 version on openSUSE 42.3 I am using, specially on processing filter masks. What is the minimum version you recommend? (mine is 3.20.10)
Regards,André



 
 

    On Tuesday, January 9, 2018 7:01 PM, Robert Kausch <notifications@github.com> wrote:
 

 Hi André,Thanks alot for creating the .spec files!Some remarks from me:   
   - It should not be necessary to add the libraries paths to '/etc/ld.rc.conf.d'. The libraries in the 'BoCA' and 'freac' folders are not meant to being linked against at build time - except for boca.1.0.so, but that already has a symlink as 'libboca-1.0.so' in '/usr/lib'.
   - 'freac.so' should not be renamed to 'libfreac.so' for the same reason.
   - 'cdparanoia' should not be needed to build BoCA on Linux. 'libcdio' is used instead.
I guess you are unable to open any files with fre:ac, because there are no codecs installed (assuming you are running the build result in something like a chroot environment with only the libraries mentioned in 'Requires:' available).You should provide at least the following packages for fre:ac at runtime:   
   - libsndfile for simple audio formats like .wav and .aiff
   - libcdio and libcdio-paranoia for CD ripping
   - libfdk-aac or libfaac and libfaad2 for AAC encoding/decoding
   - libmp3lame and libmpg123 for MP3 encoding/decoding
   - libFLAC, libopus, libspeex and libvorbis for the corresponding formats
   - libogg and libmp4v2 for container format support
   - libsamplerate for resampling support
And optionally the following command line utilities:   
   - mpcenc and mpcdec for Musepack (.mpc) support
   - ofr for OptimFROG (.ofr) support
   - wavpack and wvunpack for WavPack (.wv) support
   - avconv or ffmpeg for additional format support (encoding ALAC and WMA plus decoding various other formats)
I will try building fre:ac using the .spec files myself in the next few days.Cheers,
Robert—

**Comment by enzo1982** [comment]
mppenc/mppdec are the Musepack SV7 tools and are not supported by fre:ac. mpcenc/mpcdec are the newer Musepack SV8. Not a big issue if they are not available for now, though.

I don't know about the gtk version. I used various versions of gtk 2 and 3 before and did not see any problems. I'll take a look later when I try the build myself. Can you add files to the joblist by drag & drop?

**Comment by andrecbarros** [comment]
Hi Robert,
No, I can't use dnd, it gives me the same error as when I try to add a file by menu/button (see the picture). I will, probably, will enable debugging I check it out by weekend.
Regards,André
 

    On Tuesday, January 9, 2018 9:01 PM, Robert Kausch <notifications@github.com> wrote:
 

 mppenc/mppdec are the Musepack SV7 tools and are not supported by fre:ac. mpcenc/mpcdec are the newer Musepack SV8. Not a big issue if they are not available for now, though.I don't know about the gtk version. I used various versions of gtk 2 and 3 before and did not see any problems. I'll take a look later when I try the build myself. Can you add files to the joblist by drag & drop?—

**Comment by andrecbarros** [comment]
Hi Robert,
No, I can't use dnd, it gives me the same error as when I try to add a file by menu/button (see the picture). I will, probably, enable debugging and check it out by weekend.
Regards,André
 
 

    On Tuesday, January 9, 2018 9:01 PM, Robert Kausch <notifications@github.com> wrote:
 

 mppenc/mppdec are the Musepack SV7 tools and are not supported by fre:ac. mpcenc/mpcdec are the newer Musepack SV8. Not a big issue if they are not available for now, though.I don't know about the gtk version. I used various versions of gtk 2 and 3 before and did not see any problems. I'll take a look later when I try the build myself. Can you add files to the joblist by drag & drop?—

**Comment by enzo1982** [comment]
The screenshot doesn't seem to get through when replying by mail. Can you upload it here directly?

**Comment by andrecbarros** [comment]
OK,

See below.

![screenshot_20180110_160045](https://user-images.githubusercontent.com/7326330/34794705-a6444352-f636-11e7-9271-8d89534aab07.png)

**Comment by andrecbarros** [comment]
OK,

I have installed all things under /usr (not /usr/local).

I may be wrong, but it seems to me that there is a couple of "/usr/local/lib*" hardwired on source code so, perhaps, this is the origin of the problem. fre:ac may be failing to load plugins and register file formats and, as so, may be unable to recognize file extensions. Does it sounds possible to you?

Regards,
André

**Comment by enzo1982** [comment]
OK, I know what's going on. The BoCA runtime is looking for components in '$(prefix)/lib/boca', but as your libdir is 'lib64' it will not find anything.

Please add this to the 'boca.spec' file to fix it:

`sed -i.orig runtime/common/utilities.cpp -e 's!/lib\(/boca\)!/'%{_lib}'\1!;'`

**Comment by andrecbarros** [comment]
Hey ! That did the trick !

Thank you, will be testing it on next days. If, for some misfortune, I hit something not working (can't be possible, it is software we are talking about! ;) ), I will let you know.

May you need translation to portuguese, I may help on that.

Regards,
André

**Comment by enzo1982** [comment]
If you would like to update the Portuguese translation for the latest alpha, go ahead! I'll appreciate it and will include the update in the next release.

You can use the translator utility included with smooth.

Thanks,
Robert

**Comment by andrecbarros** [comment]
OK, will take a look at it by weekend.

Regards,André 

    On Thursday, January 11, 2018 4:01 PM, Robert Kausch <notifications@github.com> wrote:
 

 If you would like to update the Portuguese translation for the latest alpha, go ahead! I'll appreciate it and will include the update in the next release.You can use the translator utility included with smooth.Thanks,
Robert—

**Comment by andrecbarros** [comment]
Robert,
There is an entry you used "Higher" as token, shouldn't be more appropriate to use "Upper" instead? (Lower-Upper, Lowest-Highest being the usual terms, like on lower case upper case).
I'm still fixing and translating things. I used the german xml as start point as it seems to be the most complete of all and migrated the messages from the older pt_BR xml.
I think it will be ready by Thursday.
Regards,André
 

    On Thursday, January 11, 2018 4:01 PM, Robert Kausch <notifications@github.com> wrote:
 

 If you would like to update the Portuguese translation for the latest alpha, go ahead! I'll appreciate it and will include the update in the next release.You can use the translator utility included with smooth.Thanks,
Robert—

**Comment by enzo1982** [comment]
Hi André,

Yes, the German translation is the most complete as that is my native language. But when you open an incomplete file in the translator app, it will show the missing entries too, provided that template.xml is found in the same directory.

"higher" is correct in this case as it refers to "higher than usual process priority". The corresponding option is currently available on Windows only, though, so you won't find it in your Linux build.

Thanks and best regards,
Robert

**Comment by andrecbarros** [comment]
Hi Robert,
Finished the translations. Man, you have scads of messages to show!
Well, anyway, if you allow me, I suggest to add an option on smooth-translation to export, to a text only file, all the translated messages. I used a small bash script to do it. Will make it easier to spellcheck using Libreoffice Writer or MS Word. Good translations -> greater professionalism.

Regards and best wishes,André
 

    On Tuesday, January 16, 2018 2:11 PM, Robert Kausch <notifications@github.com> wrote:
 

 Hi André,Yes, the German translation is the most complete as that is my native language. But when you open an incomplete file in the translator app, it will show the missing entries too, provided that template.xml is found in the same directory."higher" is correct in this case as it refers to "higher than usual process priority". The corresponding option is currently available on Windows only, though, so you won't find it in your Linux build.Thanks and best regards,
Robert—

**Comment by enzo1982** [comment]
Hi André,
Thanks alot for your work, but the file did not make it through to GitHub. You need to upload it here directly.
Good idea about the plain text export. I'll add it in a future release - probably with fre:ac 1.1 beta.
Thanks, Robert

**Comment by andrecbarros** [comment]
OK,
Opened a new issue and attached the file.
Regards,André
 

    On Wednesday, January 17, 2018 5:59 PM, Robert Kausch <notifications@github.com> wrote:
 

 Hi André,
Thanks alot for your work, but the file did not make it through to GitHub. You need to upload it here directly.
Good idea about the plain text export. I'll add it in a future release - probably with fre:ac 1.1 beta.
Thanks, Robert—
