### ISSUE TITLE
Chapters in MP4 container?

### ISSUE THREAD

**Issue by thw0rted** [enzo1982/freac#30]
In the [news archive on the site](https://www.freac.org/index.php/en/latest-news-mainmenu-2/15-archive/133-freac-20110409), I saw a note from ages ago about supporting chapter markers in MP4 audio.  I loaded a bunch of m4a files into the joblist, ticked the "single file" box, and selected the FAAC encoder.  The job ran fine, and the output file does have all the tracks joined into a single file, but as far as I can tell there are no chapter markers (according to VLC and MediaInfo).  Am I missing an option somewhere, or do I misunderstand the feature?  If I'm doing it wrong, is what I want possible?

**Comment by thw0rted** [comment]
I was using the release (1.0) version, the first download listed on the website.  I installed the alpha instead, and chapter writing seems to work very well.  Thank you!

It might be nice to have a brief description of the difference between the branches somewhere either in the README or on the downloads page of the main site.  From what I've seen, there's a ton of stuff in the alpha that isn't available in the release build, so maybe most users would do best to start off with the alpha?  (Is there a roadmap for when 1.1.x reaches release status?)

**Comment by enzo1982** [comment]
Yes, the alpha has a massive changelog compared to the 1.0 releases. It's listed in the Readme file: https://github.com/enzo1982/freac/blob/master/Readme#L129

I hope to be able to make a beta release soon - maybe in February. Once that is out, it will be the default download on the site.
