### ISSUE TITLE
Front covers seem corrupted during a convert

### ISSUE THREAD

**Issue by GooodFr** [enzo1982/freac#303]
Hello,

**Describe the bug**
When I convert AAC files in MP3 files, my player can't see front covers

**To Reproduce**
1. I have some AAC files
2. Before, I added all Front covers in those files with Mp3tag v3.14

3. Today, I would like to convert all my AAC file to MP3
I tried to do it with fre:ac v1.1.6

4. When I check my new files with Mp3tag, I see my covers in MP3 files
5. But I can't see them in my player (in my car)
Usually, my car work fine with MP3
In my car, I see all my covers on MP3, but not on all fre:ac conversions

**Expected behavior**
I expected to see covers in converted files

**Additional context**
I don't know if that can help :
With Mp3tag, I also tried to write covers.jpg, I see that sometime <title> become (title) on some file names.

Regards, and thank you so much for your work !

**Comment by enzo1982** [comment]
Difficult to tell what's going wrong here. One possibility is that fre:ac is writing ID3v2.4 tags and your car player does not support those (many devices support only ID3v2.3).

Please check the ID3v2 tag encoding setting on the Tags page in fre:ac's configuration dialog. It should be set to UTF-16LE. Setting it to UTF-16BE or UTF-8 will make fre:ac create ID3v2.4 tags.

Another possibility is that your AAC files have the _Subtitle_ tag field set. In that case, fre:ac will preserve that field during conversion and write it to the corresponding ID3v2 field. The subtitle field is available in ID3v2.4 only, though, so this will also trigger creation of the newer tag version. You can check the ID3v2 tag version with Mp3tag.

If that doesn't explain it, it would be great if you could provide an example file. Ideally one version created with fre:ac and one where you added the cover with Mp3tag and it's showing up on your car player.

If you cannot attach files here, you can send them to support@freac.org.
