### ISSUE TITLE
OGG libraries from aoTuV

### ISSUE THREAD

**Issue by LopenantMan** [enzo1982/freac#320]
**Is your feature request related to a problem? Please describe.**
Add the ability to switch between the Lancer and aoTuV libraries when converting to OGG.
https://ru.wikipedia.org/wiki/Vorbis#aoTuV

**Describe the solution you'd like**
Add the ability to switch between the Lancer and aoTuV libraries when converting to OGG.
https://ru.wikipedia.org/wiki/Vorbis#aoTuV

**Describe alternatives you've considered**
I used the official program with his libraries
https://www.rarewares.org/ogg-oggdropxpd.php

**Additional context**

**Comment by enzo1982** [comment]
fre:ac already uses the aoTuV version of Vorbis and the codec library makes uses of most of the Lancer optimizations as well.

The library used is this one with both, aoTuV and Lancer patches included: https://github.com/enzo1982/vorbis-aotuv-lancer/

I don't plan to add an option to use a non-aoTuV version of Vorbis, but if you want that, you can use the 32 bit version of fre:ac with the non-aoTuV Vorbis libraries offered by [RareWares](https://www.rarewares.org/ogg-libraries.php#vorbislibs-libvorbis). Just replace the Vorbis.dll and VorbisEnc.dll files included with fre:ac with the DLLs from RareWares.
