### ISSUE TITLE
Joint stereo forced

### ISSUE THREAD

**Issue by mverdier829** [enzo1982/freac#328]
**Describe the bug**
I try to encode with stereo. Wave ripped keep stereo. But vorbis and flac force joint stereo. Lame force joint stereo even if "stereo" option is selected. AAC keep stereo.

**To Reproduce**
Get a wave with stereo effects. Encode with vorbis, flac or lame (with stereo selected). Result in joint stereo.

**Expected behavior**
With vorbis and flac I don't know if there is stereo. But Lame has an option to keep stereo.

**System (please complete the following information)**
windows 10

**Comment by enzo1982** [comment]
What do you use to evaluate the results, i.e. to find out whether stereo or joint stereo was used?

I just checked to be sure and the _Stereo mode_ setting in fre:ac's LAME encoder settings does what it claims. When set to stereo, the created MP3 files do not use Joint Stereo. So I do not see a bug here.

Note that disabling joint stereo will result in lower quality output files (in case of CBR/ABR encoding) or larger files with no extra quality gain (in case of VBR encoding). So if you were judging the results by their perceived quality, expecting stereo to sound better than joint stereo, you will get it the wrong way around.

The FLAC settings in fre:ac also have an option to toggle joint stereo encoding. As FLAC is lossless, disabling joint stereo will not affect quality here, but only increase the resulting file size (by approximately 4% in my tests).

The AAC encoders in fre:ac should all use some form of joint stereo, but as far as I know it works a bit different for AAC compared to e.g. MP3.

Vorbis uses different forms of joint stereo depending on the quality setting and fre:ac does not offer a setting to configure this.

**Comment by mverdier829** [comment]
I use Pink Floyd "Wish you were here" which starts with a clear stereo effect : 1 guitar on right and 1 other on left. MP3 losses greatly but it is not the point. I check encoders to keep each guitar on its proper side.
I found flac parameter but I will not test it as the resulting file is very huge.
I confirm AAC keeps stereo effect but LAME does not even with stereo parameter checked. I mean it gets both right and left sounds but it mixes them and you hear them on both right and left.

**Comment by mverdier829** [comment]
I make another try with FLAC. I remove "stereo combinée" option which I leave on my first try. And all is good. Except size of FLAC file... So my playback is ok.
For LAME I set VBR level 2.0, stereo mode, expert with ATH on, audio processing all unchecked.

**Comment by enzo1982** [comment]
OK, like I explained above, disabling joint stereo for FLAC will result in bigger files. You should not be able to hear a difference between a FLAC with joint stereo enabled or disabled, though.

You LAME settings seem to be generally fine. Stereo or Joint Stereo mode should not make a big difference in quality with these settings, but Stereo files will be a bit larger.

If you think that LAME does not preserve stereo separation well at these settings, better report this to the LAME project directly as I will not be able to help with this. As I wrote before, I verified that fre:ac sets the stereo mode correctly when configuring the LAME encoder. So anything happening after that will not be a fre:ac issue. Therefore closing this issue.
