### ISSUE TITLE
no access to cd drive after upgrading FreeBSD 13.0 -> 13.1

### ISSUE THREAD

**Issue by amahling** [enzo1982/freac#332]
After upgrading my system from FreeBSD 13.0 to 13.1 freac fails to access the cd drive and throws a message

++ WARN: ioctl(fd, CDIOCALLOW) failed: Invalid argument

++ WARN: open: Inappropriate ioctl for device

Please see details in the freebsd bug report, which I've opened:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264709

**Comment by amahling** [comment]
Other applications for instance vlc can access cd drive and medium

**Comment by enzo1982** [comment]
Thank you for reporting this! I will look into it, but won't be home for a few more days, so I will get to it only later.

**Comment by amahling** [comment]
was a problem with the FreeBSD base system, issue is fixed in 13.1-p3
