### ISSUE TITLE
Use DATE entry from the .cue file

### ISSUE THREAD

**Issue by msdobrescu** [enzo1982/freac#336]
**Is your feature request related to a problem? Please describe.**
Splitting by .cue files does not use the DATE entry.
The directory will not contain the year in the name, if used, nor the files tags.

**Describe the solution you'd like**
The DATE should be read from the .cue file at least when missing in other media tags.

**Describe alternatives you've considered**
Must open the .cue file, check if DATE entry exists, copy that to a file in the jobs list and use it with all the files there by the drop down menu. A lot of steps.

**Additional context**

**Comment by msdobrescu** [comment]
Nice. A question would be, if it is already set in the media file (ape, flac, wv etc), should it be overridden or used that one?

**Comment by enzo1982** [comment]
Whether metadata from media files or cue sheets is preferred is configurable. In the config dialog go to _Components->Decoders->Cue Sheet Reader_. There you will find the option _Prefer cue sheet metadata over referenced files' tags_.

**Comment by msdobrescu** [comment]
Is it possible to see the year in the track list grid?

**Comment by enzo1982** [comment]
It wasn't, but I just published a new continuous build that adds a year column to the list on the _Interface->Joblist_ page of the config dialog. Please try that.

**Comment by enzo1982** [comment]
The changes are now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7). Closing this issue.
