### ISSUE TITLE
Request: --no-phase-inv using opus

### ISSUE THREAD

**Issue by 38github** [enzo1982/freac#337]
Opus-tools 0.2 introduced the option --no-phase-inv that really helps the sound when a stereo Opus file is downmixed to mono. Is this something that can be implemented as an option under the Opus codec?

Regards

**Comment by enzo1982** [comment]
Thank your for bringing this up. The option has been added is now available in the [continuous builds](https://github.com/enzo1982/freac/releases/tag/continuous).

**Comment by dok-prog** [comment]
Thank you very much for this. With bluetooth mono speakers being everywhere this option is very useful.
