### ISSUE TITLE
Add return codes to freaccmd for success and failure

### ISSUE THREAD

**Issue by mattaw** [enzo1982/freac#348]
**Is your feature request related to a problem? Please describe.**
Currently `freaccmd` does not return success or failure exit codes/numbers (return codes). When automating the conversion of my `.flac` archive to `.opus` for use on my cell phone it is difficult to detect any failures. (Fre:ac is the best program to convert files to opus and preserve the tags and album art I have found.)

**Describe the solution you'd like**
On success have `freaccmd` return `0` and on any failure return `-1`.

**Describe alternatives you've considered**
I have searched through `freaccmd`'s `stdout` for the string `done.` but it is much more error prone, and is not supported by most process runners by default. For example the Python [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run) has a `check=True` option which would automatically throw an `CalledProcessError` exception upon the process exiting with `!=0` code. The captured `stdout`, `stderr` and return code would be attributes on the Exception.

**Additional context**
The code here seems to be the relevant section, hopefully it would be a 5 minute task to change `void` to `int` and `return 0` (or -1). For multitrack encodes or rips perhaps setup `int success=1` and if any failure occurs flip to `-1`. That is the typical behavior for return codes as they are a blunt instrument. I have not done a PR as I have not yet setup the build environment to make freeac and test it.
https://github.com/enzo1982/freac/blob/659094dced4e1f1d06c1017db674915b2b1915ba/src/startconsole.cpp#L624-L655

**Comment by enzo1982** [comment]
Thank you for bringing this up!

Support for exit codes is added in commit bdcc3057. A new [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous) should be ready soon.

0 is returned after a successful run; a negative error code otherwise:

-1 for processing/conversion errors
-2 for invalid arguments
-3 for file(s) not found
-4 for CD ripping being requested while no drives are available

**Comment by mattaw** [comment]
Looks amazing, pulling the build to test right now. I had a look at the patchset, and boy was I wrong about how to implement that cleanly. Looks like define an int in a config struct in startconsole.h, and set that in the various functions that were already testing success to control what was printed on the command line. Return from the StartConsole function.

I am really impressed by the speed you developed the numbering schema and adapted it, or you could have just assigned a different negative number for each type of activity you had a function for.

Either way, thank you very much. Are you interested in a report if it goes well, or would you only prefer reports if it has some kind of bad behavior.

**Comment by enzo1982** [comment]
The change is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7). Closing this issue.

> Are you interested in a report if it goes well, or would you only prefer reports if it has some kind of bad behavior.

Sorry, missed this question back then. In general, I appreciate any feedback to changes/fixes. Otherwise I just assume that everything is working fine after the change.
