### ISSUE TITLE
Unchecking "Show tips on startup" does nothing

### ISSUE THREAD

**Issue by forrcaho** [enzo1982/freac#35]
Even when I uncheck the box, I still see a tip on the next startup.

**Comment by enzo1982** [comment]
fre:ac saves this setting in its configuration file. There were some issues with saving that file in the initial Flatpak package. So if you're running the Flatpak, please make sure you have the latest version (you can do a manual update by running `sudo flatpak update`).

Other than that, if fre:ac crashes for any reason, the settings - including whether to show the tips dialog - might not be saved. Could this be the cause of this problem?

I just double-checked that all Linux releases - Snap, Flatpak, AppImage and the plain .tar.gz package - actually don't show the tips dialog on the next startup after its been turned off. Everything looks good there, so it does not seem to be a general issue.

**Comment by forrcaho** [comment]
I had build from source, I _thought_ from the latest tagged version of freac and supporting libraries. I just rebuild everything from HEAD, and it's now working.

**Comment by enzo1982** [comment]
The 20181201a tagged release stored its configuration in ~/.freac. The current head now evaluates the XDG_CONFIG_HOME variable usually ending up with ~/.config/freac. Maybe this played a role here?
