### ISSUE TITLE
Tags lost, FLAC -> OPUS

### ISSUE THREAD

**Issue by EnArvy** [enzo1982/freac#368]
**Describe the bug**
When a flac file is converted to opus, the tags are lost. This does not happen when converting from flac to mp3.

**To Reproduce**
1. Select flac file to convert
2. Convert to opus
3. Original tags lost, such as Title, Album, Genre

**Screenshots**
![image](https://user-images.githubusercontent.com/70991883/188545001-48219130-d915-4d5e-917f-467ae915c12f.png)

**System (please complete the following information)**
 - OS: Windows 11

**Comment by enzo1982** [comment]
Windows Explorer does not support displaying Opus tags. Any reasonable audio player will display the tags, though.

Closing as invalid.

**Comment by MichalisSak** [comment]
Hello, although you are correct that the tags remain, it is just not visible by windows explorer or stock media player, I have noticed another problem.

When the artist or album artist tags have multiple names, with the conversion only the last one is kept.
Opening the files in mp3tag I get for example in flac a\\b and in opus it is just b, if it is a\\b\\c in flac, I get only c in opus and so on and so forth.
Is there a setting I am missing or is it a bug?
