### ISSUE TITLE
Add metadata support for all supported file formats (including Opus, etc)

### ISSUE THREAD

**Issue by dbolton** [enzo1982/freac#379]
**Is your feature request related to a problem? Please describe.**
Currently if you export to any of the following formats, it does not save any metadata (such as track title, album name, artist, CD covers, etc.)

- Monkey's Audio Encoder
- Musepack Audio Encoder
- Ogg Vorbis Encoder
- OptimFROG Lossless Encoder
- Opus Audio Encoder v1.3.1
- Speex Speech Encoder v1.2.0
- Tom's Audiokompressor
- WavPack Audio Encoder

**Describe the solution you'd like**
Ideally fre:ac would save metadata for all the included encoders. However, in terms of priority, I would rank Opus format as the most important of the formats (as successor to both Ogg Vorbis and Speex).

**Describe alternatives you've considered**
I've found some FLAC to Opus web-based converters and some command line converters, but neither option are as convenient as fre:ac would be with this built in. 

**Additional context**
I've tested converting opus (and the other formats listed above) in version 1.1.6, 1.1.5 and 1.1 (the first version to introduced most of these formats). This limitation appears to be present in all version of fre:ac.

**Comment by enzo1982** [comment]
fre:ac does of course write metadata to all of those formats - unless you explicitly disable metadata writing.

How did you check whether metadata has been written to your output files? There was a user reporting a similar issue in #368 who was looking at the file information in Windows Explorer. That of course does not work as Windows Explorer does not support reading metadata from these formats.

Instead, please open the converted files in fre:ac or foobar2000 to see the attached metadata.

To check whether metadata writing is enabled, open the _Tags_ page of the configuration dialog and make sure the relevant formats are enabled. The metadata formats relevant for the file formats you mentioned are:

- APEv2 (for Monkey's Audio, Musepack, WavPack, OptimFROG and Tom's Audio)
- Vorbis Comment (for Ogg Vorbis, Opus and Speex)

**Comment by dbolton** [comment]
My mistake. I was misled by partial support for the audio file both the apps I was using to test: 

- Window's default music app Groove plays an opus file if you open it, but doesn't display the meta data.
- Android's Metro music app seems to support the opus file but perhaps has some delays in displaying all the meta data--particularly cover art. 

I opened in foobar2000 as you suggested and everything was working there.

**Comment by enzo1982** [comment]
Great! Thank you for reporting back!
