### ISSUE TITLE
Letter 'ö' in artist name renders as '^' in m3u playlist file making the latter unreadable in Music app (macOS).

### ISSUE THREAD

**Issue by BeneThien** [enzo1982/freac#386]
Letter 'ö' in artist name renders as '^' in m3u playlist file making the latter unreadable in Music app (macOS).

Fre:ac generated following m3u playlist file content for Björk's Homogenic album CD:

Begin of file content
#EXTM3U
#EXTINF:255,Bjˆrk - Hunter
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/01 - Bjˆrk - Hunter.mp3
#EXTINF:305,Bjˆrk - JÛga
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/02 - Bjˆrk - JÛga.mp3
#EXTINF:202,Bjˆrk - Unravel
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/03 - Bjˆrk - Unravel.mp3
#EXTINF:313,Bjˆrk - Bachelorette
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/04 - Bjˆrk - Bachelorette.mp3
#EXTINF:353,Bjˆrk - All Neon Like
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/05 - Bjˆrk - All Neon Like.mp3
#EXTINF:269,Bjˆrk - Five Years
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/06 - Bjˆrk - Five Years.mp3
#EXTINF:186,Bjˆrk - Immature
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/07 - Bjˆrk - Immature.mp3
#EXTINF:260,Bjˆrk - Alarm Call
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/08 - Bjˆrk - Alarm Call.mp3
#EXTINF:199,Bjˆrk - Pluto
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/09 - Bjˆrk - Pluto.mp3
#EXTINF:273,Bjˆrk - All Is Full Of Love
Bjˆrk - Homogenic - (1997) - (Art Pop, electronic)/10 - Bjˆrk - All Is Full Of Love.mp3
End of file content

The second track title of the album Jóga is rendered as JÛga which is also problematic.
In the file naming of the m3u file the original letters are preserved. Also in the file naming of the generated mp3 files the original letters are preserved.

Ask if you need more info. Hope this is of any help.

**Comment by enzo1982** [comment]
The .m3u format uses 8 bit characters which need to be interpreted in the same encoding by the writing and reading application.

fre:ac traditionally uses ISO-8859-1 as the encoding of .m3u files. Apple Music, on the other hand, seems to interpret the files in the MacRoman encoding. ISO-8859-1 has ó and ö at the codepoints where MacRoman has Û and ˆ.

I will consider changing the way fre:ac writes .m3u files to use the current system encoding. That way, the files would be written in CP1252 (mostly compatible with ISO-8859-1) on Windows computers configured to a Western European language, and as MacRoman on Macs. Naturally, such files would not be interchangeable between Windows and Mac systems anymore then.

For best compatibility, configure fre:ac to create .m3u8 playlists (called _M3U Playlist (Unicode)_ in fre:ac). Those use the UTF-8 Unicode encoding and can represent tens of thousands of international characters in an interchangeable format. I'm not sure whether Apple Music supports .m3u8, though.
