### ISSUE TITLE
Error while opening CUE file with cyrillic names

### ISSUE THREAD

**Issue by sapozhnikov** [enzo1982/freac#39]
I'm using freac-1.1-alpha-20190423-x64, Windows 7 x64. While trying to open CUE file got this error:
"File referenced in cue sheet not found"
File contains ANSI codepage (1251). Trying to save it as UTF-8, still no luck. It opens without issues with Foobar2000 and Xrecode3.

[t.A.T.u. - Я сошла с ума.cue.zip](https://github.com/enzo1982/freac/files/3268868/t.A.T.u.-.cue.zip)

**Comment by enzo1982** [comment]
I made a new version that should be able to handle cue sheets in system encoding, i.e. you should be able to open a CP1251 cue sheet on a Russian computer: https://freac.org/updates/freac-1.1-alpha-20190610-windows-x64.zip

Please try if this works for you.

Converting the cue sheet to UTF-8 would be better. fre:ac needs a BOM (byte order mark) in UTF-8 cue sheets though. Most text editors have an option to save UTF-8 with or without BOM.

**Comment by sapozhnikov** [comment]
Thank you for the quick fix. Is it only for the Russian Windows? I think something like MultiByteToWideChar(CP_ACP, ....) will be universal solution.
freac-1.1-alpha-20190610-windows-x64 opens CUE file, but shows garbage at GUI (attachment).
CUE converted fo UTF-8 without BOM still shows error from 1st message.
CUE with BOM opens without issues and GUI shows everything correctly.
![freac_tatu](https://user-images.githubusercontent.com/10401818/59218069-04b1ec00-8bc8-11e9-993d-33d3c8e08595.png)

**Comment by giodot** [comment]
I'm still getting this error message with Cyrilic cue sheets in fre:ac 1.1.1 on macOS 10.15.6

**Comment by enzo1982** [comment]
Last year's patch only applies on Windows. It works by falling back to the system codepage when files referenced in the cue sheet are not found according to the UTF-8 or ISO-8859-1 encoding. On macOS, however, the system codepage usually is UTF-8 nowadays, so this fallback will have no effect.

The other issue with fre:ac's cue sheet support, however, is that it does not support UTF-8 encoding without a BOM. Support for this will be added in the next update.

So if your cue sheet is encoded in UTF-8 without BOM, it should work with the upcoming fre:ac 1.1.3 update. If it is in a different encoding like ANSI CP1251 or KOI8-RU, though, it will still not work on macOS.

**Comment by enzo1982** [comment]
fre:ac 1.1.3 is available now and adds support for UTF-8 cue sheets without a BOM.

This should greatly improve compatibility with cue sheets created by various applications, so I'm closing this issue now. Please add comments if there still are issues.
