### ISSUE TITLE
When no disc number is available use 1 instead of 0

### ISSUE THREAD

**Issue by GrumpusGiteous** [enzo1982/freac#391]
**Is your feature request related to a problem? Please describe.**
Using <disc> in path creation adds 0 if it's only 1 cd, I assume because the tag is empty.

**Describe the solution you'd like**
If <disc> contains 0 change it to 1

**Comment by enzo1982** [comment]
Yes, makes sense. Changed in b247c78. New continuous builds should be ready soon.

**Comment by enzo1982** [comment]
The chage is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7). Closing this issue.
