### ISSUE TITLE
Display AccurateRip Existence (Before Rip)

### ISSUE THREAD

**Issue by joshstoik1** [enzo1982/freac#398]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be helpful to have some sort of visual indication, or way of checking, whether or not a given disc exists in the AccurateRip database prior to ripping, that way rip settings could be adjusted accordingly. (I prefer slow rips when there's nothing to compare the result with.)

**Describe alternatives you've considered**
This could take the form of an icon (e.g. colored yes, greyed no), a text field displaying the ID, or some sort of button to launch an actual lookup action.

**Additional context**
N/A

**Comment by enzo1982** [comment]
[fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7) has been released an includes a new option for AccurateRip to show a notification when a newly inserted disc is not found in the database.

**Comment by joshstoik1** [comment]
Thanks @enzo1982! That's perfect.
