### ISSUE TITLE
CDTOC (Tag) Track Count

### ISSUE THREAD

**Issue by joshstoik1** [enzo1982/freac#399]
**Describe the bug**
The track count in the first part of the `CDTOC` metadata tag should (probably) reflect the total number of _audio_ tracks, i.e. exclude any data tracks. Otherwise it is impossible to know after the fact — at least without consulting other tags like `TRACKTOTAL` — whether or not a data session was present.

This distinction is of particular relevance for services like MusicBrainz and CTDB, which factor the absence or presence of data sessions into their ID calculations.

**To Reproduce**
Rip a CD with a data session.

**Expected behavior**
The total should only count the number of audio tracks.

**Screenshots**
N/A

**System (please complete the following information)**
 - OS: Ubuntu 22.10
 - CPU: Intel Core i7-10610U
 - RAM: 16GiB

**Additional context**
There isn't an RFC or anything, so this is more of a "bug" than a _bug_, but it would be helpful to maintain compatibility with programs like CUETools and dBpoweramp.

Spoon has a nice write-up on the formatting [here](https://forum.dbpoweramp.com/showthread.php?16705-FLAC-amp-Ogg-Vorbis-Storage-of-CDTOC&s=3ca0c65ee58fc45489103bb1c39bfac0&p=76686&viewfull=1#post76686).

**Comment by enzo1982** [comment]
Indeed, the number of tracks should count only the audio tracks. Fixed with enzo1982/BoCA@fa5a24b and reflected in the latest [continuous build](https://github.com/enzo1982/freac/releases/continuous).

**Comment by joshstoik1** [comment]
Thanks @enzo1982! I ripped a data CD using the continuous version and the CDTOC showed the correct track count.
