### ISSUE TITLE
No Folders

### ISSUE THREAD

**Issue by stgallen11** [enzo1982/freac#405]
How can I prevent a folder from being created from each track? I only want the songs...

**Comment by enzo1982** [comment]
Check the _Output filename pattern_ setting in the configuration dialog.

To prevent creating a folder for each album, remove the part before the slash or backslash. You can also replace the whole pattern with `<filename>` to instruct fre:ac to keep the source file name.

You can find more information about output filename pattern placeholders here: https://freac.org/manual/en/howto.html#anchor_pat
