### ISSUE TITLE
Add album images

### ISSUE THREAD

**Issue by jo99jo** [enzo1982/freac#417]
EAC allows for the adding of an album image when a CD is being processed.  Why can't fre:ac do this also?

**Comment by enzo1982** [comment]
fre:ac currently supports only the CDDB database which does not include album images.

I plan to add support for the MusicBrainz database after the fre:ac 1.1.7 release, though. MusicBrainz links to Cover Art Archive which will then be used to automatically find album art when loading a CD.

**Comment by jo99jo** [comment]
> fre:ac currently supports only the CDDB database which does not include album images.
> 
> I plan to add support for the MusicBrainz database after the fre:ac 1.1.7 release, though. MusicBrainz links to Cover Art Archive which will then be used to automatically find album art when loading a CD.

That should be helpful.  But even with the cover art from MusicBraiz, it only offers the front cover.  If I want the rear, liner notes, CD image, etc. I have to do a search on Google and look at Discogs.

**Comment by enzo1982** [comment]
Cover Art Archive also contains back covers, booklets and CD images for a lot of CDs.

But anyway, MusicBrainz and Cover Art Archive are only the first step. The new metadata engine will be modular and it will be possible to add support for Discogs later. Adding a module that performs an online search and lets you select covers to add will be possible too.

**Comment by jo99jo** [comment]
Sounds good!  I mention Discogs because they have a lot images for most albums but they are not alone.  There are numerous others.

**Comment by RJVB** [comment]
> I plan to add support for the MusicBrainz database after the fre:ac 1.1.7 release, though. MusicBrainz links to Cover Art Archive which will then be used to automatically find album art when loading a CD.


Good news - any updates on this?

I find that MusicBrainz is often more accurate/complete (though it has a weird habit of putting the composer in the artist tag, which isn't completely wrong but still quite unusual :) )
