### ISSUE TITLE
fre:ac crashes when requesting CD metadata

### ISSUE THREAD

**Issue by philmikejones** [enzo1982/freac#42]
**Describe the bug**
Fre:ac crashes when I try to Add Audio CD contents to the joblist (the crash actually happens when freac tries to query the CDDB).

Output from running freac from terminal (there's not a lot to go on):

```
/snap/freac/247/bin/desktop-launch: line 344: cannot create temp file for here-document: No such file or directory
Segmentation fault (core dumped)
```

**To Reproduce**
1. Click on 'Add Audio CD contents to the joblist'
2. Crashes when freac tries to query the CDDB

**Expected behavior**
Not crash! :)

**System (please complete the following information)**
 - OS: Xubuntu 18.04 Bionic
 - CPU: Intel Core i5
 - RAM: 16GB

**Additional context**
I'm using the `--beta` snap version of freac

Happy to include any other logs/information if you tell me where to look!
Thanks

**Comment by enzo1982** [comment]
Thank you for reporting this and sorry for responding only now!

This was an issue I already knew for some time and I was working on a solution in summer. Well, that took longer than expected, but finally landed in the repository a few weeks ago.

Could you try the continuous build available here under [Releases](https://github.com/enzo1982/freac/releases/tag/continuous) or the `--edge` snap?

**Comment by philmikejones** [comment]
Thanks for looking into this. I've tried the `--edge` build and that does seem to work. I'll close the ticket but I'll keep testing and re-open if necessary.

Thanks
