### ISSUE TITLE
Lack of easy access help

### ISSUE THREAD

**Issue by jo99jo** [enzo1982/freac#420]
There are many choices in the Options dialogs and I have no idea what many of them do.  No one really wants to plow through some document describing what these options are.

Is it possible for you to implement pop-up help when someone mouses over an option choice?  This of course does not have to be a deep in-depth explanation (that is what the help document might be for) but a one sentence short help of what the option does.

**Comment by enzo1982** [comment]
The framework supports tooltips on UI controls, so this would be possible. However, it would be a lot of work to come up with helpful short explanations for hundreds of options and it would create more work for translators and make it more difficult to keep everything updated when an option changes.

If someone came up with the initial strings, a patch to add the tooltips to the respective controls and volunteered to keep this updated in the long run, I would consider integrating it.

But without anyone stepping up for this, the initial work would probably take me weeks and the maintenance work this would incur in the long run would be too much for me to handle.

**Comment by jo99jo** [comment]
OK, I can see that this would be a lot of work.
