### ISSUE TITLE
Freac unable to connect to freedb server

### ISSUE THREAD

**Issue by FrancoiseJolibois** [enzo1982/freac#433]
**Describe the bug**
Freac unable to connect to freedb server . I receive the following message:"Some errors occured trying to connect to freedb server. ..."

**To Reproduce**
Happens each time since this morning while it was working well previously.

**Expected behavior**
Well, I expecetd to happen that Freeac would connect to the server and find the details of the tracks as usual!

**Screenshots**
![image](https://user-images.githubusercontent.com/124233679/216239379-dfdb6f26-f6dc-491e-afee-2783df3c3d18.png)

**System (please complete the following information)**
 - OS: 19044.2486, window 10 pro
 - CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz
 - RAM: 16.0 GB (15.8 GB usable)

**Additional context**
Nope

**Comment by ohquait** [comment]
you know : freedb has died ?
you have to use in configuretion:
e.g.
CDDB-Server:   gnudb.gnudb.org

Hope this help

**Comment by enzo1982** [comment]
@ohquait, fre:ac already uses GnuDb by default. And it automatically switches freedb.freedb.org to gnudb.gnudb.org when updating from an older version.

The GnuDb server probably was down or unreachable for some time. That can happen, as with any service on the internet. Also, GnuDb is not associated with the fre:ac project, so I cannot do anything to fix it when it goes down.

Right now it's working fine for me and as it has been working for @FrancoiseJolibois before, this doesn't look like a bug in fre:ac.

**Comment by FrancoiseJolibois** [comment]
Thank you Envoyé depuis l'application Mail Orange----------------De: "Robert Kausch" ***@***.***>Envoyé: lundi, 20 février 2023, 4:00À: "enzo1982/freac" ***@***.***>Cc: "FrancoiseJolibois" ***@***.***>;"Mention" ***@***.***>Objet: Re: [enzo1982/freac] Freac unable to connect to freedb server (Issue #433)   
Closed #433 as completed.
