### ISSUE TITLE
Metadata not parsed

### ISSUE THREAD

**Issue by 2m** [enzo1982/freac#45]
**Describe the bug**
Metadata from this CD (https://musicbrainz.org/cdtoc/XUzOviz7drJxdEGCgjaYBRGv6k8-) is not parsed successfully.

![metadata](https://user-images.githubusercontent.com/422086/62830952-16dbf500-bc20-11e9-9718-2515da00c69f.png)

However other tools, like CUETools can successfully parse it.

How can I provide more information from this CD to help you to fix it?

**Comment by enzo1982** [comment]
fre:ac uses the freedb CD database, not MusicBrainz (however, adding support for MusicBrainz is planned for after the 1.1 release).

freedb does not have an entry for this CD (you can search the database at http://www.freedb.org/freedb_search.php).

You can create or update information for CDs using _Database->Submit CDDB data_ (or the fifth toolbar button).

**Comment by 2m** [comment]
I see. I thought this information was being read from the CD itself, without querying databases.

**Comment by enzo1982** [comment]
Only if the CD has CD-Text, which is usually found on Sony releases only.
