### ISSUE TITLE
Fre:ac 1.1.6 not maintaining WMA 9.2 codec format setting

### ISSUE THREAD

**Issue by john-iv** [enzo1982/freac#451]
Alterations to the Quality dropdown for the WMA 9.2 codec are not sticking.

**To Reproduce**
1.	Launch Fre:ac.
2.	Go to Options / General Settings / Default Config.
3.	Encoder to Windows Media Audio Encoder.
4.	Configure Encoder.
5.	Chose Windows Media Audio 9.2.
6.	Select use format: And choose VBR Quality 50, 44kHz, stereo VBR
7.	Press OK.
8.	Return to the same spot as 2 and repeat.  Note that it is now the VBR Quality 98.

**Expected behavior**
Remain at VBR Quality 50 as set.

**System (please complete the following information)**
 - OS: Win11 x64 
 - CPU: i7-12700K
 - RAM: 64GB DDR5

**Additional context**
Happens in portable 1.1.6 and Windows Store version. Happens from general settings menu or in-UI yellow config. button.

![image](https://user-images.githubusercontent.com/9202235/221737764-72638770-94ec-425a-8e2d-bd7a079ddc34.png)

![image](https://user-images.githubusercontent.com/9202235/221737799-ae546900-39ea-493d-8be8-a25f39e82d68.png)

**Comment by john-iv** [comment]
Where does Fre:ac store this information? Maybe I can manually set it as a workaround.

**Comment by enzo1982** [comment]
This is a known issue with fre:ac 1.1.6 and is already fixed in the [continuous builds](https://github.com/enzo1982/freac/releases/tag/continuous).

Fixed with enzo1982/BoCA@18f4ca168.

**Comment by john-iv** [comment]
Thank you, closing as fixed in master.
