### ISSUE TITLE
fre:ac on Ubuntu 22.10 can not open mp3 files

### ISSUE THREAD

**Issue by marp188** [enzo1982/freac#456]
**Describe the bug**
fre:ac vers. 1.1.7 (snap) installed on Ubuntu 22.10.
Loading any .mp3 file results in error - "Unknown file type" 
Same .mp3 file loaded in any other audio player (like vlc) shows no problem

**To Reproduce**
1. Open fre:ac
2. Load any .mp3 file
3. Errors windows opens. Unable to open nnnn.mp3 - rreason unknown file type

**System (please complete the following information)**
 - Ubuntu 22.10
 - CPU: Intel Core i5
 - RAM: 8 GB

**Comment by enzo1982** [comment]
Thank you for reporting this!

The mpg123 library used for decoding MP3 files was missing from the Snap.

The Snap has been updated and the issue should be fixed.
