### ISSUE TITLE
[Question] Where are the logs stored?

### ISSUE THREAD

**Issue by collectorgeneral** [enzo1982/freac#47]
Using the freac continuous appimage: where are the logs stored (if any)?
Context: I have observed some random behaviour where freac would randomly stop working, resizing the GUI makes it go whacky. I am trying to debug it but I cannot get any logs from it. My system setup: Arch Linux (5.2.11 Zen Kernel), KDE Plasma DE.

**Comment by enzo1982** [comment]
Thank you for reporting this!

There are no logs with information about window management or drawing. You might get some console output from the X server when running fre:ac from the terminal.

Can you elaborate on what exactly is happening and how to trigger it? Like does a conversion have to be running to make this happen? Does the UI rendering become broken or does the program freeze?

**Comment by collectorgeneral** [comment]
@enzo1982 Its been inconsistent but roughly this is what happens:

- Added a bunch of flacs to convert to mp3s.
- Hit convert and wait for things to convert.
- Sometime along the conversion, suddenly, the progress bars will freeze. 

At the last point, doing anything with the window will cause it to go weird (buttons get clipped, elements do not resize properly, etc.). That was the first thing I did: run the freac appimage on terminal to see if I find anything (`./freac-continuous-linux-x86_64.AppImage`), but absolutely nothing gets printed out, which I thought was odd (maybe `stdout` and `stderr` are redirected somewhere?). At this point, the only way to stop the process is to `killall -9 freac`. After this, the only thing that is displayed on terminal is that the process was killed. There is absolutely nothing else that is giving me any indication of where the problem is.

**Comment by enzo1982** [comment]
Sounds like a UI deadlock.

I think this may have been caused by [this commit](https://github.com/enzo1982/smooth/commit/6f8ce4638a0e5fa224568777a2d44b2469558aef#diff-21b537dc67014a11dfc5f3b2ba7e15d3) in the smooth class library. At least I found it to be causing deadlocks for me on macOS.

It is fixed by fre:ac commit ac7f840. I would be great if you could try today's continuous build to see if it fixes the Linux issue for you.

**Comment by collectorgeneral** [comment]
So far no hangs. So it appears that the changes might have solved the issue. I will keep an eye out just in case.
I will close the issue for now. Thanks!
