### ISSUE TITLE
Encoding Autobooks with >100 Chapters

### ISSUE THREAD

**Issue by theanimal666** [enzo1982/freac#5]
When encoding audio books with more then 100 chapters the tracks are numbered: 01, 02 .. 10, 11, ... 100, 101 which breaks sorting on non-tag aware players that use the filename to order the tracks. 

Is there any possibility to configure that behavior which i simply did not find yet? 

thx & kind regards,
Chris

**Comment by enzo1982** [comment]
Hi Chris,

With the fre:ac 1.1 alpha release, you can use <track(3)> in the output filename pattern to create three-digit track numbers.

Robert

**Comment by theanimal666** [comment]
Cool, and thanks a lot for all the great work and time you spend for providing that great app.
