### ISSUE TITLE
No menu to edit multiple tags. 

### ISSUE THREAD

**Issue by hawkiboy** [enzo1982/freac#536]
There does not seem to be any way to edit multiple tags. 

1. read a CD in. 
2. Click on artist
3. No small menu appears that allows applying change to all tracks.

other posts have described a menu button that is supposed to appear. I see nothing.

 - OS: macOS Monterey 12.6
 - CPU: [e.g. m1
 - RAM: [e.g. 16GB]

Version 1.1.7

**Comment by Lee-Carre** [comment]
Fre:AC has a tag-editing tab (you may need to toggle a configuration variable, to enable it).

Changes made in the `Album` sub-tab (eg to the `artist` field) will apply to all tracks.
