### ISSUE TITLE
Log file: "total duration" figure loses the hours. 

### ISSUE THREAD

**Issue by pblitz-github** [enzo1982/freac#577]
Frea:ac ver 1.1.7 on Win 10

Converting .wav files to .m4a

The tail of a recent log file looks like this:

01:26:26.612 Finished converting: 23-01-01.wav
01:26:26.612 Duration: 00:38.520 (101.2x speed)
01:26:26.614
01:26:26.654 Total duration: 26:26.600 (215.5x speed)
01:26:26.655 Conversion process finished.

So, the timestamp clearly shows the elapsed time as being "01:26:26.655", but the "Total duration: 26:26.600" seems to be an hour short! I've seen this on other occasions where time > 1hour.  Not a biggie, but thought it was worth mentioning.

**System (please complete the following information)**
 - OS: Win 10 64bit
 - CPU: ntel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
 - RAM: 8 GB

**Comment by enzo1982** [comment]
Thank you for reporting this! This is now fixed in the latest [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous).
