### ISSUE TITLE
ConvertTicksToTimestamp(ticks)

### ISSUE THREAD

**Issue by ohquait** [enzo1982/freac#598]
**Describe the bug**
compilation breaks on host linux

**To Reproduce**
3. g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/engine/worker.cpp -o objects/engine_worker.o
src/engine/worker.cpp: In member function ‘smooth::Void freac::ConvertWorker::LogConversionEnd(const smooth::String&, smooth::Int64, smooth::UnsignedInt32, const smooth::String&, const smooth::String&)’:
src/engine/worker.cpp:800:62: error: ‘ConvertTicksToTimestamp’ is not a member of ‘BoCA::Utilities’
  800 |                 String           duration = BoCA::Utilities::ConvertTicksToTimestamp(ticks);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:313: objects/engine_worker.o] Error 1
make: *** Waiting for unfinished jobs....
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/gui/edit_folder.cpp -o objects/edit_folder.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/engine/encoder.cpp -o objects/engine_encoder.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/engine/worker_singlefile.cpp -o objects/engine_worker_singlefile.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/gui/layer_tooltip.cpp -o objects/layer_tooltip.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/jobs/joblist/addfolders.cpp -o objects/job_addfolders.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/gui/main_threads.cpp -o objects/main_threads.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/gui/playback.cpp -o objects/playback.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/jobs/joblist/removedisc.cpp -o objects/job_removedisc.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/jobs/joblist/addtracks.cpp -o objects/job_addtracks.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/jobs/joblist/removeall.cpp -o objects/job_removeall.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/dialogs/splitter.cpp -o objects/splitter.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/jobs/engine/convert.cpp -o objects/job_convert.o
src/jobs/engine/convert.cpp: In member function ‘virtual smooth::Errors::Error freac::JobConvert::Perform()’:
src/jobs/engine/convert.cpp:1334:62: error: ‘ConvertTicksToTimestamp’ is not a member of ‘BoCA::Utilities’
 1334 |                 String           duration = BoCA::Utilities::ConvertTicksToTimestamp(ticks);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:322: objects/job_convert.o] Error 1
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/jobs/joblist/addfiles.cpp -o objects/job_addfiles.o
g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/gui/main_joblist.cpp -o objects/main_joblist.o
error: Bad exit status from /home/quait/src/tmp/rpm-tmp.PTYVq2 (%build)

**Expected behavior**

**Screenshots**

**System (please complete the following information)**
System:
  Kernel: 6.6.20-pclos1 arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: PCLinuxOS 2024
Machine:
  Type: Desktop System: Gigabyte product: B450 AORUS PRO v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: B450 AORUS PRO-CF serial: <superuser required>
    UEFI: American Megatrends LLC. v: F63 date: 01/31/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 PRO 4750G with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 4 MiB
  Speed (MHz): avg: 562 min/max: 400/4454 cores: 1: 400 2: 400 3: 400 4: 400
    5: 400 6: 400 7: 400 8: 400 9: 400 10: 400 11: 400 12: 400 13: 400 14: 400
    15: 2994 16: 400
Graphics:
  Device-1: AMD Renoir driver: amdgpu v: kernel
  Display: server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: amdgpu,v4l dri: radeonsi gpu: amdgpu resolution: 3840x2160~60Hz
  API: OpenGL v: 4.6 vendor: amd mesa v: 24.0.2 renderer: AMD Radeon
    Graphics (radeonsi renoir LLVM 15.0.6 DRM 3.54 6.6.20-pclos1)
  API: Vulkan v: 1.3.231 drivers: radv,llvmpipe surfaces: xcb,xlib
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel
  Device-2: AMD Family 17h/19h HD Audio driver: snd_hda_intel
  API: ALSA v: k6.6.20-pclos1 status: kernel-api
  Server-1: PipeWire v: 1.1.0 status: active
...
Info:
  Memory: total: N/A available: 29.26 GiB used: 3.53 GiB (12.1%)
  Processes: 414 Uptime: 1h 27m Shell: Bash inxi: 3.3.33

**Additional context**

I not knowing .... can be a miss in code or ...

**Comment by ohquait** [comment]
freac - 1.1.7  git-update in local source on Mon Mar 04 2024 build breaks !

make
....
`g++ -I"/home/quait/src/rpm/BUILD/freac-1.1.7"/include -fvisibility=hidden -c -fPIC -pthread -I/usr/include  src/engine/worker.cpp -o objects/engine_worker.o
src/engine/worker.cpp: In member function ‘smooth::Void freac::ConvertWorker::LogConversionEnd(const smooth::String&, smooth::Int64, smooth::UnsignedInt32, const smooth::String&, const smooth::String&)’:
src/engine/worker.cpp:800:62: error: ‘ConvertTicksToTimestamp’ is not a member of ‘BoCA::Utilities’
  800 |                 String           duration = BoCA::Utilities::ConvertTicksToTimestamp(ticks);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:313: objects/engine_worker.o] Error 1
error: Bad exit status from /home/quait/src/tmp/rpm-tmp.LiUknZ (%build)`

Smooth - 0.9.10  git-update in local source on Mon Mar 04 2024 build OKAY!
BoCA - 1.0.7  git-update in local source on Mon Mar 04 2024 build OKAY!

Can it be -fPIC is not good for , can i disable it ?

**Comment by enzo1982** [comment]
You are trying to build current fre:ac git sources against an older state of BoCA. To build the current fre:ac git sources you also need up to date BoCA sources.

`BoCA::Utilities::ConvertTicksToTimestamp()` was added to BoCA in [this commit](https://github.com/enzo1982/BoCA/commit/190223e80fb871ca3a50e7482dc5fec198331637) on Feb 18.

**Comment by ohquait** [comment]
Big THANK YOU!
solved
