### ISSUE TITLE
freac-1.1-alpha-20180306-linux crashes when selecting a cd to rip

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#6]
i am using fre:ac to rip from multiple (4) cd drives.
sometimes when i try to select a cd drive to import the tracks,fre:ac crashes.
OS: Linux Mint 18.3

Here are some traces when it happens

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x0
  Serial number of failed request:  7766
  Current serial number in output stream:  7767

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x0
  Serial number of failed request:  7386
  Current serial number in output stream:  7387

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x0
  Serial number of failed request:  7598
  Current serial number in output stream:  7598

**Comment by enzo1982** [comment]
One note for reproducing the original issue. The problem only occurs when the CDDB query window comes up and goes away quickly. To reproduce it more easily, follow these steps:

1. Disable the CDDB cache in the database menu to perform new queries even on already known discs.
2. Use a local freedb copy and configure local CDDB access in the configuration dialog to speed up queries.

**Comment by wkremser** [comment]
yes nr 2. is my setting .. using a local freedb copy and to make it even quicker use a version where every disc i am going to rip is only in it once.

so first i am identifying my 4 cds, edit the freedb entries and copy the text files in a directory which is configured as local freedb database for fre:ac

**Comment by wkremser** [comment]
after using the newly compiled smooth library for the last few days, no more crashes happened on my side.
i think we can close this issue :)

**Comment by enzo1982** [comment]
Great! Thanks!
