### ISSUE TITLE
Flatpak update issue

### ISSUE THREAD

**Issue by Miccio-AN** [enzo1982/freac#637]
Starting today, doing the update on Flatpak I receive the following warning:

Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   org.freac.freac

Info: runtime org.freedesktop.Platform.GL.default branch 22.08-extra is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.freac.freac

Info: runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.freac.freac

Thanks for your great software!

Otello

**Comment by autofire372** [comment]
This is not strictly fre:ac's fault; a library it depends on has been declared EoL by flatpak.

It might be a sign that fre:ac is overdue for a new release. It HAS been more than a year since 1.1.7. dropped...

**Comment by Miccio-AN** [comment]
Do you know approximately when the next release is scheduled?
Thanks!

**Comment by alp-km** [comment]
Same issue - can't update freedesktop-sdk to 22.08.26.

**Comment by enzo1982** [comment]
Thanks for reporting this! fre:ac's Flatpak packages have now been updated to use the new 24.08 runtime.
