### ISSUE TITLE
Update Opus 1.5.2

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [enzo1982/freac#643]
Freac 1.1.7 comes with OPUS 1.3.1

On September 11th, 2024 OPUS 1.5.2 has been released:
https://github.com/xiph/opus/releases

Please update OPUS.

**Comment by mven** [comment]
It appears Opus is already at 1.5.2 with https://github.com/enzo1982/freac/commit/f92b06572ae55af759ae072fddfa57d16f6632f0

**Comment by NewKidOnTheBlock** [comment]
Nevermind then.
Looking forward to Freac 1.1.8
