### ISSUE TITLE
[REQ] Monkeys Audio v10.80

### ISSUE THREAD

**Issue by Barough** [enzo1982/freac#651]
https://monkeysaudio.com/versionhistory.html
https://monkeysaudio.com/files/

**Comment by enzo1982** [comment]
There are no relevant changes in Monkey's Audio v10.80 (and v10.81 released today) compared to v10.76 already in fre:ac continuous builds. Files created by v10.81 would be exactly the same as v10.76, so I don't see a need to update to it.

There is a new Monkey's Audio release whenever they change the tiniest bit of code even if it doesn't effect the compiler output. Many changes also affect the Monkey's Audio GUI application only and are not relevant to 3rd party applications. Therefore, it's not useful to update for every release.

**Comment by enzo1982** [comment]
Monkey's Audio v10.82 is now available in continuous builds. Still no changes relevant for fre:ac compared to v10.76 though.
