### ISSUE TITLE
Interface: translations don't fit / fixed strings (no translation possible)

### ISSUE THREAD

**Issue by Vegebutcher** [enzo1982/freac#68]
I just tested the Beta 1 on Mac and found these issues:

1. "Keep time stamps..." translation doesn't fit.
![Zrzut ekranu 2019-12-16 o 10 56 47](https://user-images.githubusercontent.com/907743/70898502-1059f180-1ff5-11ea-8711-da086318db6f.png)

2. The bitrate value for Opus encoder doesn't fit.
![Zrzut ekranu 2019-12-16 o 10 55 40](https://user-images.githubusercontent.com/907743/70898628-4bf4bb80-1ff5-11ea-8196-5055b7618920.png)

3. The bitrate slider for WMA Encoder is not translated, as well as its units ("kbps"). In fact, the slider is translated, but the source string is "target bitrate", not just "bitrate" as in the interface.
![Zrzut ekranu 2019-12-16 o 10 54 47](https://user-images.githubusercontent.com/907743/70899203-7135f980-1ff6-11ea-9a5d-4ef31e979085.png)

**Comment by enzo1982** [comment]
Thank you for reporting these! I'll fix these issues for the Beta 2 release.

If you find more like these, please report them too. I think there might be a few other too small edit fields, for example, as the macOS font has slightly wider numbers than the Windows font.

**Comment by enzo1982** [comment]
Beta 2 is out now and should fix these glitches.

**Comment by Vegebutcher** [comment]
> Beta 2 is out now and should fix these glitches.

Yep, everything's fine now. Great job!
