### ISSUE TITLE
freac-1.1-alpha-20180306: using freaccmd via remote ssh produces error

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#7]
When i try to use freaccmd via remote ssh shell i get the following error:

freaccmd -help
Error: Unable to open display at <none>.

It seems as if freaccmd needs an x11 environment.

after faking a Display freaccmd runs.

export DISPLAY=:0.0
echo $DISPLAY
:0.0
freaccmd -help
fre:ac - free audio converter v1.1 Alpha 20180306 (x86-64) command line interface
Copyright (C) 2001-2018 Robert Kausch

Usage:  freaccmd [options] [file(s)]

  --encoder=<id>  | -e <id>     Specify the encoder to use (default is LAME)
  --help=<id>     | -h <id>     Print help for encoder specific options

                    -d <dir>    Specify output directory for encoded files
                    -o <file>   Specify output file name in single file mode
  --pattern=<pat> | -p <pat>    Specify output file name pattern

  --list-configs                Print a list of available configurations
  --config=<cfg>                Specify configuration to use

  --quiet                       Do not print any messages

Encoder <id> can be one of:

        avconv-alac, faac, flac, lame, meh, mac, mpc, vorbis, opus, sndfile, speex,
        wv, avconv-wma

Default for <pat> is "<artist> - <title>".

**Comment by enzo1982** [comment]
Yes, there is some one-time initialization happening at startup that tries to open an X display.

I will try to find a solution to postpone the initialization to when a window is actually created. That should fix it.

**Comment by enzo1982** [comment]
This is now fixed in enzo1982/smooth@fdb4971.

The fix will be included in the next alpha release.

**Comment by enzo1982** [comment]
Should be fixed in fre:ac 1.1 alpha 20180710.

Please close this ticket if solved. If there is no reaction, I will close this ticket in two weeks.

**Comment by wkremser** [comment]
Well ... it sort of works ... i dont get the X11 error anymore but there seems to be a problem with the translations.

./freaccmd --help
/home/wkremser/Programs/freac-1.1-alpha-20180710-linux-x64/lang/freac_ca@valencia.xml:2: parser error : XML declaration allowed only at the start of the document
<?xml version="1.0" encoding="UTF-8"?>
     ^
fre:ac - free audio converter v1.1 Alpha 20180710 (x86-64) command line interface
Copyright (C) 2001-2018 Robert Kausch

Usage:  freaccmd [options] [--] [encoder options] [file(s)]

  --encoder=<id>  | -e <id>     Specify the encoder to use (default is LAME)
  --help=<id>     | -h <id>     Print help for encoder specific options

                    -d <dir>    Specify output directory for encoded files
                    -o <file>   Specify output file name in single file mode
  --pattern=<pat> | -p <pat>    Specify output file name pattern

  --drive=<n>     | -cd <n>     Specify active CD drive (0..n)
  --track=<n>     | -t <n>      Specify input track(s) to rip (e.g. 1-5,7,9 or 'all')
  --timeout=<s>                 Timeout for CD track ripping (default is 120 seconds)
  --cddb                        Enable CDDB database lookup

  --list-configs                Print a list of available configurations
  --config=<cfg>                Specify configuration to use

  --quiet                       Do not print any messages

Use -- to separate freaccmd options from encoder options if both have the same name.

Encoder <id> can be one of:

        avconv-alac, faac, flac, lame, meh, mac, mpc, vorbis, opus, sndfile, speex,
        wv, avconv-wma

Default for <pat> is "<filename>".

**Comment by wkremser** [comment]
works :)
