### ISSUE TITLE
Command Line Hangs on JPEGs

### ISSUE THREAD

**Issue by krothschild** [enzo1982/freac#75]
When calling freac via the command-line to encode a folder, if the folder has JPEG cover-art, the app hangs on that file. If it is the last file in the folder, it will include it as the cover-art and finish, but won't move on.

for x in ~/to-convert/*;  do    /Applications/freac.app/Contents/MacOS/freaccmd -e coreaudio -b 32 -o "$x.m4a" "$x/*";  done

**Comment by enzo1982** [comment]
Thank you for reporting this!

A fix for this is now in the repository and will be in fre:ac 1.1 beta 3, to be released tomorrow (if all goes well).

**Comment by enzo1982** [comment]
This should be fixed in fre:ac 1.1 beta 3 now. Please check.

**Comment by krothschild** [comment]
Fix confirmed - I was not able to reproduce the issue with the new code,
however, the image was NOT used as the cover graphic (no image was). I
believe this bug is fixes, but wanted to note this... Also, although the
bug was written specifically for JPGs, I also later saw the issue with PNG
files (got a segmentation error), but was not able to retest this. If I do
later see the problem with PNGs I will open a separate bug. THANKS!

**Comment by enzo1982** [comment]
Thanks for confirming the fix!

freaccmd does not do any cover art handling of it's own yet, which means that the settings configured in the GUI are used.

The default there is to use separate cover art files only if they are < 100 kB, so depending on the file size, a file might end up being used as a cover graphic or not.

I will add some arguments for controlling cover art to freaccmd with the next release.
