### ISSUE TITLE
Drag and drop does not work

### ISSUE THREAD

**Issue by collectorgeneral** [enzo1982/freac#77]
**Describe the bug**
Dragging and dropping does not appear to add any files to the joblist. 

**To Reproduce**

1. Drag any folder to the joblist. Nothing happens.

**Expected behavior**

All folder contents should be added to the joblist.

**Additional context**

System: Arch Linux, DE: GNOME; freac version: latest continuous build as of this bug report.
This could be a DE specific issue, I am not sure. I do not remember ever encountering this until now.

**Comment by collectorgeneral** [comment]
On further investigation, this appears to be a GNOME specific issue and happens on quite a few other apps. So I am closing this as I do not exactly know what you can do about it, if anything at all.

**Comment by enzo1982** [comment]
Thank you for your update!

I will try to reproduce this on Arch Linux at some point, but unfortunately didn't have time yet due to the ongoing fre:ac 1.1 release preparations.

**Comment by collectorgeneral** [comment]
No worries! I switched away from GNOME anyway, I cannot get myself to like the interface. It was not particular to freac, any app had to be brought into focus before drag and drop worked. This is unlike other DEs like KDE where drag and drop does not require this. I do not know if there is anything you can actually do about it since it feels like a DE issue.
