### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Lonerider2010** [enzo1982/freac#79]
**Describe the bug**
Running fre:ac on Raspbian Buster with XFCE, I have set GTK3 and QT5 to Adwaita Dark Theme. But fre:ac is still shown in a "light" theme.

**To Reproduce**
Switch GTK3 to Adwaita Dark theme, switch QT5 to Adwaita Dark theme.

**Expected behavior**
fre:ac show be shown in the dark theme.

**System (please complete the following information)**
 - OS: Raspbian Buster
 - CPU: Raspberry Pi 4
 - RAM: 4 GB

**Additional context**
All other applications installed are shown in a dark theme, so hopefully it will be possible for fre:ac, too.

**Comment by enzo1982** [comment]
Dark mode is not supported with the Linux version of fre:ac yet. I would have loved to add it in time for the 1.1 release, but there simply was not enough time.

This will be added in one of the next updates, 1.1.1 or 1.1.2.

**Comment by enzo1982** [comment]
Dark mode on Linux is now available in the [continuous builds](https://github.com/enzo1982/freac/releases/tag/continuous) and will be part of the upcoming 1.1.2 release.

It would be great if you could give it a try before the official release.

**Comment by Lonerider2010** [comment]
Have tested build #795 and the dark theme looks fine. That was one of the last apps that blinds me.
Thanks a lot!
Just a question: how can I switch between dark and light mode?

**Comment by enzo1982** [comment]
The colors are taken from the current GTK theme, so you cannot switch between the two modes in fre:ac itself.

I plan to implement color updates upon changing the global theme, though.

**Comment by ArielRosenfeld** [comment]
it picks up the colors for gtk correctly but i think it doesnt pickup the fonts and their sizes or should i open a new bug for that?

**Comment by enzo1982** [comment]
> When started, the window of fre:ac shows a symbol as if it was maximized, where in fact its width
> is 1900 on a 1920x1200 screen. After clicking on this "maximized" symbol, the window is actually
> maximized.

fre:ac does not explicitly handle maximized state, but leaves this to the window manager. Tried on Ubuntu 20.04 and on an old Fedora installation and fre:ac starts up correctly maximized on both if it was maximized in the previous session. However, I can see how other window managers might behave differently as fre:ac is not explicitly demanding a maximized window, just a very large one filling the whole screen.

The lack of explicit maximized state handling also leads to another issue (this time also present on Ubuntu and Fedora). Even if the window is correctly maximized when fre:ac starts up, it does not remember its non-maximized size from the previous run. So when I un-maximize it, I still get a very large window with a different size than I had before.

I'll see if I can fix both of these issues.

> Now I would like to start fre:ac together with other apps needed for CD ripping by a bash script.
> If I start this bash script via terminal, fre:ac starts in dark mode. If I then use a XFCE starter to
> start this bash script, fre:ac starts in light mode.
> Do you have an idea what happens there? What part of the user environment is missing
> in this scenario?

This I really don't know. fre:ac just queries the current GTK theme for theme colors and uses that. I don't know how and why the XFCE starter would interfere with that.

**Comment by enzo1982** [comment]
> it picks up the colors for gtk correctly but i think it doesnt pickup the fonts and their sizes or should i open a new bug for that?

The font should be correct, but the font size is tacked to 8pt in fre:ac which appears very small especially on Gnome with its 11pt default font size (compared to Windows using a 9pt default size).

You can use fre:ac's --scale option as a work around. E.g. run fre:ac with `freac --scale:1.375` to get an 11pt font.

This has been a long standing issue and is unrelated to dark mode, so feel free to open a separate ticket for this. I will then post updates there.

As it happens, I'm currently actively working on scaling fre:ac to the correct font size automatically by default (you will still be able to override this with the --scale option). I even hope to be able to ship this with the 1.1.2 release, but depending on how things work out, might have to delay it by one release.

**Comment by enzo1982** [comment]
@Lonerider2010 The issues with maximized state should be fixed in the latest continuous build.

**Comment by enzo1982** [comment]
@ArielRosenfeld The latest continuous build should use the system font size.

**Comment by enzo1982** [comment]
fre:ac 1.1.2 is available now with support for dark mode on Linux, larger fonts by default and fixed maximize/restore behavior.
