### ISSUE TITLE
Original created date is not preserved when transconding

### ISSUE THREAD

**Issue by Gorrrg** [enzo1982/freac#81]
**Describe the bug**
Original creation time stamp is not preserved when transcoding.

**To Reproduce**
1. Set the option "Keep time stamp**s** of source files", "Encode on-the-fly", "Use input folder if possible", "Allow overwriting of input files", "Filename pattern: \<filename\>"
2. Set encoder to FLAC
3. Add some non-FLAC files and encode
4. Check the file time stamps.

**Expected behavior**
The modified **and** created time stamps should match those of the originals, as it says "keep time stamp**s** (plural)" in the settings.

**System (please complete the following information)**
 - OS: Windows 10
 - CPU: Intel Core i7 6700K
 - RAM: 16 GB
 - fre:ac version: 1.1 beta 3

**Comment by enzo1982** [comment]
Thank you for reporting this!

I can confirm the issue and will have a fix ready soon.

**Comment by enzo1982** [comment]
This should be fixed now with commit 313e2d8f.

You can try this updated version: [freac-1.1-beta3-filetimefix-windows-x64.zip](https://github.com/enzo1982/freac/files/4201808/freac-1.1-beta3-filetimefix-windows-x64.zip)

**Comment by Gorrrg** [comment]
It works!

**Comment by enzo1982** [comment]
Great! Thanks for reporting back!
