### ISSUE TITLE
Option to delete source files

### ISSUE THREAD

**Issue by Gorrrg** [enzo1982/freac#82]
**Is your feature request related to a problem? Please describe.**
When transcoding without the option to automatically delete the source file after a successful conversion, disk space usage is getting roughly doubled in case of lossless to lossless transcoding. That makes transconding the entire music library impossible if the free space is less than the size of the music library.

**Describe the solution you'd like**
Delete the source file after a successful transcoding. Make it an option.

**Describe alternatives you've considered**
Do the conversion in batches or let fre:ac run out of disk space. Then use the operating system's file search tools to identify all files of the old format and delete. Rinse and repeat.

**Comment by enzo1982** [comment]
This is already available.

Select _Encode->Encoder options->Delete original files after encoding_ from the menu.

**Comment by Gorrrg** [comment]
Ah, I looked everywhere, but not there! lol

**Comment by enzo1982** [comment]
Admittedly this option is a bit hidden, because I consider it dangerous.

I hope I will find time to improve documentation before the 1.1 final release. Then I will add this to the "How to" section.
