### ISSUE TITLE
Lossy to Lossless warning when converting from WavPack to FLAC

### ISSUE THREAD

**Issue by Gorrrg** [enzo1982/freac#84]
**Describe the bug**
When you try and transcode wv files, fre:ac thinks they are lossy.

**To Reproduce**
1. Add .wv files (lossless, high compression confirmed)
2. Encode to lossless format

**Expected behavior**
No warning should pop-up. Or rather only when the sources are lossy WavPack files without correction files.

**Screenshots**
<img width="303" alt="freac_Warning" src="https://user-images.githubusercontent.com/24706454/74577658-a62be180-4f90-11ea-840c-2f53fbbeab8c.png">

**System (please complete the following information)**
 - OS: Windows 10
 - CPU: Intel Core i7 6700K
 - RAM: 16 GB
 - fre:ac version: freac-1.1-beta3-filetimefix-windows-x64 **

**Additional context**
Maybe fre:ac mixes up WavPack lossless and lossy mode? Or only looks at the bitrate instead of the source file header?

**Comment by enzo1982** [comment]
fre:ac uses the external wvunpack.exe under the hood to decode WavPack files.

So indeed, it does not look at the headers. All it knows that .wv files can be either lossy or lossless and thus it treats them as lossy to be on the safe side.

I should be possible, however, to build a heuristic to detect whether a file is lossy or lossless based on the bitrate. This would work most of the time and should produce this warning only for files that contain lots of silence.

**Comment by enzo1982** [comment]
I now have a fix for this in the repository. It will be included with the next update (probably a 1.1 RC 2 release next Sunday).

**Comment by enzo1982** [comment]
fre:ac 1.1 RC is available now. Please give it a try.
