### ISSUE TITLE
Crashing in ubuntu 19.10

### ISSUE THREAD

**Issue by geoiii68** [enzo1982/freac#86]
**Describe the bug**
Crashes a lot when adding folder to job list, no error given just shuts down. And has problem getting back to top level folder, have to make a few clicks.
Feature fix: get rid of the bar with last opened folder just go straight to browse window.

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**System (please complete the following information)**
 - OS: Ubuntu 19.10
 - CPU: AMD dual core 2.8 ghz
 - RAM: 10 gb

**Additional context**

**Comment by enzo1982** [comment]
Thank you for reporting this!

Such crashes are usually related to the files in the folder rather than the add folder action itself. For example, a file contained in that folder might be damaged or have a format that fre:ac does not expect.

Does it always crash when trying to add a certain folder? Or is the behavior more random even if the folder you're trying to add is the same?

Please try adding the individual files to find out if one or all of them are causing fre:ac to crash. I'll then need that file for further analysis. You can either attach it here or send it or a link to it to support@freac.org.

**Comment by geoiii68** [comment]
The problem is random. I can get anything loaded with a few tries. As I said before there is no error message it just shuts down. Maybe there is a log file I can send, I can't find one.

The only error I have gotten is with one particular file as expected, I was warned ahead there was a problem with that file and fre:ac did not crash it just let me know.

I have never had a problem with fre:ac until i moved up from ubuntu 18.04 to 19.10 but I also moved up to beta 3 at the same time so I don't know.

I really hope this can get fixed, I love the program. Ubuntu 20.04 is right around the corner.

Update:
Before i got done here, I just found the continuous build. 
I have loaded and loaded different folders many times, I would have seen the problem.
It's seems to be working now.

I still don't like the add folder dialog. It is unnecessary just go straight to browse.

Keep up the good work. When I get a job I plan on a healthy donation to the cause!

**Comment by enzo1982** [comment]
Thank you for the details!

There have been no changes that would be relevant when adding folders to the joblist between 1.1 beta 3 and the current continuous build. So it's strange that one works, but not the other. You write you considered a corrupt install - could you try with a freshly downloaded 1.1 beta 3 again?

Regarding the _Add folder_ dialog, I agree that it's pretty useless in its current form. I will consider changing it or removing it completely after the 1.1 final release. But did you consider just using drag and drop from your file manager? I find that much easier than using the _Add folder_ dialog in most cases.

**Comment by geoiii68** [comment]
The results are in!
The app is fine!

Thanks for the drag and drop note. Just dumb on my part. Tunnel vision I guess, I was just using the app. I did do it both ways to be sure and its good.

Power to the people!

**Comment by enzo1982** [comment]
Thank you for reporting back! Glad that it turned out to be OK.
