### ISSUE TITLE
Doesn't open aac files encoded with AAC LC

### ISSUE THREAD

**Issue by ezxpro** [enzo1982/freac#88]
**Describe the bug**
Doesn't open AAC LC

**To Reproduce**
1. Simply trying to open an an audio encoded with AAC LC in fre:ac latest versuib and it says "It's not possible to open the file: filename.aac

**Expected behavior**
It should open the file normally

**Screenshots**
https://imgur.com/a/KcQetyA

error message is in Portuguese

**System (please complete the following information)**
 - OS: Windows 7 SP1 64 bits
 - CPU: i3-4150
 - RAM: 4GB

**Additional context**
Trying to point to the folder where the file lies also doesn't help. Same error pops up. Audio plays normally anywhere. Apparently was recorded on an iPhone (not sure though)

**Comment by enzo1982** [comment]
Thank you for reporting this!

I can confirm the issue of being unable to open raw AAC files with fre:ac 1.1 beta 3 and later. This will be fixed in the next update (1.1 RC2 or 1.1 final).

I will provide an updated decoder module for you here later today.

**Comment by ezxpro** [comment]
I think there's no need to provide this module, I don't use fre:ac regularly, I just googled "open source audio converter" and downloaded whatever popped up in the search. Anyways, thank you very much for the support 😉👍🏾

**Comment by enzo1982** [comment]
Alright, I'll ship the updated decoder with next release then.

Thanks again for reporting this! I guess many users would not bother to report the issue, but just ignore it and try the next converter in your situation.

The bug is now fixed in the code repository.
