### ISSUE TITLE
Preserve input folder hierarchy

### ISSUE THREAD

**Issue by NeverSm1le** [enzo1982/freac#90]
**Is your feature request related to a problem? Please describe.**
When fre:ac convert all music a folder that also contain subfolders, all output file is put in a common output folder.
**Describe the solution you'd like**
I hope there is an option that preserve the hierarchy of subfolders, means the input file from a subfolder get output to a similar one at the output.

**Comment by enzo1982** [comment]
> I hope there is an option that preserve the hierarchy of subfolders

Yes, you can use the `<directory>` placeholder in the output filename pattern for this. See [this page](https://freac.org/manual/en/howto.html#anchor_pat) for further information.

**Comment by NeverSm1le** [comment]
> > I hope there is an option that preserve the hierarchy of subfolders
> 
> Yes, you can use the `<directory>` placeholder in the output filename pattern for this. See [this page](https://freac.org/manual/en/howto.html#anchor_pat) for further information.

Oh thank you, I do not know about this. Will try this now.
