### ISSUE TITLE
[Question] Command line usage

### ISSUE THREAD

**Issue by jwillmer** [enzo1982/freac#91]
I need a audio converter and would like to know if I can use this tool in a Linux system without any GUI.

**Comment by wkremser** [comment]
in principal you can, it comes with a second binary called freaccmd. 
currently there is a bug when the variable DISPLAY is not set. 
a workaround would be to execute "export DISPLAY=:0.0" in the shell before running freaccmd the first time in this session, so that a dummy value exists.

**Comment by enzo1982** [comment]
fre:ac 1.1 final, scheduled for tomorrow, will have that DISPLAY variable issue fixed. Thank you for bringing this to my attention!
