### ISSUE TITLE
freac-1.1-rc1-linux-x86_64: freaccmd again needs DISPLAY variable set.

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#92]
**Describe the bug**
when using freaccmd in a remote ssh session, the program exits with error posted under screenshots. 

this was already solved see ticket (https://github.com/enzo1982/freac/issues/7)

**To Reproduce**
run freaccmd in a remote ssh shell without X11 Forwarding enabled.

**Expected behavior**
run freaccmd without the need to set a fake DISPLAY shell variable

**Screenshots**
Unable to init server: Could not connect: Connection refused

(freaccmd:26248): Gdk-WARNING **: 09:24:52.587: cannot open display:

**System (please complete the following information)**
 - OS: Linux
 - CPU: Intel
 - RAM: 8GB

**Additional context**

**Comment by wkremser** [comment]
Same behavior in fre:ac - free audio converter v1.1 RC 2 (x86-64) command line interface

**Comment by enzo1982** [comment]
Thank you for reporting this!

This was introduced accidentally when HiDPI scale factor detection was improved for fre:ac 1.1 RC 1. Beta 3 still worked without the DISPLAY variable set.

This will be fixed in fre:ac 1.1 final scheduled for tomorrow.

**Comment by enzo1982** [comment]
fre:ac 1.1 is now available. Please confirm that this is fixed and close the issue in that case.

**Comment by wkremser** [comment]
Works again, thx for the fix

**Comment by wkremser** [comment]
Sorry, have to reopen this ... you can get the help screen without the DISPLAY variable set, but if i try to rip a cd, this happens.

Error: Unable to open display.
Error: Unable to open display.
Could not process file: Audio CD 1 - Track 1
/home/wkremser/scripts/freac-ripdisc.sh: line 12: 28534 Segmentation fault      (core dumped) ./freaccmd -e flac -cd $1 --track=all --cddb -d "/Volumes/Musik/__INCOMING__/_RIPPED_" -p "<filetype>/<albumartist>/<album>/<disc(2)><track(2)> - <artist> - <title>"

**Comment by enzo1982** [comment]
OK, this is related to the --cddb option. Sorry about that! I will provide a fix.

**Comment by enzo1982** [comment]
Should be fixed in the latest continuous build.

**Comment by wkremser** [comment]
yes, the latest continous build works without the DISPLAY variable set.
