### ISSUE TITLE
free audio converter v1.1 RC 2 (x86-64): freaccmd only rips first track of cd

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#93]
freaccmd ejects disc after ripping first track and therefore the remaining tracks fail to encode
Call:
freaccmd -e flac -cd 0 --track=all --cddb -d "/Volumes/Musik/__INCOMING__/_RIPPED_" -p "<filetype>/<albumartist>/<album>/<disc(2)><track(2)> - <artist> - <title>"

Output: 
Processing file: Audio CD 0 - Track 1...done.
Could not process file: Audio CD 0 - Track 2
Could not process file: Audio CD 0 - Track 3
Could not process file: Audio CD 0 - Track 4
Could not process file: Audio CD 0 - Track 5
Could not process file: Audio CD 0 - Track 6
Could not process file: Audio CD 0 - Track 7
Could not process file: Audio CD 0 - Track 8
Could not process file: Audio CD 0 - Track 9
Could not process file: Audio CD 0 - Track 10
Could not process file: Audio CD 0 - Track 11
Could not process file: Audio CD 0 - Track 12
Could not process file: Audio CD 0 - Track 13
Could not process file: Audio CD 0 - Track 14
Could not process file: Audio CD 0 - Track 15
Could not process file: Audio CD 0 - Track 16

**Comment by enzo1982** [comment]
Thank you for reporting this!

This happens when the "Eject disc after ripping" option is enabled in the GUI. freaccmd needs to ignore that setting.

This will be fixed in fre:ac 1.1 final, scheduled for tomorrow.

**Comment by wkremser** [comment]
Great :) ... i tried to change the setting in my freac.xml file in my ~/.freac directory, but this was still ignored.

**Comment by enzo1982** [comment]
fre:ac 1.1 is now available. Please confirm that this is fixed and close the issue in that case.

**Comment by wkremser** [comment]
Now the cd is no longer ejected after the first track.
