### ISSUE TITLE
freaccmd add parameter to eject disc after finishing ripping it.

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#94]
**Is your feature request related to a problem? Please describe.**
with version 1.1 the cd is no longer ejected after the first track and rips all, or selected tracks.

**Describe the solution you'd like**
It would be nice to have a parameter to eject the disc after the ripping process is done

**Describe alternatives you've considered**

**Additional context**

**Comment by enzo1982** [comment]
Thank you for this suggestion!

The latest continuous build adds an `--eject` option to freaccmd.

**Comment by wkremser** [comment]
just tested the latest continous build. this feature works like a charm :)
