### ISSUE TITLE
freaccmd linux chose cd drive from /dev device node

### ISSUE THREAD

**Issue by wkremser** [enzo1982/freac#95]
**Is your feature request related to a problem? Please describe.**
i am running freaccmd with 4 drives to rip my collection. 
i can choose the cd drive with the parameter --drive= or -cd .. but the order is not the same as the /dev nodes.

so for example /dev/sr0 is not the same drive as if i use --drive=0

**Describe the solution you'd like**
it would be nice to select the drive from the /dev device file. also this would enable me to use labels for my 4 drives and identify them with the labels

this is my setup:
/dev/sr3
/dev/sr2
/dev/sr1
/dev/sr0

/dev/liteon-01 -> sr1
/dev/liteon-02 -> sr0
/dev/liteon-03 -> sr3
/dev/liteon-04 -> sr2

**Describe alternatives you've considered**

**Additional context**

**Comment by enzo1982** [comment]
Thank you for this suggestion!

The latest continuous build now allows specifying the device path with the `--drive=` option. I also added a `--list-drives` option to list all the drives known to fre:ac.

**Comment by wkremser** [comment]
it seems to work with direct device paths, but not with the symbolic link ones ..
i can acces /dev/sr0 to /dev/sr3 .. but if i try to use my symbolic links it only worked for the last one /dev/liteon-04

the symbolic links are set by the udev daemon, i have some rules defined for it.

**Comment by enzo1982** [comment]
Symbolic links are not supported there yet. The path you pass to the `--drive=` argument is simply compared to the one where libcdio found a drive. I'll add a fix for this.

**Comment by enzo1982** [comment]
The latest continuous build now supports symbolic links with the `--drive=` argument too.

**Comment by wkremser** [comment]
tried the lastest build, but it still has the same outcome ... only one symbolic link works .. the rest not at all.

**Comment by enzo1982** [comment]
Could you provide the output of `freaccmd --list-drives` and `ls -l <path to your symlinks>`?

**Comment by wkremser** [comment]
ls -l /dev/liteon*
lrwxrwxrwx 1 root root 3 Apr  3 10:02 /dev/liteon-01 -> sr1
lrwxrwxrwx 1 root root 3 Apr  3 10:00 /dev/liteon-02 -> sr0
lrwxrwxrwx 1 root root 3 Apr  3 10:08 /dev/liteon-03 -> sr3
lrwxrwxrwx 1 root root 3 Apr  3 10:05 /dev/liteon-04 -> sr2

 ./freaccmd --list-drives
fre:ac - free audio converter v1.1 (20200402) (x86-64) command line interface
Copyright (C) 2001-2020 Robert Kausch

Available CD drives:

        Number  Device path     Designation
        ------------------------------------------------
        0       /dev/sr0        ATAPI iHAS124   F CL9M
        1       /dev/sr3        ATAPI iHAS124   F CL9N
        2       /dev/sr1        ATAPI iHAS124   F CL9N
        3       /dev/sr2        ATAPI iHAS124   F CL9N


it works for /dev/sr0 -> /dev/liteon-02

**Comment by enzo1982** [comment]
Alright, thanks! My implementation does not handle relative symlinks properly. I'll have a fix this evening.

**Comment by enzo1982** [comment]
So, the latest update should finally work. Please check again.

**Comment by wkremser** [comment]
yes, the lastest continous build (fre:ac - free audio converter v1.1 (20200403) (x86-64) command line interface) works now like a charm :)
