### ISSUE TITLE
Fre:ac 1.0.33 does not see update to 1.1

### ISSUE THREAD

**Issue by Invictaz** [enzo1982/freac#96]
**Describe the bug**
If you scan for new updates the 1.1 update .psa is not found. I had to update manually.

**Expected behavior**
Download the 1.1 update file

**Screenshots**
![image](https://user-images.githubusercontent.com/20338545/78088836-b293be80-73c5-11ea-862a-7d8b1a60eb1b.png)

**System (please complete the following information)**
 - OS: Windows 7

**Comment by enzo1982** [comment]
That's intentional. It's to avoid migrating all users to the new version at once in case serious issues are showing up.

The update will be made available to fre:ac 1.0.x users in the next few days.

**Comment by Invictaz** [comment]
Understood
