### ISSUE TITLE
Support ATRACDENC output options

### ISSUE THREAD

**Issue by Invictaz** [enzo1982/freac#97]
**Is your feature request related to a problem? Please describe.**
If you copy atracdenc.exe to codecs/cmdline it can be shown in Fre:ac but has no configurable options such as LP4 mode (which is supported in commandline) or others.

This encoder also does decoding and ATRAC3 but only ATRAC1 is in the title. 

**Describe the solution you'd like**
GUI with selectable options

https://github.com/dcherednik/atracdenc

![image](https://user-images.githubusercontent.com/20338545/78089162-d4417580-73c6-11ea-8715-f76b262db2df.png)

**Comment by enzo1982** [comment]
The release version of fre:ac supports only ATRAC-1 encoding with atracdenc.

The author of atracdenc quite strongly discourages using it for ATRAC-3 as that encoder is unfinished and will result in bad audio quality:

- From the Readme: _"ATRAC3: - use it only if you want to improve it ;)"_
- Output when invoking the ATRAC-3 encoder: _"WARNING: ATRAC3 is uncompleted, result will be not good )))"_

If you really want to use the ATRAC-3 encoder with fre:ac, you need to copy the [boca_encoder_atrac3.1.0.xml](https://raw.githubusercontent.com/enzo1982/BoCA/master/scripts/boca_encoder_atrac3enc.1.0.xml) file to the boca folder.

The LP4 option, by the way, was added to atracdenc only 4 days ago. Too late to be included with fre:ac 1.1. The only thing this does, however, is set the bitrate to 64 kbps. You can achieve the same using the `--bitrate` argument (which is supported in the ATRAC-3 encoder script for fre:ac). Having both, the bitrate option and an LP4 option that also simply sets the bitrate, but is in turn overruled if the bitrate option is also set, would probably only add confusion.

**Comment by enzo1982** [comment]
Just noticed that the bitrate option has a minimum limit of 96 kbps in the ATRAC-3 script. I think this is because atracdenc did not support lower bitrates at the time the script was created. I'll update it to add support for lower bitrates (and thus actual LP4 mode).

**Comment by Invictaz** [comment]
Thanks for updating. What is missing is the AT3 extension. 
Only these 3 are now available

    <extension>aa3</extension>
    <extension>oma</extension>
    <extension>omg</extension>

Here is more info:

https://datatypes.net/open-at3-files

**Comment by enzo1982** [comment]
The .at3 and .wav extensions are for ATRAC-3 in RIFF containers. atracdenc does not support writing that format as far as I can see. That's why they are missing in the encoder script.

The decoder script has the .aa3, .oma and .omg extensions. There's a [second \<format\> declaration](https://github.com/enzo1982/BoCA/blob/master/scripts/boca_decoder_avconv_atrac3.1.0.xml#L16) for them.

**Comment by Invictaz** [comment]
What is the difference between AT3 and OpenMG? The DRM?

**Comment by enzo1982** [comment]
RIFF (.at3) is simply a different container format (the same that is also used for .wav and .avi files). OpenMG is another container format, it just wraps the data in a different way. OpenMG supports DRM, but atracdenc doesn't, so that aspect is not relevant here.

> Oh, and there is no option to change encoding to ATRAC1 mono 146kbps

There is no option for this in atracdenc. I assume that it automatically selects that mode when encoding a mono signal. You can change a stereo track to mono in fre:ac using the _Channel Converter_ DSP.

**Comment by Invictaz** [comment]
Well I tried doing that and it gave a "atracdenc does not respond anymore" window. So I requested that on his Github. I think the combination of the filter and the atracdenc isn't a great option.

Oh, and even after setting the output directory, FREAC still shows a "save as" window. Why? 

![image](https://user-images.githubusercontent.com/20338545/78412218-dc8df080-7612-11ea-8ac0-baf783ff8d05.png)

**Comment by enzo1982** [comment]
Just tried the _Channel Converter_ plus atracdenc here and it worked without any issues. _"atracdenc does not respond anymore"_ means atracdenc has crashed, so there might be a bug there.

The _"Save as"_ dialog is shown because you have the _"Encode to a single file"_ option enabled.

**Comment by Invictaz** [comment]
This is the error

![image](https://user-images.githubusercontent.com/20338545/78413546-2b8a5480-7618-11ea-8fd1-97b63ead006e.png)

**Comment by enzo1982** [comment]
Exit code 255 usually means the application exited abnormally, so yeah, it looks like atracdenc is crashing. Well, the author calls it pre-alpha at version 0.0.3, so I guess crashes and other issues can be expected at this point.

**Comment by enzo1982** [comment]
Closing this issue as I will not make any more changes wrt ATRAC support for now.

Once new features that you would like to see supported in fre:ac are added to atracdenc or its experimental status changes, please open a new issue.
