### ISSUE TITLE
Paste output path

### ISSUE THREAD

**Issue by Invictaz** [enzo1982/freac#98]
You cannot copy and paste the path to the output folder in this window. Only option is to select it via a treebox window. If it is 6 folders deep it's quite a hassle to scroll to. 

![image](https://user-images.githubusercontent.com/20338545/78089453-c04a4380-73c7-11ea-9921-932b7dbadab8.png)

Only this is available now

![image](https://user-images.githubusercontent.com/20338545/78089490-e66fe380-73c7-11ea-8df5-bc50788e41ba.png)

**Comment by enzo1982** [comment]
You can paste a path in the edit field in the "Select folder" dialog, no need to navigate to it all the way.

Alternatively, the path can be pasted in the corresponding field of the config dialog (also only one click away).

The reason the field is not editable in the main window is to apply basic checks when entering an output path (i.e. the configuration dialog checks whether the folder exists and offers to create it if it doesn't).

**Comment by Invictaz** [comment]
Well, it does not recognize this which is libraries\documents or c:\users\enzo\documents it just reverts it back to what it was. The only way it works if you copy the full path c:\users\enzo\documents in that field.

![image](https://user-images.githubusercontent.com/20338545/78411132-ec0b3a80-760e-11ea-9a89-ad4df8b5d226.png)

**Comment by enzo1982** [comment]
The dialog is a standard Windows dialog. If it does not support addressing the _Documents_ folder as _Library\Documents_, fre:ac can do nothing about it.

However, that dialog is used only because fre:ac 1.1 still supports Windows XP. Later versions of Windows introduced a new folder selection dialog that will be used in fre:ac 1.2. That one might actually support entering _Library\Documents_ to select the _Documents_ folder.

**Comment by Invictaz** [comment]
Oh well in that case please keep it as I tend to keep my XP machines running as long as possible.

**Comment by enzo1982** [comment]
Well, fre:ac 1.1 will receive updates until 1.2 is released. That will probably not be before 2022, so at least until then you will be able to use the latest stable release on XP.

**Comment by Invictaz** [comment]
Well even after that 80-90 % of functionality will remain working. For XP it's mostly the online functionality that made it outdated. For offline use it works fine. It opens what it should open.
The same with Android 4. It is quite old but still opens most of the apps that I want, even if it doesn't have the latest security stuff.
