### ISSUE TITLE
Win10 CD file access

### ISSUE THREAD

**Issue by casner** [enzo1982/freac#99]
**Describe the bug**
When opening the program, I get the "Access to CDROM drives denied by Windows" error. This is with and without running as administrator. I have installed all of the settings and registry edits suggested in the forums I can find, one at a time, testing after each one.

**To Reproduce**
Open fre:ac

**Expected behavior**
Expected the ability to read and rip CDs

**Screenshots**
![image](https://user-images.githubusercontent.com/691259/78178485-5791b400-7425-11ea-946a-b4bc82741cfe.png)

**System (please complete the following information)**
 - OS: Win10 64 bit Home
 - CPU: [e.g. Intel Core i7 6700K]
 - RAM: [e.g. 8 GB]
![image](https://user-images.githubusercontent.com/691259/78178985-164dd400-7426-11ea-98d4-bcfcc0b8b983.png)

**Additional context**

**Comment by enzo1982** [comment]
Hi, I've only ever seen this on Windows versions other than XP Professional when some system protection software is restricting access to the CD drives.

E.g. this user had the same issue on Windows 7 due to Comodo firewall not liking fre:ac: https://answers.microsoft.com/en-us/windows/forum/all/access-to-cd-rom-drive-being-denied-to-free-audio/703cd396-8b19-42f7-8c0a-0894c491bae0

**Comment by enzo1982** [comment]
@casner Have you been able to resolve this issue? Please close this ticket then. I'll close it in a few days if I don't hear back from you.

**Comment by stevewasiura** [comment]
I had this issue, and was able to get around it by running fre:Ac as administrator, then I had permissions to access the dvd cd-rom drive. no group policy settings for removable storage access were applied and registry settings were correct.

**Comment by willhennegan** [comment]
I still have this issue with Fre:Ac on Windows 11. I have no local/domain policies restricting removable storage, and no firewall outside of Windows Defender. The error still appears after running Fre:Ac as an Administrator as well.

**Comment by LeeThompson** [comment]
Is there any way to disable fre:ac from even looking at the drive?  I'm not planning on ripping anything.

**Comment by enzo1982** [comment]
> Is there any way to disable fre:ac from even looking at the drive? I'm not planning on ripping anything.

If you are using fre:ac on Windows, you can remove the `boca_deviceinfo_cdrip.1.0.dll` file in the `boca` folder. This will remove all CD ripping features. Doesn't work with the Microsoft Store version, though, as Windows doesn't allow modifying those.

**Comment by LeeThompson** [comment]
> > Is there any way to disable fre:ac from even looking at the drive? I'm not planning on ripping anything.
> 
> If you are using fre:ac on Windows, you can remove the `boca_deviceinfo_cdrip.1.0.dll` file in the `boca` folder. This will remove all CD ripping features. Doesn't work with the Microsoft Store version, though, as Windows doesn't allow modifying those.

That works perfectly!  Thank you!
